// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_dao.djinni

package com.steelsidekick.sguitar;

public final class ChordRecord {


    /*package*/ final Integer id;

    /*package*/ final String name;

    /*package*/ final int[] intervals;

    public ChordRecord(
            Integer id,
            String name,
            int[] intervals) {
        this.id = id;
        this.name = name;
        this.intervals = intervals;
    }

    public Integer getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public int[] getIntervals() {
        return intervals;
    }

    @Override
    public String toString() {
        return "ChordRecord{" +
                "id=" + id +
                "," + "name=" + name +
                "," + "intervals=" + intervals +
        "}";
    }

}
