// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_dao.djinni

package com.steelsidekick.sguitar;

import com.snapchat.djinni.NativeObjectManager;
import java.util.concurrent.atomic.AtomicBoolean;

public abstract class ChordDAO {
    public abstract ChordRecord[] getChords();

    public abstract Integer addChord(ChordRecord chord);

    public abstract boolean updateChord(ChordRecord chord);

    public abstract boolean deleteChord(int id);

    public static native ChordDAO createChordDao(SGuitarDatabase database);

    public static final class CppProxy extends ChordDAO
    {
        private final long nativeRef;
        private final AtomicBoolean destroyed = new AtomicBoolean(false);

        private CppProxy(long nativeRef)
        {
            if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
            this.nativeRef = nativeRef;
            NativeObjectManager.register(this, nativeRef);
        }
        public static native void nativeDestroy(long nativeRef);

        @Override
        public ChordRecord[] getChords()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_getChords(this.nativeRef);
        }
        private native ChordRecord[] native_getChords(long _nativeRef);

        @Override
        public Integer addChord(ChordRecord chord)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_addChord(this.nativeRef, chord);
        }
        private native Integer native_addChord(long _nativeRef, ChordRecord chord);

        @Override
        public boolean updateChord(ChordRecord chord)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_updateChord(this.nativeRef, chord);
        }
        private native boolean native_updateChord(long _nativeRef, ChordRecord chord);

        @Override
        public boolean deleteChord(int id)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_deleteChord(this.nativeRef, id);
        }
        private native boolean native_deleteChord(long _nativeRef, int id);
    }
}
