// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_dao.djinni

package com.steelsidekick.sguitar;

public final class GuitarStringRecord {


    /*package*/ final Integer id;

    /*package*/ final int guitarId;

    /*package*/ final int stringNumber;

    /*package*/ final String startNote;

    /*package*/ final int octave;

    public GuitarStringRecord(
            Integer id,
            int guitarId,
            int stringNumber,
            String startNote,
            int octave) {
        this.id = id;
        this.guitarId = guitarId;
        this.stringNumber = stringNumber;
        this.startNote = startNote;
        this.octave = octave;
    }

    public Integer getId() {
        return id;
    }

    public int getGuitarId() {
        return guitarId;
    }

    public int getStringNumber() {
        return stringNumber;
    }

    public String getStartNote() {
        return startNote;
    }

    public int getOctave() {
        return octave;
    }

    @Override
    public String toString() {
        return "GuitarStringRecord{" +
                "id=" + id +
                "," + "guitarId=" + guitarId +
                "," + "stringNumber=" + stringNumber +
                "," + "startNote=" + startNote +
                "," + "octave=" + octave +
        "}";
    }

}
