// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_dao.djinni

package com.steelsidekick.sguitar;

public final class GuitarAdjustmentRecord {


    /*package*/ final int id;

    /*package*/ final int guitarId;

    /*package*/ final String name;

    /*package*/ final GuitarStringAdjustmentRecord[] guitarStringAdjustments;

    public GuitarAdjustmentRecord(
            int id,
            int guitarId,
            String name,
            GuitarStringAdjustmentRecord[] guitarStringAdjustments) {
        this.id = id;
        this.guitarId = guitarId;
        this.name = name;
        this.guitarStringAdjustments = guitarStringAdjustments;
    }

    public int getId() {
        return id;
    }

    public int getGuitarId() {
        return guitarId;
    }

    public String getName() {
        return name;
    }

    public GuitarStringAdjustmentRecord[] getGuitarStringAdjustments() {
        return guitarStringAdjustments;
    }

    @Override
    public String toString() {
        return "GuitarAdjustmentRecord{" +
                "id=" + id +
                "," + "guitarId=" + guitarId +
                "," + "name=" + name +
                "," + "guitarStringAdjustments=" + guitarStringAdjustments +
        "}";
    }

}
