// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_dao.djinni

package com.steelsidekick.sguitar;

public final class GuitarStringAdjustmentRecord {


    /*package*/ final Integer id;

    /*package*/ final int guitarAdjustmentId;

    /*package*/ final int stringNumber;

    /*package*/ final int step;

    public GuitarStringAdjustmentRecord(
            Integer id,
            int guitarAdjustmentId,
            int stringNumber,
            int step) {
        this.id = id;
        this.guitarAdjustmentId = guitarAdjustmentId;
        this.stringNumber = stringNumber;
        this.step = step;
    }

    public Integer getId() {
        return id;
    }

    public int getGuitarAdjustmentId() {
        return guitarAdjustmentId;
    }

    public int getStringNumber() {
        return stringNumber;
    }

    public int getStep() {
        return step;
    }

    @Override
    public String toString() {
        return "GuitarStringAdjustmentRecord{" +
                "id=" + id +
                "," + "guitarAdjustmentId=" + guitarAdjustmentId +
                "," + "stringNumber=" + stringNumber +
                "," + "step=" + step +
        "}";
    }

}
