// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_dao.djinni

package com.steelsidekick.sguitar;

import com.snapchat.djinni.NativeObjectManager;
import java.util.concurrent.atomic.AtomicBoolean;

public abstract class GuitarDAO {
    public abstract GuitarRecord[] getGuitars();

    public abstract Integer addGuitar(GuitarRecord guitar);

    public abstract boolean updateGuitar(GuitarRecord guitar);

    public abstract boolean deleteGuitar(int id);

    public static native GuitarDAO createGuitarDao(SGDatabaseConnection database);

    public static final class CppProxy extends GuitarDAO
    {
        private final long nativeRef;
        private final AtomicBoolean destroyed = new AtomicBoolean(false);

        private CppProxy(long nativeRef)
        {
            if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
            this.nativeRef = nativeRef;
            NativeObjectManager.register(this, nativeRef);
        }
        public static native void nativeDestroy(long nativeRef);

        @Override
        public GuitarRecord[] getGuitars()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_getGuitars(this.nativeRef);
        }
        private native GuitarRecord[] native_getGuitars(long _nativeRef);

        @Override
        public Integer addGuitar(GuitarRecord guitar)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_addGuitar(this.nativeRef, guitar);
        }
        private native Integer native_addGuitar(long _nativeRef, GuitarRecord guitar);

        @Override
        public boolean updateGuitar(GuitarRecord guitar)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_updateGuitar(this.nativeRef, guitar);
        }
        private native boolean native_updateGuitar(long _nativeRef, GuitarRecord guitar);

        @Override
        public boolean deleteGuitar(int id)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_deleteGuitar(this.nativeRef, id);
        }
        private native boolean native_deleteGuitar(long _nativeRef, int id);
    }
}
