// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_dao.djinni

package com.steelsidekick.sguitar;

public final class GuitarRecord {


    /*package*/ final int id;

    /*package*/ final String name;

    /*package*/ final int numberOfFrets;

    /*package*/ final GuitarStringRecord[] guitarStrings;

    /*package*/ final GuitarAdjustmentRecord[] guitarAdjustments;

    public GuitarRecord(
            int id,
            String name,
            int numberOfFrets,
            GuitarStringRecord[] guitarStrings,
            GuitarAdjustmentRecord[] guitarAdjustments) {
        this.id = id;
        this.name = name;
        this.numberOfFrets = numberOfFrets;
        this.guitarStrings = guitarStrings;
        this.guitarAdjustments = guitarAdjustments;
    }

    public int getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public int getNumberOfFrets() {
        return numberOfFrets;
    }

    public GuitarStringRecord[] getGuitarStrings() {
        return guitarStrings;
    }

    public GuitarAdjustmentRecord[] getGuitarAdjustments() {
        return guitarAdjustments;
    }

    @Override
    public String toString() {
        return "GuitarRecord{" +
                "id=" + id +
                "," + "name=" + name +
                "," + "numberOfFrets=" + numberOfFrets +
                "," + "guitarStrings=" + guitarStrings +
                "," + "guitarAdjustments=" + guitarAdjustments +
        "}";
    }

}
