// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_dao.djinni

package com.steelsidekick.sguitar;

public final class ScaleRecord {


    /*package*/ final Integer id;

    /*package*/ final String name;

    /*package*/ final int[] semitones;

    public ScaleRecord(
            Integer id,
            String name,
            int[] semitones) {
        this.id = id;
        this.name = name;
        this.semitones = semitones;
    }

    public Integer getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public int[] getSemitones() {
        return semitones;
    }

    @Override
    public String toString() {
        return "ScaleRecord{" +
                "id=" + id +
                "," + "name=" + name +
                "," + "semitones=" + semitones +
        "}";
    }

}
