// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_dao.djinni

package com.steelsidekick.sguitar;

import com.snapchat.djinni.NativeObjectManager;
import java.util.concurrent.atomic.AtomicBoolean;

public abstract class ScaleDAO {
    public abstract ScaleRecord[] getScales();

    public abstract Integer addScale(ScaleRecord scale);

    public abstract boolean updateScale(ScaleRecord scale);

    public abstract boolean deleteScale(int id);

    public static native ScaleDAO createScaleDao(DatabaseConnection databaseConnection);

    public static final class CppProxy extends ScaleDAO
    {
        private final long nativeRef;
        private final AtomicBoolean destroyed = new AtomicBoolean(false);

        private CppProxy(long nativeRef)
        {
            if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
            this.nativeRef = nativeRef;
            NativeObjectManager.register(this, nativeRef);
        }
        public static native void nativeDestroy(long nativeRef);

        @Override
        public ScaleRecord[] getScales()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_getScales(this.nativeRef);
        }
        private native ScaleRecord[] native_getScales(long _nativeRef);

        @Override
        public Integer addScale(ScaleRecord scale)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_addScale(this.nativeRef, scale);
        }
        private native Integer native_addScale(long _nativeRef, ScaleRecord scale);

        @Override
        public boolean updateScale(ScaleRecord scale)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_updateScale(this.nativeRef, scale);
        }
        private native boolean native_updateScale(long _nativeRef, ScaleRecord scale);

        @Override
        public boolean deleteScale(int id)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_deleteScale(this.nativeRef, id);
        }
        private native boolean native_deleteScale(long _nativeRef, int id);
    }
}
