# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/john/Projects/SGuitar

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/john/Projects/SGuitar

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\" \"headers\" \"libraries\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/john/Projects/SGuitar/CMakeFiles /home/john/Projects/SGuitar//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/john/Projects/SGuitar/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named SGuitar

# Build rule for target.
SGuitar: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SGuitar
.PHONY : SGuitar

# fast build rule for target.
SGuitar/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/build
.PHONY : SGuitar/fast

#=============================================================================
# Target rules for targets named SQLiteCpp

# Build rule for target.
SQLiteCpp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SQLiteCpp
.PHONY : SQLiteCpp

# fast build rule for target.
SQLiteCpp/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sqlitecpp-build/CMakeFiles/SQLiteCpp.dir/build.make _deps/sqlitecpp-build/CMakeFiles/SQLiteCpp.dir/build
.PHONY : SQLiteCpp/fast

#=============================================================================
# Target rules for targets named SQLiteCpp_cpplint

# Build rule for target.
SQLiteCpp_cpplint: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SQLiteCpp_cpplint
.PHONY : SQLiteCpp_cpplint

# fast build rule for target.
SQLiteCpp_cpplint/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sqlitecpp-build/CMakeFiles/SQLiteCpp_cpplint.dir/build.make _deps/sqlitecpp-build/CMakeFiles/SQLiteCpp_cpplint.dir/build
.PHONY : SQLiteCpp_cpplint/fast

#=============================================================================
# Target rules for targets named sqlite3

# Build rule for target.
sqlite3: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sqlite3
.PHONY : sqlite3

# fast build rule for target.
sqlite3/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sqlitecpp-build/sqlite3/CMakeFiles/sqlite3.dir/build.make _deps/sqlitecpp-build/sqlite3/CMakeFiles/sqlite3.dir/build
.PHONY : sqlite3/fast

#=============================================================================
# Target rules for targets named doctest_with_main

# Build rule for target.
doctest_with_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 doctest_with_main
.PHONY : doctest_with_main

# fast build rule for target.
doctest_with_main/fast:
	$(MAKE) $(MAKESILENT) -f _deps/doctest-build/CMakeFiles/doctest_with_main.dir/build.make _deps/doctest-build/CMakeFiles/doctest_with_main.dir/build
.PHONY : doctest_with_main/fast

djinni/support-lib/wasm/DataRef_wasm.o: djinni/support-lib/wasm/DataRef_wasm.cpp.o
.PHONY : djinni/support-lib/wasm/DataRef_wasm.o

# target to build an object file
djinni/support-lib/wasm/DataRef_wasm.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/djinni/support-lib/wasm/DataRef_wasm.cpp.o
.PHONY : djinni/support-lib/wasm/DataRef_wasm.cpp.o

djinni/support-lib/wasm/DataRef_wasm.i: djinni/support-lib/wasm/DataRef_wasm.cpp.i
.PHONY : djinni/support-lib/wasm/DataRef_wasm.i

# target to preprocess a source file
djinni/support-lib/wasm/DataRef_wasm.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/djinni/support-lib/wasm/DataRef_wasm.cpp.i
.PHONY : djinni/support-lib/wasm/DataRef_wasm.cpp.i

djinni/support-lib/wasm/DataRef_wasm.s: djinni/support-lib/wasm/DataRef_wasm.cpp.s
.PHONY : djinni/support-lib/wasm/DataRef_wasm.s

# target to generate assembly for a file
djinni/support-lib/wasm/DataRef_wasm.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/djinni/support-lib/wasm/DataRef_wasm.cpp.s
.PHONY : djinni/support-lib/wasm/DataRef_wasm.cpp.s

djinni/support-lib/wasm/djinni_wasm.o: djinni/support-lib/wasm/djinni_wasm.cpp.o
.PHONY : djinni/support-lib/wasm/djinni_wasm.o

# target to build an object file
djinni/support-lib/wasm/djinni_wasm.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/djinni/support-lib/wasm/djinni_wasm.cpp.o
.PHONY : djinni/support-lib/wasm/djinni_wasm.cpp.o

djinni/support-lib/wasm/djinni_wasm.i: djinni/support-lib/wasm/djinni_wasm.cpp.i
.PHONY : djinni/support-lib/wasm/djinni_wasm.i

# target to preprocess a source file
djinni/support-lib/wasm/djinni_wasm.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/djinni/support-lib/wasm/djinni_wasm.cpp.i
.PHONY : djinni/support-lib/wasm/djinni_wasm.cpp.i

djinni/support-lib/wasm/djinni_wasm.s: djinni/support-lib/wasm/djinni_wasm.cpp.s
.PHONY : djinni/support-lib/wasm/djinni_wasm.s

# target to generate assembly for a file
djinni/support-lib/wasm/djinni_wasm.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/djinni/support-lib/wasm/djinni_wasm.cpp.s
.PHONY : djinni/support-lib/wasm/djinni_wasm.cpp.s

generated-src/wasm/jni_accidental_type.o: generated-src/wasm/jni_accidental_type.cpp.o
.PHONY : generated-src/wasm/jni_accidental_type.o

# target to build an object file
generated-src/wasm/jni_accidental_type.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/generated-src/wasm/jni_accidental_type.cpp.o
.PHONY : generated-src/wasm/jni_accidental_type.cpp.o

generated-src/wasm/jni_accidental_type.i: generated-src/wasm/jni_accidental_type.cpp.i
.PHONY : generated-src/wasm/jni_accidental_type.i

# target to preprocess a source file
generated-src/wasm/jni_accidental_type.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/generated-src/wasm/jni_accidental_type.cpp.i
.PHONY : generated-src/wasm/jni_accidental_type.cpp.i

generated-src/wasm/jni_accidental_type.s: generated-src/wasm/jni_accidental_type.cpp.s
.PHONY : generated-src/wasm/jni_accidental_type.s

# target to generate assembly for a file
generated-src/wasm/jni_accidental_type.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/generated-src/wasm/jni_accidental_type.cpp.s
.PHONY : generated-src/wasm/jni_accidental_type.cpp.s

generated-src/wasm/jni_chord.o: generated-src/wasm/jni_chord.cpp.o
.PHONY : generated-src/wasm/jni_chord.o

# target to build an object file
generated-src/wasm/jni_chord.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/generated-src/wasm/jni_chord.cpp.o
.PHONY : generated-src/wasm/jni_chord.cpp.o

generated-src/wasm/jni_chord.i: generated-src/wasm/jni_chord.cpp.i
.PHONY : generated-src/wasm/jni_chord.i

# target to preprocess a source file
generated-src/wasm/jni_chord.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/generated-src/wasm/jni_chord.cpp.i
.PHONY : generated-src/wasm/jni_chord.cpp.i

generated-src/wasm/jni_chord.s: generated-src/wasm/jni_chord.cpp.s
.PHONY : generated-src/wasm/jni_chord.s

# target to generate assembly for a file
generated-src/wasm/jni_chord.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/generated-src/wasm/jni_chord.cpp.s
.PHONY : generated-src/wasm/jni_chord.cpp.s

generated-src/wasm/jni_chord_DAO.o: generated-src/wasm/jni_chord_DAO.cpp.o
.PHONY : generated-src/wasm/jni_chord_DAO.o

# target to build an object file
generated-src/wasm/jni_chord_DAO.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/generated-src/wasm/jni_chord_DAO.cpp.o
.PHONY : generated-src/wasm/jni_chord_DAO.cpp.o

generated-src/wasm/jni_chord_DAO.i: generated-src/wasm/jni_chord_DAO.cpp.i
.PHONY : generated-src/wasm/jni_chord_DAO.i

# target to preprocess a source file
generated-src/wasm/jni_chord_DAO.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/generated-src/wasm/jni_chord_DAO.cpp.i
.PHONY : generated-src/wasm/jni_chord_DAO.cpp.i

generated-src/wasm/jni_chord_DAO.s: generated-src/wasm/jni_chord_DAO.cpp.s
.PHONY : generated-src/wasm/jni_chord_DAO.s

# target to generate assembly for a file
generated-src/wasm/jni_chord_DAO.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/generated-src/wasm/jni_chord_DAO.cpp.s
.PHONY : generated-src/wasm/jni_chord_DAO.cpp.s

generated-src/wasm/jni_chord_record.o: generated-src/wasm/jni_chord_record.cpp.o
.PHONY : generated-src/wasm/jni_chord_record.o

# target to build an object file
generated-src/wasm/jni_chord_record.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/generated-src/wasm/jni_chord_record.cpp.o
.PHONY : generated-src/wasm/jni_chord_record.cpp.o

generated-src/wasm/jni_chord_record.i: generated-src/wasm/jni_chord_record.cpp.i
.PHONY : generated-src/wasm/jni_chord_record.i

# target to preprocess a source file
generated-src/wasm/jni_chord_record.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/generated-src/wasm/jni_chord_record.cpp.i
.PHONY : generated-src/wasm/jni_chord_record.cpp.i

generated-src/wasm/jni_chord_record.s: generated-src/wasm/jni_chord_record.cpp.s
.PHONY : generated-src/wasm/jni_chord_record.s

# target to generate assembly for a file
generated-src/wasm/jni_chord_record.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/generated-src/wasm/jni_chord_record.cpp.s
.PHONY : generated-src/wasm/jni_chord_record.cpp.s

generated-src/wasm/jni_database_connection.o: generated-src/wasm/jni_database_connection.cpp.o
.PHONY : generated-src/wasm/jni_database_connection.o

# target to build an object file
generated-src/wasm/jni_database_connection.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/generated-src/wasm/jni_database_connection.cpp.o
.PHONY : generated-src/wasm/jni_database_connection.cpp.o

generated-src/wasm/jni_database_connection.i: generated-src/wasm/jni_database_connection.cpp.i
.PHONY : generated-src/wasm/jni_database_connection.i

# target to preprocess a source file
generated-src/wasm/jni_database_connection.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/generated-src/wasm/jni_database_connection.cpp.i
.PHONY : generated-src/wasm/jni_database_connection.cpp.i

generated-src/wasm/jni_database_connection.s: generated-src/wasm/jni_database_connection.cpp.s
.PHONY : generated-src/wasm/jni_database_connection.s

# target to generate assembly for a file
generated-src/wasm/jni_database_connection.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/generated-src/wasm/jni_database_connection.cpp.s
.PHONY : generated-src/wasm/jni_database_connection.cpp.s

generated-src/wasm/jni_guitar.o: generated-src/wasm/jni_guitar.cpp.o
.PHONY : generated-src/wasm/jni_guitar.o

# target to build an object file
generated-src/wasm/jni_guitar.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/generated-src/wasm/jni_guitar.cpp.o
.PHONY : generated-src/wasm/jni_guitar.cpp.o

generated-src/wasm/jni_guitar.i: generated-src/wasm/jni_guitar.cpp.i
.PHONY : generated-src/wasm/jni_guitar.i

# target to preprocess a source file
generated-src/wasm/jni_guitar.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/generated-src/wasm/jni_guitar.cpp.i
.PHONY : generated-src/wasm/jni_guitar.cpp.i

generated-src/wasm/jni_guitar.s: generated-src/wasm/jni_guitar.cpp.s
.PHONY : generated-src/wasm/jni_guitar.s

# target to generate assembly for a file
generated-src/wasm/jni_guitar.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/generated-src/wasm/jni_guitar.cpp.s
.PHONY : generated-src/wasm/jni_guitar.cpp.s

generated-src/wasm/jni_guitar_DAO.o: generated-src/wasm/jni_guitar_DAO.cpp.o
.PHONY : generated-src/wasm/jni_guitar_DAO.o

# target to build an object file
generated-src/wasm/jni_guitar_DAO.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/generated-src/wasm/jni_guitar_DAO.cpp.o
.PHONY : generated-src/wasm/jni_guitar_DAO.cpp.o

generated-src/wasm/jni_guitar_DAO.i: generated-src/wasm/jni_guitar_DAO.cpp.i
.PHONY : generated-src/wasm/jni_guitar_DAO.i

# target to preprocess a source file
generated-src/wasm/jni_guitar_DAO.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/generated-src/wasm/jni_guitar_DAO.cpp.i
.PHONY : generated-src/wasm/jni_guitar_DAO.cpp.i

generated-src/wasm/jni_guitar_DAO.s: generated-src/wasm/jni_guitar_DAO.cpp.s
.PHONY : generated-src/wasm/jni_guitar_DAO.s

# target to generate assembly for a file
generated-src/wasm/jni_guitar_DAO.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/generated-src/wasm/jni_guitar_DAO.cpp.s
.PHONY : generated-src/wasm/jni_guitar_DAO.cpp.s

generated-src/wasm/jni_guitar_adjustment.o: generated-src/wasm/jni_guitar_adjustment.cpp.o
.PHONY : generated-src/wasm/jni_guitar_adjustment.o

# target to build an object file
generated-src/wasm/jni_guitar_adjustment.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/generated-src/wasm/jni_guitar_adjustment.cpp.o
.PHONY : generated-src/wasm/jni_guitar_adjustment.cpp.o

generated-src/wasm/jni_guitar_adjustment.i: generated-src/wasm/jni_guitar_adjustment.cpp.i
.PHONY : generated-src/wasm/jni_guitar_adjustment.i

# target to preprocess a source file
generated-src/wasm/jni_guitar_adjustment.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/generated-src/wasm/jni_guitar_adjustment.cpp.i
.PHONY : generated-src/wasm/jni_guitar_adjustment.cpp.i

generated-src/wasm/jni_guitar_adjustment.s: generated-src/wasm/jni_guitar_adjustment.cpp.s
.PHONY : generated-src/wasm/jni_guitar_adjustment.s

# target to generate assembly for a file
generated-src/wasm/jni_guitar_adjustment.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/generated-src/wasm/jni_guitar_adjustment.cpp.s
.PHONY : generated-src/wasm/jni_guitar_adjustment.cpp.s

generated-src/wasm/jni_guitar_adjustment_position.o: generated-src/wasm/jni_guitar_adjustment_position.cpp.o
.PHONY : generated-src/wasm/jni_guitar_adjustment_position.o

# target to build an object file
generated-src/wasm/jni_guitar_adjustment_position.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/generated-src/wasm/jni_guitar_adjustment_position.cpp.o
.PHONY : generated-src/wasm/jni_guitar_adjustment_position.cpp.o

generated-src/wasm/jni_guitar_adjustment_position.i: generated-src/wasm/jni_guitar_adjustment_position.cpp.i
.PHONY : generated-src/wasm/jni_guitar_adjustment_position.i

# target to preprocess a source file
generated-src/wasm/jni_guitar_adjustment_position.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/generated-src/wasm/jni_guitar_adjustment_position.cpp.i
.PHONY : generated-src/wasm/jni_guitar_adjustment_position.cpp.i

generated-src/wasm/jni_guitar_adjustment_position.s: generated-src/wasm/jni_guitar_adjustment_position.cpp.s
.PHONY : generated-src/wasm/jni_guitar_adjustment_position.s

# target to generate assembly for a file
generated-src/wasm/jni_guitar_adjustment_position.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/generated-src/wasm/jni_guitar_adjustment_position.cpp.s
.PHONY : generated-src/wasm/jni_guitar_adjustment_position.cpp.s

generated-src/wasm/jni_guitar_adjustment_record.o: generated-src/wasm/jni_guitar_adjustment_record.cpp.o
.PHONY : generated-src/wasm/jni_guitar_adjustment_record.o

# target to build an object file
generated-src/wasm/jni_guitar_adjustment_record.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/generated-src/wasm/jni_guitar_adjustment_record.cpp.o
.PHONY : generated-src/wasm/jni_guitar_adjustment_record.cpp.o

generated-src/wasm/jni_guitar_adjustment_record.i: generated-src/wasm/jni_guitar_adjustment_record.cpp.i
.PHONY : generated-src/wasm/jni_guitar_adjustment_record.i

# target to preprocess a source file
generated-src/wasm/jni_guitar_adjustment_record.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/generated-src/wasm/jni_guitar_adjustment_record.cpp.i
.PHONY : generated-src/wasm/jni_guitar_adjustment_record.cpp.i

generated-src/wasm/jni_guitar_adjustment_record.s: generated-src/wasm/jni_guitar_adjustment_record.cpp.s
.PHONY : generated-src/wasm/jni_guitar_adjustment_record.s

# target to generate assembly for a file
generated-src/wasm/jni_guitar_adjustment_record.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/generated-src/wasm/jni_guitar_adjustment_record.cpp.s
.PHONY : generated-src/wasm/jni_guitar_adjustment_record.cpp.s

generated-src/wasm/jni_guitar_factory.o: generated-src/wasm/jni_guitar_factory.cpp.o
.PHONY : generated-src/wasm/jni_guitar_factory.o

# target to build an object file
generated-src/wasm/jni_guitar_factory.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/generated-src/wasm/jni_guitar_factory.cpp.o
.PHONY : generated-src/wasm/jni_guitar_factory.cpp.o

generated-src/wasm/jni_guitar_factory.i: generated-src/wasm/jni_guitar_factory.cpp.i
.PHONY : generated-src/wasm/jni_guitar_factory.i

# target to preprocess a source file
generated-src/wasm/jni_guitar_factory.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/generated-src/wasm/jni_guitar_factory.cpp.i
.PHONY : generated-src/wasm/jni_guitar_factory.cpp.i

generated-src/wasm/jni_guitar_factory.s: generated-src/wasm/jni_guitar_factory.cpp.s
.PHONY : generated-src/wasm/jni_guitar_factory.s

# target to generate assembly for a file
generated-src/wasm/jni_guitar_factory.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/generated-src/wasm/jni_guitar_factory.cpp.s
.PHONY : generated-src/wasm/jni_guitar_factory.cpp.s

generated-src/wasm/jni_guitar_import.o: generated-src/wasm/jni_guitar_import.cpp.o
.PHONY : generated-src/wasm/jni_guitar_import.o

# target to build an object file
generated-src/wasm/jni_guitar_import.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/generated-src/wasm/jni_guitar_import.cpp.o
.PHONY : generated-src/wasm/jni_guitar_import.cpp.o

generated-src/wasm/jni_guitar_import.i: generated-src/wasm/jni_guitar_import.cpp.i
.PHONY : generated-src/wasm/jni_guitar_import.i

# target to preprocess a source file
generated-src/wasm/jni_guitar_import.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/generated-src/wasm/jni_guitar_import.cpp.i
.PHONY : generated-src/wasm/jni_guitar_import.cpp.i

generated-src/wasm/jni_guitar_import.s: generated-src/wasm/jni_guitar_import.cpp.s
.PHONY : generated-src/wasm/jni_guitar_import.s

# target to generate assembly for a file
generated-src/wasm/jni_guitar_import.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/generated-src/wasm/jni_guitar_import.cpp.s
.PHONY : generated-src/wasm/jni_guitar_import.cpp.s

generated-src/wasm/jni_guitar_record.o: generated-src/wasm/jni_guitar_record.cpp.o
.PHONY : generated-src/wasm/jni_guitar_record.o

# target to build an object file
generated-src/wasm/jni_guitar_record.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/generated-src/wasm/jni_guitar_record.cpp.o
.PHONY : generated-src/wasm/jni_guitar_record.cpp.o

generated-src/wasm/jni_guitar_record.i: generated-src/wasm/jni_guitar_record.cpp.i
.PHONY : generated-src/wasm/jni_guitar_record.i

# target to preprocess a source file
generated-src/wasm/jni_guitar_record.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/generated-src/wasm/jni_guitar_record.cpp.i
.PHONY : generated-src/wasm/jni_guitar_record.cpp.i

generated-src/wasm/jni_guitar_record.s: generated-src/wasm/jni_guitar_record.cpp.s
.PHONY : generated-src/wasm/jni_guitar_record.s

# target to generate assembly for a file
generated-src/wasm/jni_guitar_record.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/generated-src/wasm/jni_guitar_record.cpp.s
.PHONY : generated-src/wasm/jni_guitar_record.cpp.s

generated-src/wasm/jni_guitar_string.o: generated-src/wasm/jni_guitar_string.cpp.o
.PHONY : generated-src/wasm/jni_guitar_string.o

# target to build an object file
generated-src/wasm/jni_guitar_string.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/generated-src/wasm/jni_guitar_string.cpp.o
.PHONY : generated-src/wasm/jni_guitar_string.cpp.o

generated-src/wasm/jni_guitar_string.i: generated-src/wasm/jni_guitar_string.cpp.i
.PHONY : generated-src/wasm/jni_guitar_string.i

# target to preprocess a source file
generated-src/wasm/jni_guitar_string.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/generated-src/wasm/jni_guitar_string.cpp.i
.PHONY : generated-src/wasm/jni_guitar_string.cpp.i

generated-src/wasm/jni_guitar_string.s: generated-src/wasm/jni_guitar_string.cpp.s
.PHONY : generated-src/wasm/jni_guitar_string.s

# target to generate assembly for a file
generated-src/wasm/jni_guitar_string.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/generated-src/wasm/jni_guitar_string.cpp.s
.PHONY : generated-src/wasm/jni_guitar_string.cpp.s

generated-src/wasm/jni_guitar_string_adjustment_record.o: generated-src/wasm/jni_guitar_string_adjustment_record.cpp.o
.PHONY : generated-src/wasm/jni_guitar_string_adjustment_record.o

# target to build an object file
generated-src/wasm/jni_guitar_string_adjustment_record.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/generated-src/wasm/jni_guitar_string_adjustment_record.cpp.o
.PHONY : generated-src/wasm/jni_guitar_string_adjustment_record.cpp.o

generated-src/wasm/jni_guitar_string_adjustment_record.i: generated-src/wasm/jni_guitar_string_adjustment_record.cpp.i
.PHONY : generated-src/wasm/jni_guitar_string_adjustment_record.i

# target to preprocess a source file
generated-src/wasm/jni_guitar_string_adjustment_record.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/generated-src/wasm/jni_guitar_string_adjustment_record.cpp.i
.PHONY : generated-src/wasm/jni_guitar_string_adjustment_record.cpp.i

generated-src/wasm/jni_guitar_string_adjustment_record.s: generated-src/wasm/jni_guitar_string_adjustment_record.cpp.s
.PHONY : generated-src/wasm/jni_guitar_string_adjustment_record.s

# target to generate assembly for a file
generated-src/wasm/jni_guitar_string_adjustment_record.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/generated-src/wasm/jni_guitar_string_adjustment_record.cpp.s
.PHONY : generated-src/wasm/jni_guitar_string_adjustment_record.cpp.s

generated-src/wasm/jni_guitar_string_record.o: generated-src/wasm/jni_guitar_string_record.cpp.o
.PHONY : generated-src/wasm/jni_guitar_string_record.o

# target to build an object file
generated-src/wasm/jni_guitar_string_record.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/generated-src/wasm/jni_guitar_string_record.cpp.o
.PHONY : generated-src/wasm/jni_guitar_string_record.cpp.o

generated-src/wasm/jni_guitar_string_record.i: generated-src/wasm/jni_guitar_string_record.cpp.i
.PHONY : generated-src/wasm/jni_guitar_string_record.i

# target to preprocess a source file
generated-src/wasm/jni_guitar_string_record.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/generated-src/wasm/jni_guitar_string_record.cpp.i
.PHONY : generated-src/wasm/jni_guitar_string_record.cpp.i

generated-src/wasm/jni_guitar_string_record.s: generated-src/wasm/jni_guitar_string_record.cpp.s
.PHONY : generated-src/wasm/jni_guitar_string_record.s

# target to generate assembly for a file
generated-src/wasm/jni_guitar_string_record.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/generated-src/wasm/jni_guitar_string_record.cpp.s
.PHONY : generated-src/wasm/jni_guitar_string_record.cpp.s

generated-src/wasm/jni_harmonized_scale.o: generated-src/wasm/jni_harmonized_scale.cpp.o
.PHONY : generated-src/wasm/jni_harmonized_scale.o

# target to build an object file
generated-src/wasm/jni_harmonized_scale.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/generated-src/wasm/jni_harmonized_scale.cpp.o
.PHONY : generated-src/wasm/jni_harmonized_scale.cpp.o

generated-src/wasm/jni_harmonized_scale.i: generated-src/wasm/jni_harmonized_scale.cpp.i
.PHONY : generated-src/wasm/jni_harmonized_scale.i

# target to preprocess a source file
generated-src/wasm/jni_harmonized_scale.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/generated-src/wasm/jni_harmonized_scale.cpp.i
.PHONY : generated-src/wasm/jni_harmonized_scale.cpp.i

generated-src/wasm/jni_harmonized_scale.s: generated-src/wasm/jni_harmonized_scale.cpp.s
.PHONY : generated-src/wasm/jni_harmonized_scale.s

# target to generate assembly for a file
generated-src/wasm/jni_harmonized_scale.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/generated-src/wasm/jni_harmonized_scale.cpp.s
.PHONY : generated-src/wasm/jni_harmonized_scale.cpp.s

generated-src/wasm/jni_note.o: generated-src/wasm/jni_note.cpp.o
.PHONY : generated-src/wasm/jni_note.o

# target to build an object file
generated-src/wasm/jni_note.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/generated-src/wasm/jni_note.cpp.o
.PHONY : generated-src/wasm/jni_note.cpp.o

generated-src/wasm/jni_note.i: generated-src/wasm/jni_note.cpp.i
.PHONY : generated-src/wasm/jni_note.i

# target to preprocess a source file
generated-src/wasm/jni_note.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/generated-src/wasm/jni_note.cpp.i
.PHONY : generated-src/wasm/jni_note.cpp.i

generated-src/wasm/jni_note.s: generated-src/wasm/jni_note.cpp.s
.PHONY : generated-src/wasm/jni_note.s

# target to generate assembly for a file
generated-src/wasm/jni_note.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/generated-src/wasm/jni_note.cpp.s
.PHONY : generated-src/wasm/jni_note.cpp.s

generated-src/wasm/jni_note_value.o: generated-src/wasm/jni_note_value.cpp.o
.PHONY : generated-src/wasm/jni_note_value.o

# target to build an object file
generated-src/wasm/jni_note_value.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/generated-src/wasm/jni_note_value.cpp.o
.PHONY : generated-src/wasm/jni_note_value.cpp.o

generated-src/wasm/jni_note_value.i: generated-src/wasm/jni_note_value.cpp.i
.PHONY : generated-src/wasm/jni_note_value.i

# target to preprocess a source file
generated-src/wasm/jni_note_value.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/generated-src/wasm/jni_note_value.cpp.i
.PHONY : generated-src/wasm/jni_note_value.cpp.i

generated-src/wasm/jni_note_value.s: generated-src/wasm/jni_note_value.cpp.s
.PHONY : generated-src/wasm/jni_note_value.s

# target to generate assembly for a file
generated-src/wasm/jni_note_value.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/generated-src/wasm/jni_note_value.cpp.s
.PHONY : generated-src/wasm/jni_note_value.cpp.s

generated-src/wasm/jni_scale.o: generated-src/wasm/jni_scale.cpp.o
.PHONY : generated-src/wasm/jni_scale.o

# target to build an object file
generated-src/wasm/jni_scale.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/generated-src/wasm/jni_scale.cpp.o
.PHONY : generated-src/wasm/jni_scale.cpp.o

generated-src/wasm/jni_scale.i: generated-src/wasm/jni_scale.cpp.i
.PHONY : generated-src/wasm/jni_scale.i

# target to preprocess a source file
generated-src/wasm/jni_scale.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/generated-src/wasm/jni_scale.cpp.i
.PHONY : generated-src/wasm/jni_scale.cpp.i

generated-src/wasm/jni_scale.s: generated-src/wasm/jni_scale.cpp.s
.PHONY : generated-src/wasm/jni_scale.s

# target to generate assembly for a file
generated-src/wasm/jni_scale.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/generated-src/wasm/jni_scale.cpp.s
.PHONY : generated-src/wasm/jni_scale.cpp.s

generated-src/wasm/jni_scale_DAO.o: generated-src/wasm/jni_scale_DAO.cpp.o
.PHONY : generated-src/wasm/jni_scale_DAO.o

# target to build an object file
generated-src/wasm/jni_scale_DAO.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/generated-src/wasm/jni_scale_DAO.cpp.o
.PHONY : generated-src/wasm/jni_scale_DAO.cpp.o

generated-src/wasm/jni_scale_DAO.i: generated-src/wasm/jni_scale_DAO.cpp.i
.PHONY : generated-src/wasm/jni_scale_DAO.i

# target to preprocess a source file
generated-src/wasm/jni_scale_DAO.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/generated-src/wasm/jni_scale_DAO.cpp.i
.PHONY : generated-src/wasm/jni_scale_DAO.cpp.i

generated-src/wasm/jni_scale_DAO.s: generated-src/wasm/jni_scale_DAO.cpp.s
.PHONY : generated-src/wasm/jni_scale_DAO.s

# target to generate assembly for a file
generated-src/wasm/jni_scale_DAO.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/generated-src/wasm/jni_scale_DAO.cpp.s
.PHONY : generated-src/wasm/jni_scale_DAO.cpp.s

generated-src/wasm/jni_scale_record.o: generated-src/wasm/jni_scale_record.cpp.o
.PHONY : generated-src/wasm/jni_scale_record.o

# target to build an object file
generated-src/wasm/jni_scale_record.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/generated-src/wasm/jni_scale_record.cpp.o
.PHONY : generated-src/wasm/jni_scale_record.cpp.o

generated-src/wasm/jni_scale_record.i: generated-src/wasm/jni_scale_record.cpp.i
.PHONY : generated-src/wasm/jni_scale_record.i

# target to preprocess a source file
generated-src/wasm/jni_scale_record.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/generated-src/wasm/jni_scale_record.cpp.i
.PHONY : generated-src/wasm/jni_scale_record.cpp.i

generated-src/wasm/jni_scale_record.s: generated-src/wasm/jni_scale_record.cpp.s
.PHONY : generated-src/wasm/jni_scale_record.s

# target to generate assembly for a file
generated-src/wasm/jni_scale_record.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/generated-src/wasm/jni_scale_record.cpp.s
.PHONY : generated-src/wasm/jni_scale_record.cpp.s

generated-src/wasm/jni_string_adjustment.o: generated-src/wasm/jni_string_adjustment.cpp.o
.PHONY : generated-src/wasm/jni_string_adjustment.o

# target to build an object file
generated-src/wasm/jni_string_adjustment.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/generated-src/wasm/jni_string_adjustment.cpp.o
.PHONY : generated-src/wasm/jni_string_adjustment.cpp.o

generated-src/wasm/jni_string_adjustment.i: generated-src/wasm/jni_string_adjustment.cpp.i
.PHONY : generated-src/wasm/jni_string_adjustment.i

# target to preprocess a source file
generated-src/wasm/jni_string_adjustment.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/generated-src/wasm/jni_string_adjustment.cpp.i
.PHONY : generated-src/wasm/jni_string_adjustment.cpp.i

generated-src/wasm/jni_string_adjustment.s: generated-src/wasm/jni_string_adjustment.cpp.s
.PHONY : generated-src/wasm/jni_string_adjustment.s

# target to generate assembly for a file
generated-src/wasm/jni_string_adjustment.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/generated-src/wasm/jni_string_adjustment.cpp.s
.PHONY : generated-src/wasm/jni_string_adjustment.cpp.s

src/ChordDAOImpl.o: src/ChordDAOImpl.cpp.o
.PHONY : src/ChordDAOImpl.o

# target to build an object file
src/ChordDAOImpl.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/src/ChordDAOImpl.cpp.o
.PHONY : src/ChordDAOImpl.cpp.o

src/ChordDAOImpl.i: src/ChordDAOImpl.cpp.i
.PHONY : src/ChordDAOImpl.i

# target to preprocess a source file
src/ChordDAOImpl.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/src/ChordDAOImpl.cpp.i
.PHONY : src/ChordDAOImpl.cpp.i

src/ChordDAOImpl.s: src/ChordDAOImpl.cpp.s
.PHONY : src/ChordDAOImpl.s

# target to generate assembly for a file
src/ChordDAOImpl.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/src/ChordDAOImpl.cpp.s
.PHONY : src/ChordDAOImpl.cpp.s

src/ChordImpl.o: src/ChordImpl.cpp.o
.PHONY : src/ChordImpl.o

# target to build an object file
src/ChordImpl.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/src/ChordImpl.cpp.o
.PHONY : src/ChordImpl.cpp.o

src/ChordImpl.i: src/ChordImpl.cpp.i
.PHONY : src/ChordImpl.i

# target to preprocess a source file
src/ChordImpl.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/src/ChordImpl.cpp.i
.PHONY : src/ChordImpl.cpp.i

src/ChordImpl.s: src/ChordImpl.cpp.s
.PHONY : src/ChordImpl.s

# target to generate assembly for a file
src/ChordImpl.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/src/ChordImpl.cpp.s
.PHONY : src/ChordImpl.cpp.s

src/DatabaseConnectionImpl.o: src/DatabaseConnectionImpl.cpp.o
.PHONY : src/DatabaseConnectionImpl.o

# target to build an object file
src/DatabaseConnectionImpl.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/src/DatabaseConnectionImpl.cpp.o
.PHONY : src/DatabaseConnectionImpl.cpp.o

src/DatabaseConnectionImpl.i: src/DatabaseConnectionImpl.cpp.i
.PHONY : src/DatabaseConnectionImpl.i

# target to preprocess a source file
src/DatabaseConnectionImpl.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/src/DatabaseConnectionImpl.cpp.i
.PHONY : src/DatabaseConnectionImpl.cpp.i

src/DatabaseConnectionImpl.s: src/DatabaseConnectionImpl.cpp.s
.PHONY : src/DatabaseConnectionImpl.s

# target to generate assembly for a file
src/DatabaseConnectionImpl.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/src/DatabaseConnectionImpl.cpp.s
.PHONY : src/DatabaseConnectionImpl.cpp.s

src/GuitarAdjustmentImpl.o: src/GuitarAdjustmentImpl.cpp.o
.PHONY : src/GuitarAdjustmentImpl.o

# target to build an object file
src/GuitarAdjustmentImpl.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/src/GuitarAdjustmentImpl.cpp.o
.PHONY : src/GuitarAdjustmentImpl.cpp.o

src/GuitarAdjustmentImpl.i: src/GuitarAdjustmentImpl.cpp.i
.PHONY : src/GuitarAdjustmentImpl.i

# target to preprocess a source file
src/GuitarAdjustmentImpl.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/src/GuitarAdjustmentImpl.cpp.i
.PHONY : src/GuitarAdjustmentImpl.cpp.i

src/GuitarAdjustmentImpl.s: src/GuitarAdjustmentImpl.cpp.s
.PHONY : src/GuitarAdjustmentImpl.s

# target to generate assembly for a file
src/GuitarAdjustmentImpl.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/src/GuitarAdjustmentImpl.cpp.s
.PHONY : src/GuitarAdjustmentImpl.cpp.s

src/GuitarDAOImpl.o: src/GuitarDAOImpl.cpp.o
.PHONY : src/GuitarDAOImpl.o

# target to build an object file
src/GuitarDAOImpl.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/src/GuitarDAOImpl.cpp.o
.PHONY : src/GuitarDAOImpl.cpp.o

src/GuitarDAOImpl.i: src/GuitarDAOImpl.cpp.i
.PHONY : src/GuitarDAOImpl.i

# target to preprocess a source file
src/GuitarDAOImpl.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/src/GuitarDAOImpl.cpp.i
.PHONY : src/GuitarDAOImpl.cpp.i

src/GuitarDAOImpl.s: src/GuitarDAOImpl.cpp.s
.PHONY : src/GuitarDAOImpl.s

# target to generate assembly for a file
src/GuitarDAOImpl.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/src/GuitarDAOImpl.cpp.s
.PHONY : src/GuitarDAOImpl.cpp.s

src/GuitarFactory.o: src/GuitarFactory.cpp.o
.PHONY : src/GuitarFactory.o

# target to build an object file
src/GuitarFactory.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/src/GuitarFactory.cpp.o
.PHONY : src/GuitarFactory.cpp.o

src/GuitarFactory.i: src/GuitarFactory.cpp.i
.PHONY : src/GuitarFactory.i

# target to preprocess a source file
src/GuitarFactory.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/src/GuitarFactory.cpp.i
.PHONY : src/GuitarFactory.cpp.i

src/GuitarFactory.s: src/GuitarFactory.cpp.s
.PHONY : src/GuitarFactory.s

# target to generate assembly for a file
src/GuitarFactory.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/src/GuitarFactory.cpp.s
.PHONY : src/GuitarFactory.cpp.s

src/GuitarImpl.o: src/GuitarImpl.cpp.o
.PHONY : src/GuitarImpl.o

# target to build an object file
src/GuitarImpl.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/src/GuitarImpl.cpp.o
.PHONY : src/GuitarImpl.cpp.o

src/GuitarImpl.i: src/GuitarImpl.cpp.i
.PHONY : src/GuitarImpl.i

# target to preprocess a source file
src/GuitarImpl.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/src/GuitarImpl.cpp.i
.PHONY : src/GuitarImpl.cpp.i

src/GuitarImpl.s: src/GuitarImpl.cpp.s
.PHONY : src/GuitarImpl.s

# target to generate assembly for a file
src/GuitarImpl.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/src/GuitarImpl.cpp.s
.PHONY : src/GuitarImpl.cpp.s

src/GuitarImport.o: src/GuitarImport.cpp.o
.PHONY : src/GuitarImport.o

# target to build an object file
src/GuitarImport.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/src/GuitarImport.cpp.o
.PHONY : src/GuitarImport.cpp.o

src/GuitarImport.i: src/GuitarImport.cpp.i
.PHONY : src/GuitarImport.i

# target to preprocess a source file
src/GuitarImport.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/src/GuitarImport.cpp.i
.PHONY : src/GuitarImport.cpp.i

src/GuitarImport.s: src/GuitarImport.cpp.s
.PHONY : src/GuitarImport.s

# target to generate assembly for a file
src/GuitarImport.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/src/GuitarImport.cpp.s
.PHONY : src/GuitarImport.cpp.s

src/GuitarStringImpl.o: src/GuitarStringImpl.cpp.o
.PHONY : src/GuitarStringImpl.o

# target to build an object file
src/GuitarStringImpl.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/src/GuitarStringImpl.cpp.o
.PHONY : src/GuitarStringImpl.cpp.o

src/GuitarStringImpl.i: src/GuitarStringImpl.cpp.i
.PHONY : src/GuitarStringImpl.i

# target to preprocess a source file
src/GuitarStringImpl.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/src/GuitarStringImpl.cpp.i
.PHONY : src/GuitarStringImpl.cpp.i

src/GuitarStringImpl.s: src/GuitarStringImpl.cpp.s
.PHONY : src/GuitarStringImpl.s

# target to generate assembly for a file
src/GuitarStringImpl.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/src/GuitarStringImpl.cpp.s
.PHONY : src/GuitarStringImpl.cpp.s

src/HarmonizedScaleImpl.o: src/HarmonizedScaleImpl.cpp.o
.PHONY : src/HarmonizedScaleImpl.o

# target to build an object file
src/HarmonizedScaleImpl.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/src/HarmonizedScaleImpl.cpp.o
.PHONY : src/HarmonizedScaleImpl.cpp.o

src/HarmonizedScaleImpl.i: src/HarmonizedScaleImpl.cpp.i
.PHONY : src/HarmonizedScaleImpl.i

# target to preprocess a source file
src/HarmonizedScaleImpl.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/src/HarmonizedScaleImpl.cpp.i
.PHONY : src/HarmonizedScaleImpl.cpp.i

src/HarmonizedScaleImpl.s: src/HarmonizedScaleImpl.cpp.s
.PHONY : src/HarmonizedScaleImpl.s

# target to generate assembly for a file
src/HarmonizedScaleImpl.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/src/HarmonizedScaleImpl.cpp.s
.PHONY : src/HarmonizedScaleImpl.cpp.s

src/NoteImpl.o: src/NoteImpl.cpp.o
.PHONY : src/NoteImpl.o

# target to build an object file
src/NoteImpl.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/src/NoteImpl.cpp.o
.PHONY : src/NoteImpl.cpp.o

src/NoteImpl.i: src/NoteImpl.cpp.i
.PHONY : src/NoteImpl.i

# target to preprocess a source file
src/NoteImpl.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/src/NoteImpl.cpp.i
.PHONY : src/NoteImpl.cpp.i

src/NoteImpl.s: src/NoteImpl.cpp.s
.PHONY : src/NoteImpl.s

# target to generate assembly for a file
src/NoteImpl.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/src/NoteImpl.cpp.s
.PHONY : src/NoteImpl.cpp.s

src/ScaleDAOImpl.o: src/ScaleDAOImpl.cpp.o
.PHONY : src/ScaleDAOImpl.o

# target to build an object file
src/ScaleDAOImpl.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/src/ScaleDAOImpl.cpp.o
.PHONY : src/ScaleDAOImpl.cpp.o

src/ScaleDAOImpl.i: src/ScaleDAOImpl.cpp.i
.PHONY : src/ScaleDAOImpl.i

# target to preprocess a source file
src/ScaleDAOImpl.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/src/ScaleDAOImpl.cpp.i
.PHONY : src/ScaleDAOImpl.cpp.i

src/ScaleDAOImpl.s: src/ScaleDAOImpl.cpp.s
.PHONY : src/ScaleDAOImpl.s

# target to generate assembly for a file
src/ScaleDAOImpl.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/src/ScaleDAOImpl.cpp.s
.PHONY : src/ScaleDAOImpl.cpp.s

src/ScaleImpl.o: src/ScaleImpl.cpp.o
.PHONY : src/ScaleImpl.o

# target to build an object file
src/ScaleImpl.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/src/ScaleImpl.cpp.o
.PHONY : src/ScaleImpl.cpp.o

src/ScaleImpl.i: src/ScaleImpl.cpp.i
.PHONY : src/ScaleImpl.i

# target to preprocess a source file
src/ScaleImpl.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/src/ScaleImpl.cpp.i
.PHONY : src/ScaleImpl.cpp.i

src/ScaleImpl.s: src/ScaleImpl.cpp.s
.PHONY : src/ScaleImpl.s

# target to generate assembly for a file
src/ScaleImpl.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/src/ScaleImpl.cpp.s
.PHONY : src/ScaleImpl.cpp.s

src/StringAdjustmentImpl.o: src/StringAdjustmentImpl.cpp.o
.PHONY : src/StringAdjustmentImpl.o

# target to build an object file
src/StringAdjustmentImpl.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/src/StringAdjustmentImpl.cpp.o
.PHONY : src/StringAdjustmentImpl.cpp.o

src/StringAdjustmentImpl.i: src/StringAdjustmentImpl.cpp.i
.PHONY : src/StringAdjustmentImpl.i

# target to preprocess a source file
src/StringAdjustmentImpl.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/src/StringAdjustmentImpl.cpp.i
.PHONY : src/StringAdjustmentImpl.cpp.i

src/StringAdjustmentImpl.s: src/StringAdjustmentImpl.cpp.s
.PHONY : src/StringAdjustmentImpl.s

# target to generate assembly for a file
src/StringAdjustmentImpl.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/src/StringAdjustmentImpl.cpp.s
.PHONY : src/StringAdjustmentImpl.cpp.s

src/Utility.o: src/Utility.cpp.o
.PHONY : src/Utility.o

# target to build an object file
src/Utility.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/src/Utility.cpp.o
.PHONY : src/Utility.cpp.o

src/Utility.i: src/Utility.cpp.i
.PHONY : src/Utility.i

# target to preprocess a source file
src/Utility.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/src/Utility.cpp.i
.PHONY : src/Utility.cpp.i

src/Utility.s: src/Utility.cpp.s
.PHONY : src/Utility.s

# target to generate assembly for a file
src/Utility.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SGuitar.dir/build.make CMakeFiles/SGuitar.dir/src/Utility.cpp.s
.PHONY : src/Utility.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... SQLiteCpp_cpplint"
	@echo "... SGuitar"
	@echo "... SQLiteCpp"
	@echo "... doctest_with_main"
	@echo "... sqlite3"
	@echo "... djinni/support-lib/wasm/DataRef_wasm.o"
	@echo "... djinni/support-lib/wasm/DataRef_wasm.i"
	@echo "... djinni/support-lib/wasm/DataRef_wasm.s"
	@echo "... djinni/support-lib/wasm/djinni_wasm.o"
	@echo "... djinni/support-lib/wasm/djinni_wasm.i"
	@echo "... djinni/support-lib/wasm/djinni_wasm.s"
	@echo "... generated-src/wasm/jni_accidental_type.o"
	@echo "... generated-src/wasm/jni_accidental_type.i"
	@echo "... generated-src/wasm/jni_accidental_type.s"
	@echo "... generated-src/wasm/jni_chord.o"
	@echo "... generated-src/wasm/jni_chord.i"
	@echo "... generated-src/wasm/jni_chord.s"
	@echo "... generated-src/wasm/jni_chord_DAO.o"
	@echo "... generated-src/wasm/jni_chord_DAO.i"
	@echo "... generated-src/wasm/jni_chord_DAO.s"
	@echo "... generated-src/wasm/jni_chord_record.o"
	@echo "... generated-src/wasm/jni_chord_record.i"
	@echo "... generated-src/wasm/jni_chord_record.s"
	@echo "... generated-src/wasm/jni_database_connection.o"
	@echo "... generated-src/wasm/jni_database_connection.i"
	@echo "... generated-src/wasm/jni_database_connection.s"
	@echo "... generated-src/wasm/jni_guitar.o"
	@echo "... generated-src/wasm/jni_guitar.i"
	@echo "... generated-src/wasm/jni_guitar.s"
	@echo "... generated-src/wasm/jni_guitar_DAO.o"
	@echo "... generated-src/wasm/jni_guitar_DAO.i"
	@echo "... generated-src/wasm/jni_guitar_DAO.s"
	@echo "... generated-src/wasm/jni_guitar_adjustment.o"
	@echo "... generated-src/wasm/jni_guitar_adjustment.i"
	@echo "... generated-src/wasm/jni_guitar_adjustment.s"
	@echo "... generated-src/wasm/jni_guitar_adjustment_position.o"
	@echo "... generated-src/wasm/jni_guitar_adjustment_position.i"
	@echo "... generated-src/wasm/jni_guitar_adjustment_position.s"
	@echo "... generated-src/wasm/jni_guitar_adjustment_record.o"
	@echo "... generated-src/wasm/jni_guitar_adjustment_record.i"
	@echo "... generated-src/wasm/jni_guitar_adjustment_record.s"
	@echo "... generated-src/wasm/jni_guitar_factory.o"
	@echo "... generated-src/wasm/jni_guitar_factory.i"
	@echo "... generated-src/wasm/jni_guitar_factory.s"
	@echo "... generated-src/wasm/jni_guitar_import.o"
	@echo "... generated-src/wasm/jni_guitar_import.i"
	@echo "... generated-src/wasm/jni_guitar_import.s"
	@echo "... generated-src/wasm/jni_guitar_record.o"
	@echo "... generated-src/wasm/jni_guitar_record.i"
	@echo "... generated-src/wasm/jni_guitar_record.s"
	@echo "... generated-src/wasm/jni_guitar_string.o"
	@echo "... generated-src/wasm/jni_guitar_string.i"
	@echo "... generated-src/wasm/jni_guitar_string.s"
	@echo "... generated-src/wasm/jni_guitar_string_adjustment_record.o"
	@echo "... generated-src/wasm/jni_guitar_string_adjustment_record.i"
	@echo "... generated-src/wasm/jni_guitar_string_adjustment_record.s"
	@echo "... generated-src/wasm/jni_guitar_string_record.o"
	@echo "... generated-src/wasm/jni_guitar_string_record.i"
	@echo "... generated-src/wasm/jni_guitar_string_record.s"
	@echo "... generated-src/wasm/jni_harmonized_scale.o"
	@echo "... generated-src/wasm/jni_harmonized_scale.i"
	@echo "... generated-src/wasm/jni_harmonized_scale.s"
	@echo "... generated-src/wasm/jni_note.o"
	@echo "... generated-src/wasm/jni_note.i"
	@echo "... generated-src/wasm/jni_note.s"
	@echo "... generated-src/wasm/jni_note_value.o"
	@echo "... generated-src/wasm/jni_note_value.i"
	@echo "... generated-src/wasm/jni_note_value.s"
	@echo "... generated-src/wasm/jni_scale.o"
	@echo "... generated-src/wasm/jni_scale.i"
	@echo "... generated-src/wasm/jni_scale.s"
	@echo "... generated-src/wasm/jni_scale_DAO.o"
	@echo "... generated-src/wasm/jni_scale_DAO.i"
	@echo "... generated-src/wasm/jni_scale_DAO.s"
	@echo "... generated-src/wasm/jni_scale_record.o"
	@echo "... generated-src/wasm/jni_scale_record.i"
	@echo "... generated-src/wasm/jni_scale_record.s"
	@echo "... generated-src/wasm/jni_string_adjustment.o"
	@echo "... generated-src/wasm/jni_string_adjustment.i"
	@echo "... generated-src/wasm/jni_string_adjustment.s"
	@echo "... src/ChordDAOImpl.o"
	@echo "... src/ChordDAOImpl.i"
	@echo "... src/ChordDAOImpl.s"
	@echo "... src/ChordImpl.o"
	@echo "... src/ChordImpl.i"
	@echo "... src/ChordImpl.s"
	@echo "... src/DatabaseConnectionImpl.o"
	@echo "... src/DatabaseConnectionImpl.i"
	@echo "... src/DatabaseConnectionImpl.s"
	@echo "... src/GuitarAdjustmentImpl.o"
	@echo "... src/GuitarAdjustmentImpl.i"
	@echo "... src/GuitarAdjustmentImpl.s"
	@echo "... src/GuitarDAOImpl.o"
	@echo "... src/GuitarDAOImpl.i"
	@echo "... src/GuitarDAOImpl.s"
	@echo "... src/GuitarFactory.o"
	@echo "... src/GuitarFactory.i"
	@echo "... src/GuitarFactory.s"
	@echo "... src/GuitarImpl.o"
	@echo "... src/GuitarImpl.i"
	@echo "... src/GuitarImpl.s"
	@echo "... src/GuitarImport.o"
	@echo "... src/GuitarImport.i"
	@echo "... src/GuitarImport.s"
	@echo "... src/GuitarStringImpl.o"
	@echo "... src/GuitarStringImpl.i"
	@echo "... src/GuitarStringImpl.s"
	@echo "... src/HarmonizedScaleImpl.o"
	@echo "... src/HarmonizedScaleImpl.i"
	@echo "... src/HarmonizedScaleImpl.s"
	@echo "... src/NoteImpl.o"
	@echo "... src/NoteImpl.i"
	@echo "... src/NoteImpl.s"
	@echo "... src/ScaleDAOImpl.o"
	@echo "... src/ScaleDAOImpl.i"
	@echo "... src/ScaleDAOImpl.s"
	@echo "... src/ScaleImpl.o"
	@echo "... src/ScaleImpl.i"
	@echo "... src/ScaleImpl.s"
	@echo "... src/StringAdjustmentImpl.o"
	@echo "... src/StringAdjustmentImpl.i"
	@echo "... src/StringAdjustmentImpl.s"
	@echo "... src/Utility.o"
	@echo "... src/Utility.i"
	@echo "... src/Utility.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

