// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_dao.djinni

package com.steelsidekick.sguitar;

public final class ChordRecord {


    /*package*/ final Integer mId;

    /*package*/ final String mName;

    /*package*/ final int[] mIntervals;

    public ChordRecord(
            Integer id,
            String name,
            int[] intervals) {
        this.mId = id;
        this.mName = name;
        this.mIntervals = intervals;
    }

    public Integer getId() {
        return mId;
    }

    public String getName() {
        return mName;
    }

    public int[] getIntervals() {
        return mIntervals;
    }

    @Override
    public String toString() {
        return "ChordRecord{" +
                "mId=" + mId +
                "," + "mName=" + mName +
                "," + "mIntervals=" + mIntervals +
        "}";
    }

}
