// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_objects.djinni

package com.steelsidekick.sguitar;

import com.snapchat.djinni.NativeObjectManager;
import java.util.concurrent.atomic.AtomicBoolean;

public abstract class Chord {
    public abstract NoteValue[] getNotes();

    public abstract String testDescription();

    public static native Chord createWithRootNote(NoteValue rootNote, int[] intervals);

    public static native Chord createWithNotes(NoteValue[] notes);

    public static final class CppProxy extends Chord
    {
        private final long nativeRef;
        private final AtomicBoolean destroyed = new AtomicBoolean(false);

        private CppProxy(long nativeRef)
        {
            if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
            this.nativeRef = nativeRef;
            NativeObjectManager.register(this, nativeRef);
        }
        public static native void nativeDestroy(long nativeRef);

        @Override
        public NoteValue[] getNotes()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_getNotes(this.nativeRef);
        }
        private native NoteValue[] native_getNotes(long _nativeRef);

        @Override
        public String testDescription()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_testDescription(this.nativeRef);
        }
        private native String native_testDescription(long _nativeRef);
    }
}
