// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_import.djinni

package com.steelsidekick.sguitar;

import com.snapchat.djinni.NativeObjectManager;
import java.util.concurrent.atomic.AtomicBoolean;

public abstract class GuitarImport {
    public static native boolean importJsonGuitarFromPath(String fromPath, GuitarDAO toGuitarDAO);

    public static native GuitarRecord convertJsonToGuitarRecord(String filename, String json);

    public static final class CppProxy extends GuitarImport
    {
        private final long nativeRef;
        private final AtomicBoolean destroyed = new AtomicBoolean(false);

        private CppProxy(long nativeRef)
        {
            if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
            this.nativeRef = nativeRef;
            NativeObjectManager.register(this, nativeRef);
        }
        public static native void nativeDestroy(long nativeRef);
    }
}
