// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_dao.djinni

package com.steelsidekick.sguitar;

public final class GuitarStringRecord {


    /*package*/ final Integer mId;

    /*package*/ final int mGuitarId;

    /*package*/ final int mStringNumber;

    /*package*/ final String mStartNote;

    /*package*/ final int mOctave;

    public GuitarStringRecord(
            Integer id,
            int guitarId,
            int stringNumber,
            String startNote,
            int octave) {
        this.mId = id;
        this.mGuitarId = guitarId;
        this.mStringNumber = stringNumber;
        this.mStartNote = startNote;
        this.mOctave = octave;
    }

    public Integer getId() {
        return mId;
    }

    public int getGuitarId() {
        return mGuitarId;
    }

    public int getStringNumber() {
        return mStringNumber;
    }

    public String getStartNote() {
        return mStartNote;
    }

    public int getOctave() {
        return mOctave;
    }

    @Override
    public String toString() {
        return "GuitarStringRecord{" +
                "mId=" + mId +
                "," + "mGuitarId=" + mGuitarId +
                "," + "mStringNumber=" + mStringNumber +
                "," + "mStartNote=" + mStartNote +
                "," + "mOctave=" + mOctave +
        "}";
    }

}
