// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_dao.djinni

package com.steelsidekick.sguitar;

public final class GuitarAdjustmentRecord {


    /*package*/ final Integer mId;

    /*package*/ final int mGuitarId;

    /*package*/ final String mName;

    /*package*/ final int mPosition;

    /*package*/ final int mOrder;

    /*package*/ final GuitarStringAdjustmentRecord[] mGuitarStringAdjustments;

    public GuitarAdjustmentRecord(
            Integer id,
            int guitarId,
            String name,
            int position,
            int order,
            GuitarStringAdjustmentRecord[] guitarStringAdjustments) {
        this.mId = id;
        this.mGuitarId = guitarId;
        this.mName = name;
        this.mPosition = position;
        this.mOrder = order;
        this.mGuitarStringAdjustments = guitarStringAdjustments;
    }

    public Integer getId() {
        return mId;
    }

    public int getGuitarId() {
        return mGuitarId;
    }

    public String getName() {
        return mName;
    }

    public int getPosition() {
        return mPosition;
    }

    public int getOrder() {
        return mOrder;
    }

    public GuitarStringAdjustmentRecord[] getGuitarStringAdjustments() {
        return mGuitarStringAdjustments;
    }

    @Override
    public String toString() {
        return "GuitarAdjustmentRecord{" +
                "mId=" + mId +
                "," + "mGuitarId=" + mGuitarId +
                "," + "mName=" + mName +
                "," + "mPosition=" + mPosition +
                "," + "mOrder=" + mOrder +
                "," + "mGuitarStringAdjustments=" + mGuitarStringAdjustments +
        "}";
    }

}
