// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_objects.djinni

package com.steelsidekick.sguitar;

import com.snapchat.djinni.NativeObjectManager;
import java.util.concurrent.atomic.AtomicBoolean;

public abstract class GuitarAdjustment {
    public abstract StringAdjustment[] getStringAdjustments();

    public abstract int getPosition();

    public abstract int getOrder();

    public abstract void setActivated(boolean activated);

    public abstract boolean isActivated();

    public abstract String testDescription();

    public static native GuitarAdjustment createWithStringAdjustments(StringAdjustment[] stringAdjustments, int position, int order);

    public static final class CppProxy extends GuitarAdjustment
    {
        private final long nativeRef;
        private final AtomicBoolean destroyed = new AtomicBoolean(false);

        private CppProxy(long nativeRef)
        {
            if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
            this.nativeRef = nativeRef;
            NativeObjectManager.register(this, nativeRef);
        }
        public static native void nativeDestroy(long nativeRef);

        @Override
        public StringAdjustment[] getStringAdjustments()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_getStringAdjustments(this.nativeRef);
        }
        private native StringAdjustment[] native_getStringAdjustments(long _nativeRef);

        @Override
        public int getPosition()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_getPosition(this.nativeRef);
        }
        private native int native_getPosition(long _nativeRef);

        @Override
        public int getOrder()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_getOrder(this.nativeRef);
        }
        private native int native_getOrder(long _nativeRef);

        @Override
        public void setActivated(boolean activated)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            native_setActivated(this.nativeRef, activated);
        }
        private native void native_setActivated(long _nativeRef, boolean activated);

        @Override
        public boolean isActivated()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_isActivated(this.nativeRef);
        }
        private native boolean native_isActivated(long _nativeRef);

        @Override
        public String testDescription()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_testDescription(this.nativeRef);
        }
        private native String native_testDescription(long _nativeRef);
    }
}
