// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_dao.djinni

package com.steelsidekick.sguitar;

public final class GuitarRecord {


    /*package*/ final Integer mId;

    /*package*/ final String mName;

    /*package*/ final int mNumberOfFrets;

    /*package*/ final int[] mFretMarkers;

    /*package*/ final int mType;

    /*package*/ final GuitarStringRecord[] mGuitarStrings;

    /*package*/ final GuitarAdjustmentRecord[] mGuitarAdjustments;

    public GuitarRecord(
            Integer id,
            String name,
            int numberOfFrets,
            int[] fretMarkers,
            int type,
            GuitarStringRecord[] guitarStrings,
            GuitarAdjustmentRecord[] guitarAdjustments) {
        this.mId = id;
        this.mName = name;
        this.mNumberOfFrets = numberOfFrets;
        this.mFretMarkers = fretMarkers;
        this.mType = type;
        this.mGuitarStrings = guitarStrings;
        this.mGuitarAdjustments = guitarAdjustments;
    }

    public Integer getId() {
        return mId;
    }

    public String getName() {
        return mName;
    }

    public int getNumberOfFrets() {
        return mNumberOfFrets;
    }

    public int[] getFretMarkers() {
        return mFretMarkers;
    }

    public int getType() {
        return mType;
    }

    public GuitarStringRecord[] getGuitarStrings() {
        return mGuitarStrings;
    }

    public GuitarAdjustmentRecord[] getGuitarAdjustments() {
        return mGuitarAdjustments;
    }

    @Override
    public String toString() {
        return "GuitarRecord{" +
                "mId=" + mId +
                "," + "mName=" + mName +
                "," + "mNumberOfFrets=" + mNumberOfFrets +
                "," + "mFretMarkers=" + mFretMarkers +
                "," + "mType=" + mType +
                "," + "mGuitarStrings=" + mGuitarStrings +
                "," + "mGuitarAdjustments=" + mGuitarAdjustments +
        "}";
    }

}
