// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_dao.djinni

package com.steelsidekick.sguitar;

public final class GuitarStringAdjustmentRecord {


    /*package*/ final Integer mId;

    /*package*/ final int mGuitarAdjustmentId;

    /*package*/ final int mStringNumber;

    /*package*/ final int mStep;

    public GuitarStringAdjustmentRecord(
            Integer id,
            int guitarAdjustmentId,
            int stringNumber,
            int step) {
        this.mId = id;
        this.mGuitarAdjustmentId = guitarAdjustmentId;
        this.mStringNumber = stringNumber;
        this.mStep = step;
    }

    public Integer getId() {
        return mId;
    }

    public int getGuitarAdjustmentId() {
        return mGuitarAdjustmentId;
    }

    public int getStringNumber() {
        return mStringNumber;
    }

    public int getStep() {
        return mStep;
    }

    @Override
    public String toString() {
        return "GuitarStringAdjustmentRecord{" +
                "mId=" + mId +
                "," + "mGuitarAdjustmentId=" + mGuitarAdjustmentId +
                "," + "mStringNumber=" + mStringNumber +
                "," + "mStep=" + mStep +
        "}";
    }

}
