// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_objects.djinni

package com.steelsidekick.sguitar;

import com.snapchat.djinni.NativeObjectManager;
import java.util.HashMap;
import java.util.concurrent.atomic.AtomicBoolean;

public abstract class Guitar {
    public abstract int getNumberOfFrets();

    public abstract int[] getFretMarkers();

    public abstract GuitarString[] getStrings();

    public abstract void resetStrings();

    public abstract HashMap<String, GuitarAdjustment> getGuitarAdjustments();

    public abstract void setAdjustmentActivated(String adjustmentId, boolean activated);

    public abstract boolean isAdjustmentActivated(String adjustmentId);

    public abstract String testDescription();

    public static native Guitar create(int numberOfFrets, int[] fretMarkers, GuitarString[] guitarStrings, HashMap<String, GuitarAdjustment> guitarAdjustments);

    public static final class CppProxy extends Guitar
    {
        private final long nativeRef;
        private final AtomicBoolean destroyed = new AtomicBoolean(false);

        private CppProxy(long nativeRef)
        {
            if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
            this.nativeRef = nativeRef;
            NativeObjectManager.register(this, nativeRef);
        }
        public static native void nativeDestroy(long nativeRef);

        @Override
        public int getNumberOfFrets()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_getNumberOfFrets(this.nativeRef);
        }
        private native int native_getNumberOfFrets(long _nativeRef);

        @Override
        public int[] getFretMarkers()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_getFretMarkers(this.nativeRef);
        }
        private native int[] native_getFretMarkers(long _nativeRef);

        @Override
        public GuitarString[] getStrings()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_getStrings(this.nativeRef);
        }
        private native GuitarString[] native_getStrings(long _nativeRef);

        @Override
        public void resetStrings()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            native_resetStrings(this.nativeRef);
        }
        private native void native_resetStrings(long _nativeRef);

        @Override
        public HashMap<String, GuitarAdjustment> getGuitarAdjustments()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_getGuitarAdjustments(this.nativeRef);
        }
        private native HashMap<String, GuitarAdjustment> native_getGuitarAdjustments(long _nativeRef);

        @Override
        public void setAdjustmentActivated(String adjustmentId, boolean activated)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            native_setAdjustmentActivated(this.nativeRef, adjustmentId, activated);
        }
        private native void native_setAdjustmentActivated(long _nativeRef, String adjustmentId, boolean activated);

        @Override
        public boolean isAdjustmentActivated(String adjustmentId)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_isAdjustmentActivated(this.nativeRef, adjustmentId);
        }
        private native boolean native_isAdjustmentActivated(long _nativeRef, String adjustmentId);

        @Override
        public String testDescription()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_testDescription(this.nativeRef);
        }
        private native String native_testDescription(long _nativeRef);
    }
}
