// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_dao.djinni

package com.steelsidekick.sguitar;

public final class GuitarAdjustmentRecord {


    /*package*/ final Integer id;

    /*package*/ final int guitarId;

    /*package*/ final String name;

    /*package*/ final int position;

    /*package*/ final int order;

    /*package*/ final GuitarStringAdjustmentRecord[] guitarStringAdjustments;

    public GuitarAdjustmentRecord(
            Integer id,
            int guitarId,
            String name,
            int position,
            int order,
            GuitarStringAdjustmentRecord[] guitarStringAdjustments) {
        this.id = id;
        this.guitarId = guitarId;
        this.name = name;
        this.position = position;
        this.order = order;
        this.guitarStringAdjustments = guitarStringAdjustments;
    }

    public Integer getId() {
        return id;
    }

    public int getGuitarId() {
        return guitarId;
    }

    public String getName() {
        return name;
    }

    public int getPosition() {
        return position;
    }

    public int getOrder() {
        return order;
    }

    public GuitarStringAdjustmentRecord[] getGuitarStringAdjustments() {
        return guitarStringAdjustments;
    }

    @Override
    public String toString() {
        return "GuitarAdjustmentRecord{" +
                "id=" + id +
                "," + "guitarId=" + guitarId +
                "," + "name=" + name +
                "," + "position=" + position +
                "," + "order=" + order +
                "," + "guitarStringAdjustments=" + guitarStringAdjustments +
        "}";
    }

}
