// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_dao.djinni

package com.steelsidekick.sguitar;

public final class ScaleRecord {


    /*package*/ final Integer mId;

    /*package*/ final String mName;

    /*package*/ final int[] mSemitones;

    public ScaleRecord(
            Integer id,
            String name,
            int[] semitones) {
        this.mId = id;
        this.mName = name;
        this.mSemitones = semitones;
    }

    public Integer getId() {
        return mId;
    }

    public String getName() {
        return mName;
    }

    public int[] getSemitones() {
        return mSemitones;
    }

    @Override
    public String toString() {
        return "ScaleRecord{" +
                "mId=" + mId +
                "," + "mName=" + mName +
                "," + "mSemitones=" + mSemitones +
        "}";
    }

}
