// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_objects.djinni

package com.steelsidekick.sguitar;

import com.snapchat.djinni.NativeObjectManager;
import java.util.concurrent.atomic.AtomicBoolean;

public abstract class StringAdjustment {
    public abstract int getStringNumber();

    public abstract int getStep();

    public abstract String testDescription();

    public static native StringAdjustment createWithStringNumber(int stringNumber, int step);

    public static final class CppProxy extends StringAdjustment
    {
        private final long nativeRef;
        private final AtomicBoolean destroyed = new AtomicBoolean(false);

        private CppProxy(long nativeRef)
        {
            if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
            this.nativeRef = nativeRef;
            NativeObjectManager.register(this, nativeRef);
        }
        public static native void nativeDestroy(long nativeRef);

        @Override
        public int getStringNumber()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_getStringNumber(this.nativeRef);
        }
        private native int native_getStringNumber(long _nativeRef);

        @Override
        public int getStep()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_getStep(this.nativeRef);
        }
        private native int native_getStep(long _nativeRef);

        @Override
        public String testDescription()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_testDescription(this.nativeRef);
        }
        private native String native_testDescription(long _nativeRef);
    }
}
