// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_dao.djinni

#pragma once

#include "adjustment_position.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class AdjustmentPosition final : ::djinni::JniEnum {
public:
    using CppType = ::AdjustmentPosition;
    using JniType = jobject;

    using Boxed = AdjustmentPosition;

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return static_cast<CppType>(::djinni::JniClass<AdjustmentPosition>::get().ordinal(jniEnv, j)); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, CppType c) { return ::djinni::JniClass<AdjustmentPosition>::get().create(jniEnv, static_cast<jint>(c)); }

private:
    AdjustmentPosition() : JniEnum("com/steelsidekick/sguitar/AdjustmentPosition") {}
    friend ::djinni::JniClass<AdjustmentPosition>;
};

} // namespace djinni_generated
