// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_objects.djinni

#pragma once

#include "chord.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class Chord final : ::djinni::JniInterface<::Chord, Chord> {
public:
    using CppType = std::shared_ptr<::Chord>;
    using CppOptType = std::shared_ptr<::Chord>;
    using JniType = jobject;

    using Boxed = Chord;

    ~Chord();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<Chord>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<Chord>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    Chord();
    friend ::djinni::JniClass<Chord>;
    friend ::djinni::JniInterface<::Chord, Chord>;

};

} // namespace djinni_generated
