// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_dao.djinni

#pragma once

#include "chord_DAO.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class ChordDAO final : ::djinni::JniInterface<::ChordDAO, ChordDAO> {
public:
    using CppType = std::shared_ptr<::ChordDAO>;
    using CppOptType = std::shared_ptr<::ChordDAO>;
    using JniType = jobject;

    using Boxed = ChordDAO;

    ~ChordDAO();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<ChordDAO>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<ChordDAO>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    ChordDAO();
    friend ::djinni::JniClass<ChordDAO>;
    friend ::djinni::JniInterface<::ChordDAO, ChordDAO>;

};

} // namespace djinni_generated
