// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_dao.djinni

#pragma once

#include "chord_record.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class ChordRecord final {
public:
    using CppType = ::ChordRecord;
    using JniType = jobject;

    using Boxed = ChordRecord;

    ~ChordRecord();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    ChordRecord();
    friend ::djinni::JniClass<ChordRecord>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/steelsidekick/sguitar/ChordRecord") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(ILjava/lang/String;[I)V") };
    const jfieldID field_id { ::djinni::jniGetFieldID(clazz.get(), "id", "I") };
    const jfieldID field_name { ::djinni::jniGetFieldID(clazz.get(), "name", "Ljava/lang/String;") };
    const jfieldID field_intervals { ::djinni::jniGetFieldID(clazz.get(), "intervals", "[I") };
};

} // namespace djinni_generated
