// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_dao.djinni

#pragma once

#include "database_connection.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class DatabaseConnection final : ::djinni::JniInterface<::DatabaseConnection, DatabaseConnection> {
public:
    using CppType = std::shared_ptr<::DatabaseConnection>;
    using CppOptType = std::shared_ptr<::DatabaseConnection>;
    using JniType = jobject;

    using Boxed = DatabaseConnection;

    ~DatabaseConnection();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<DatabaseConnection>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<DatabaseConnection>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    DatabaseConnection();
    friend ::djinni::JniClass<DatabaseConnection>;
    friend ::djinni::JniInterface<::DatabaseConnection, DatabaseConnection>;

};

} // namespace djinni_generated
