// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_import.djinni

#pragma once

#include "djinni_support.hpp"
#include "guitar_import.hpp"

namespace djinni_generated {

class GuitarImport final : ::djinni::JniInterface<::GuitarImport, GuitarImport> {
public:
    using CppType = std::shared_ptr<::GuitarImport>;
    using CppOptType = std::shared_ptr<::GuitarImport>;
    using JniType = jobject;

    using Boxed = GuitarImport;

    ~GuitarImport();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<GuitarImport>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<GuitarImport>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    GuitarImport();
    friend ::djinni::JniClass<GuitarImport>;
    friend ::djinni::JniInterface<::GuitarImport, GuitarImport>;

};

} // namespace djinni_generated
