// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_dao.djinni

#pragma once

#include "djinni_support.hpp"
#include "guitar_adjustment_record.hpp"

namespace djinni_generated {

class GuitarAdjustmentRecord final {
public:
    using CppType = ::GuitarAdjustmentRecord;
    using JniType = jobject;

    using Boxed = GuitarAdjustmentRecord;

    ~GuitarAdjustmentRecord();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    GuitarAdjustmentRecord();
    friend ::djinni::JniClass<GuitarAdjustmentRecord>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/steelsidekick/sguitar/GuitarAdjustmentRecord") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(IILjava/lang/String;II[Lcom/steelsidekick/sguitar/GuitarStringAdjustmentRecord;)V") };
    const jfieldID field_id { ::djinni::jniGetFieldID(clazz.get(), "id", "I") };
    const jfieldID field_guitarId { ::djinni::jniGetFieldID(clazz.get(), "guitarId", "I") };
    const jfieldID field_name { ::djinni::jniGetFieldID(clazz.get(), "name", "Ljava/lang/String;") };
    const jfieldID field_position { ::djinni::jniGetFieldID(clazz.get(), "position", "I") };
    const jfieldID field_order { ::djinni::jniGetFieldID(clazz.get(), "order", "I") };
    const jfieldID field_guitarStringAdjustments { ::djinni::jniGetFieldID(clazz.get(), "guitarStringAdjustments", "[Lcom/steelsidekick/sguitar/GuitarStringAdjustmentRecord;") };
};

} // namespace djinni_generated
