// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_import.djinni

#include "guitar_import.hpp"  // my header
#include "Marshal.hpp"
#include "guitar_DAO.hpp"
#include "guitar_record.hpp"

namespace djinni_generated {

GuitarImport::GuitarImport() : ::djinni::JniInterface<::GuitarImport, GuitarImport>("com/steelsidekick/sguitar/GuitarImport$CppProxy") {}

GuitarImport::~GuitarImport() = default;


CJNIEXPORT void JNICALL Java_com_steelsidekick_sguitar_GuitarImport_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        delete reinterpret_cast<::djinni::CppProxyHandle<::GuitarImport>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jboolean JNICALL Java_com_steelsidekick_sguitar_GuitarImport_importJsonGuitarFromPath(JNIEnv* jniEnv, jobject /*this*/, jstring j_fromPath, jobject j_toGuitarDAO)
{
    try {
        auto r = ::GuitarImport::importJsonGuitarFromPath(::djinni::String::toCpp(jniEnv, j_fromPath),
                                                          ::djinni_generated::GuitarDAO::toCpp(jniEnv, j_toGuitarDAO));
        return ::djinni::release(::djinni::Bool::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT jobject JNICALL Java_com_steelsidekick_sguitar_GuitarImport_convertJsonToGuitarRecord(JNIEnv* jniEnv, jobject /*this*/, jstring j_filename, jstring j_json)
{
    try {
        auto r = ::GuitarImport::convertJsonToGuitarRecord(::djinni::String::toCpp(jniEnv, j_filename),
                                                           ::djinni::String::toCpp(jniEnv, j_json));
        return ::djinni::release(::djinni_generated::GuitarRecord::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

} // namespace djinni_generated
