// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_objects.djinni

#include "guitar.hpp"  // my header
#include "Marshal.hpp"
#include "guitar_adjustment.hpp"
#include "guitar_string.hpp"

namespace djinni_generated {

Guitar::Guitar() : ::djinni::JniInterface<::Guitar, Guitar>("com/steelsidekick/sguitar/Guitar$CppProxy") {}

Guitar::~Guitar() = default;


CJNIEXPORT void JNICALL Java_com_steelsidekick_sguitar_Guitar_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        delete reinterpret_cast<::djinni::CppProxyHandle<::Guitar>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jobject JNICALL Java_com_steelsidekick_sguitar_Guitar_create(JNIEnv* jniEnv, jobject /*this*/, jint j_numberOfFrets, jobject j_fretMarkers, jobject j_guitarStrings, jobject j_guitarAdjustments)
{
    try {
        auto r = ::Guitar::create(::djinni::I32::toCpp(jniEnv, j_numberOfFrets),
                                  ::djinni::Array<::djinni::I32, ::djinni::JavaClassName<'I'>>::toCpp(jniEnv, j_fretMarkers),
                                  ::djinni::Array<::djinni_generated::GuitarString, ::djinni::JavaClassName<'c','o','m','/','s','t','e','e','l','s','i','d','e','k','i','c','k','/','s','g','u','i','t','a','r','/','G','u','i','t','a','r','S','t','r','i','n','g'>>::toCpp(jniEnv, j_guitarStrings),
                                  ::djinni::Map<::djinni::String, ::djinni_generated::GuitarAdjustment>::toCpp(jniEnv, j_guitarAdjustments));
        return ::djinni::release(::djinni_generated::Guitar::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT jint JNICALL Java_com_steelsidekick_sguitar_Guitar_00024CppProxy_native_1getNumberOfFrets(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        const auto& ref = ::djinni::objectFromHandleAddress<::Guitar>(nativeRef);
        auto r = ref->get_number_of_frets();
        return ::djinni::release(::djinni::I32::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT jobject JNICALL Java_com_steelsidekick_sguitar_Guitar_00024CppProxy_native_1getFretMarkers(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        const auto& ref = ::djinni::objectFromHandleAddress<::Guitar>(nativeRef);
        auto r = ref->get_fret_markers();
        return ::djinni::release(::djinni::Array<::djinni::I32, ::djinni::JavaClassName<'I'>>::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT jobject JNICALL Java_com_steelsidekick_sguitar_Guitar_00024CppProxy_native_1getStrings(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        const auto& ref = ::djinni::objectFromHandleAddress<::Guitar>(nativeRef);
        auto r = ref->get_strings();
        return ::djinni::release(::djinni::Array<::djinni_generated::GuitarString, ::djinni::JavaClassName<'c','o','m','/','s','t','e','e','l','s','i','d','e','k','i','c','k','/','s','g','u','i','t','a','r','/','G','u','i','t','a','r','S','t','r','i','n','g'>>::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT void JNICALL Java_com_steelsidekick_sguitar_Guitar_00024CppProxy_native_1resetStrings(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        const auto& ref = ::djinni::objectFromHandleAddress<::Guitar>(nativeRef);
        ref->reset_strings();
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_com_steelsidekick_sguitar_Guitar_00024CppProxy_native_1setAdjustmentActivated(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jstring j_adjustmentId, jboolean j_activated)
{
    try {
        const auto& ref = ::djinni::objectFromHandleAddress<::Guitar>(nativeRef);
        ref->set_adjustment_activated(::djinni::String::toCpp(jniEnv, j_adjustmentId),
                                      ::djinni::Bool::toCpp(jniEnv, j_activated));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jboolean JNICALL Java_com_steelsidekick_sguitar_Guitar_00024CppProxy_native_1isAdjustmentActivated(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jstring j_adjustmentId)
{
    try {
        const auto& ref = ::djinni::objectFromHandleAddress<::Guitar>(nativeRef);
        auto r = ref->is_adjustment_activated(::djinni::String::toCpp(jniEnv, j_adjustmentId));
        return ::djinni::release(::djinni::Bool::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT jstring JNICALL Java_com_steelsidekick_sguitar_Guitar_00024CppProxy_native_1testDescription(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        const auto& ref = ::djinni::objectFromHandleAddress<::Guitar>(nativeRef);
        auto r = ref->test_description();
        return ::djinni::release(::djinni::String::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

} // namespace djinni_generated
