// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_factory.djinni

#pragma once

#include "djinni_support.hpp"
#include "guitar_factory.hpp"

namespace djinni_generated {

class GuitarFactory final : ::djinni::JniInterface<::GuitarFactory, GuitarFactory> {
public:
    using CppType = std::shared_ptr<::GuitarFactory>;
    using CppOptType = std::shared_ptr<::GuitarFactory>;
    using JniType = jobject;

    using Boxed = GuitarFactory;

    ~GuitarFactory();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<GuitarFactory>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<GuitarFactory>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    GuitarFactory();
    friend ::djinni::JniClass<GuitarFactory>;
    friend ::djinni::JniInterface<::GuitarFactory, GuitarFactory>;

};

} // namespace djinni_generated
