// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_dao.djinni

#pragma once

#include "djinni_support.hpp"
#include "guitar_adjustment_record.hpp"

namespace djinni_generated {

class JNIGuitarAdjustmentRecord final {
public:
    using CppType = ::GuitarAdjustmentRecord;
    using JniType = jobject;

    using Boxed = JNIGuitarAdjustmentRecord;

    ~JNIGuitarAdjustmentRecord();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    JNIGuitarAdjustmentRecord();
    friend ::djinni::JniClass<JNIGuitarAdjustmentRecord>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/steelsidekick/sguitar/GuitarAdjustmentRecord") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(Ljava/lang/Integer;ILjava/lang/String;II[Lcom/steelsidekick/sguitar/GuitarStringAdjustmentRecord;)V") };
    const jfieldID field_mId { ::djinni::jniGetFieldID(clazz.get(), "mId", "Ljava/lang/Integer;") };
    const jfieldID field_mGuitarId { ::djinni::jniGetFieldID(clazz.get(), "mGuitarId", "I") };
    const jfieldID field_mName { ::djinni::jniGetFieldID(clazz.get(), "mName", "Ljava/lang/String;") };
    const jfieldID field_mPosition { ::djinni::jniGetFieldID(clazz.get(), "mPosition", "I") };
    const jfieldID field_mOrder { ::djinni::jniGetFieldID(clazz.get(), "mOrder", "I") };
    const jfieldID field_mGuitarStringAdjustments { ::djinni::jniGetFieldID(clazz.get(), "mGuitarStringAdjustments", "[Lcom/steelsidekick/sguitar/GuitarStringAdjustmentRecord;") };
};

} // namespace djinni_generated
