// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_dao.djinni

#include "jni_guitar_DAO.hpp"  // my header
#include "Marshal.hpp"
#include "jni_database_connection.hpp"
#include "jni_guitar_record.hpp"

namespace djinni_generated {

JNIGuitarDAO::JNIGuitarDAO() : ::djinni::JniInterface<::GuitarDAO, JNIGuitarDAO>("com/steelsidekick/sguitar/GuitarDAO$CppProxy") {}

JNIGuitarDAO::~JNIGuitarDAO() = default;


CJNIEXPORT void JNICALL Java_com_steelsidekick_sguitar_GuitarDAO_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        delete reinterpret_cast<::djinni::CppProxyHandle<::GuitarDAO>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jobject JNICALL Java_com_steelsidekick_sguitar_GuitarDAO_createGuitarDao(JNIEnv* jniEnv, jobject /*this*/, jobject j_databaseConnection)
{
    try {
        auto r = ::GuitarDAO::create_guitar_dao(::djinni_generated::JNIDatabaseConnection::toCpp(jniEnv, j_databaseConnection));
        return ::djinni::release(::djinni_generated::JNIGuitarDAO::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT jobject JNICALL Java_com_steelsidekick_sguitar_GuitarDAO_00024CppProxy_native_1getGuitars(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        const auto& ref = ::djinni::objectFromHandleAddress<::GuitarDAO>(nativeRef);
        auto r = ref->get_guitars();
        return ::djinni::release(::djinni::Array<::djinni_generated::JNIGuitarRecord, ::djinni::JavaClassName<'c','o','m','/','s','t','e','e','l','s','i','d','e','k','i','c','k','/','s','g','u','i','t','a','r','/','G','u','i','t','a','r','R','e','c','o','r','d'>>::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT jobject JNICALL Java_com_steelsidekick_sguitar_GuitarDAO_00024CppProxy_native_1addGuitar(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jobject j_guitar)
{
    try {
        const auto& ref = ::djinni::objectFromHandleAddress<::GuitarDAO>(nativeRef);
        auto r = ref->add_guitar(::djinni_generated::JNIGuitarRecord::toCpp(jniEnv, j_guitar));
        return ::djinni::release(::djinni::Optional<std::optional, ::djinni::I32>::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT jboolean JNICALL Java_com_steelsidekick_sguitar_GuitarDAO_00024CppProxy_native_1updateGuitar(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jobject j_guitar)
{
    try {
        const auto& ref = ::djinni::objectFromHandleAddress<::GuitarDAO>(nativeRef);
        auto r = ref->update_guitar(::djinni_generated::JNIGuitarRecord::toCpp(jniEnv, j_guitar));
        return ::djinni::release(::djinni::Bool::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT jboolean JNICALL Java_com_steelsidekick_sguitar_GuitarDAO_00024CppProxy_native_1deleteGuitar(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jint j_id)
{
    try {
        const auto& ref = ::djinni::objectFromHandleAddress<::GuitarDAO>(nativeRef);
        auto r = ref->delete_guitar(::djinni::I32::toCpp(jniEnv, j_id));
        return ::djinni::release(::djinni::Bool::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

} // namespace djinni_generated
