// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_objects.djinni

#pragma once

#include "accidental_type.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class JNIAccidentalType final : ::djinni::JniEnum {
public:
    using CppType = ::AccidentalType;
    using JniType = jobject;

    using Boxed = JNIAccidentalType;

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return static_cast<CppType>(::djinni::JniClass<JNIAccidentalType>::get().ordinal(jniEnv, j)); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, CppType c) { return ::djinni::JniClass<JNIAccidentalType>::get().create(jniEnv, static_cast<jint>(c)); }

private:
    JNIAccidentalType() : JniEnum("com/steelsidekick/sguitar/AccidentalType") {}
    friend ::djinni::JniClass<JNIAccidentalType>;
};

} // namespace djinni_generated
