// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_objects.djinni

#pragma once

#include "djinni_support.hpp"
#include "guitar_adjustment.hpp"

namespace djinni_generated {

class JNIGuitarAdjustment final : ::djinni::JniInterface<::GuitarAdjustment, JNIGuitarAdjustment> {
public:
    using CppType = std::shared_ptr<::GuitarAdjustment>;
    using CppOptType = std::shared_ptr<::GuitarAdjustment>;
    using JniType = jobject;

    using Boxed = JNIGuitarAdjustment;

    ~JNIGuitarAdjustment();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<JNIGuitarAdjustment>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<JNIGuitarAdjustment>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    JNIGuitarAdjustment();
    friend ::djinni::JniClass<JNIGuitarAdjustment>;
    friend ::djinni::JniInterface<::GuitarAdjustment, JNIGuitarAdjustment>;

};

} // namespace djinni_generated
