// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_objects.djinni

#pragma once

#include "djinni_support.hpp"
#include "string_adjustment.hpp"

namespace djinni_generated {

class JNIStringAdjustment final : ::djinni::JniInterface<::StringAdjustment, JNIStringAdjustment> {
public:
    using CppType = std::shared_ptr<::StringAdjustment>;
    using CppOptType = std::shared_ptr<::StringAdjustment>;
    using JniType = jobject;

    using Boxed = JNIStringAdjustment;

    ~JNIStringAdjustment();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<JNIStringAdjustment>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<JNIStringAdjustment>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    JNIStringAdjustment();
    friend ::djinni::JniClass<JNIStringAdjustment>;
    friend ::djinni::JniInterface<::StringAdjustment, JNIStringAdjustment>;

};

} // namespace djinni_generated
