// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_dao.djinni

#pragma once

#include "chord_DAO.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class JNIChordDAO final : ::djinni::JniInterface<::ChordDAO, JNIChordDAO> {
public:
    using CppType = std::shared_ptr<::ChordDAO>;
    using CppOptType = std::shared_ptr<::ChordDAO>;
    using JniType = jobject;

    using Boxed = JNIChordDAO;

    ~JNIChordDAO();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<JNIChordDAO>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<JNIChordDAO>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    JNIChordDAO();
    friend ::djinni::JniClass<JNIChordDAO>;
    friend ::djinni::JniInterface<::ChordDAO, JNIChordDAO>;

};

} // namespace djinni_generated
