// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_factory.djinni

#include "jni_guitar_factory.hpp"  // my header
#include "jni_chord.hpp"
#include "jni_chord_record.hpp"
#include "jni_guitar.hpp"
#include "jni_guitar_record.hpp"
#include "jni_note_value.hpp"
#include "jni_scale.hpp"
#include "jni_scale_record.hpp"

namespace djinni_generated {

JNIGuitarFactory::JNIGuitarFactory() : ::djinni::JniInterface<::GuitarFactory, JNIGuitarFactory>("com/steelsidekick/sguitar/GuitarFactory$CppProxy") {}

JNIGuitarFactory::~JNIGuitarFactory() = default;


CJNIEXPORT void JNICALL Java_com_steelsidekick_sguitar_GuitarFactory_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        delete reinterpret_cast<::djinni::CppProxyHandle<::GuitarFactory>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jobject JNICALL Java_com_steelsidekick_sguitar_GuitarFactory_createGuitar(JNIEnv* jniEnv, jobject /*this*/, jobject j_guitarRecord)
{
    try {
        auto r = ::GuitarFactory::create_guitar(::djinni_generated::JNIGuitarRecord::toCpp(jniEnv, j_guitarRecord));
        return ::djinni::release(::djinni_generated::JNIGuitar::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT jobject JNICALL Java_com_steelsidekick_sguitar_GuitarFactory_createScale(JNIEnv* jniEnv, jobject /*this*/, jobject j_rootNote, jobject j_scaleRecord)
{
    try {
        auto r = ::GuitarFactory::create_scale(::djinni_generated::JNINoteValue::toCpp(jniEnv, j_rootNote),
                                               ::djinni_generated::JNIScaleRecord::toCpp(jniEnv, j_scaleRecord));
        return ::djinni::release(::djinni_generated::JNIScale::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT jobject JNICALL Java_com_steelsidekick_sguitar_GuitarFactory_createChord(JNIEnv* jniEnv, jobject /*this*/, jobject j_rootNote, jobject j_chordRecord)
{
    try {
        auto r = ::GuitarFactory::create_chord(::djinni_generated::JNINoteValue::toCpp(jniEnv, j_rootNote),
                                               ::djinni_generated::JNIChordRecord::toCpp(jniEnv, j_chordRecord));
        return ::djinni::release(::djinni_generated::JNIChord::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

} // namespace djinni_generated
