// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_dao.djinni

#pragma once

#include "djinni_support.hpp"
#include "guitar_string_record.hpp"

namespace djinni_generated {

class JNIGuitarStringRecord final {
public:
    using CppType = ::GuitarStringRecord;
    using JniType = jobject;

    using Boxed = JNIGuitarStringRecord;

    ~JNIGuitarStringRecord();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    JNIGuitarStringRecord();
    friend ::djinni::JniClass<JNIGuitarStringRecord>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/steelsidekick/sguitar/GuitarStringRecord") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(Ljava/lang/Integer;IILjava/lang/String;I)V") };
    const jfieldID field_id { ::djinni::jniGetFieldID(clazz.get(), "id", "Ljava/lang/Integer;") };
    const jfieldID field_guitarId { ::djinni::jniGetFieldID(clazz.get(), "guitarId", "I") };
    const jfieldID field_stringNumber { ::djinni::jniGetFieldID(clazz.get(), "stringNumber", "I") };
    const jfieldID field_startNote { ::djinni::jniGetFieldID(clazz.get(), "startNote", "Ljava/lang/String;") };
    const jfieldID field_octave { ::djinni::jniGetFieldID(clazz.get(), "octave", "I") };
};

} // namespace djinni_generated
