// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_dao.djinni

#include "jni_guitar_string_adjustment_record.hpp"  // my header
#include "Marshal.hpp"

namespace djinni_generated {

JNIGuitarStringAdjustmentRecord::JNIGuitarStringAdjustmentRecord() = default;

JNIGuitarStringAdjustmentRecord::~JNIGuitarStringAdjustmentRecord() = default;

auto JNIGuitarStringAdjustmentRecord::fromCpp(JNIEnv* jniEnv, const CppType& c) -> ::djinni::LocalRef<JniType> {
    const auto& data = ::djinni::JniClass<JNIGuitarStringAdjustmentRecord>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::get(::djinni::Optional<std::optional, ::djinni::I32>::fromCpp(jniEnv, c.id)),
                                                           ::djinni::get(::djinni::I32::fromCpp(jniEnv, c.guitar_adjustment_id)),
                                                           ::djinni::get(::djinni::I32::fromCpp(jniEnv, c.string_number)),
                                                           ::djinni::get(::djinni::I32::fromCpp(jniEnv, c.step)))};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto JNIGuitarStringAdjustmentRecord::toCpp(JNIEnv* jniEnv, JniType j) -> CppType {
    ::djinni::JniLocalScope jscope(jniEnv, 5);
    assert(j != nullptr);
    const auto& data = ::djinni::JniClass<JNIGuitarStringAdjustmentRecord>::get();
    return {::djinni::Optional<std::optional, ::djinni::I32>::toCpp(jniEnv, jniEnv->GetObjectField(j, data.field_id)),
            ::djinni::I32::toCpp(jniEnv, jniEnv->GetIntField(j, data.field_guitarAdjustmentId)),
            ::djinni::I32::toCpp(jniEnv, jniEnv->GetIntField(j, data.field_stringNumber)),
            ::djinni::I32::toCpp(jniEnv, jniEnv->GetIntField(j, data.field_step))};
}

} // namespace djinni_generated
