// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_objects.djinni

#pragma once

#include "chord.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class JNIChord final : ::djinni::JniInterface<::Chord, JNIChord> {
public:
    using CppType = std::shared_ptr<::Chord>;
    using CppOptType = std::shared_ptr<::Chord>;
    using JniType = jobject;

    using Boxed = JNIChord;

    ~JNIChord();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<JNIChord>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<JNIChord>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    JNIChord();
    friend ::djinni::JniClass<JNIChord>;
    friend ::djinni::JniInterface<::Chord, JNIChord>;

};

} // namespace djinni_generated
