// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_dao.djinni

#pragma once

#include "chord_record.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class JNIChordRecord final {
public:
    using CppType = ::ChordRecord;
    using JniType = jobject;

    using Boxed = JNIChordRecord;

    ~JNIChordRecord();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    JNIChordRecord();
    friend ::djinni::JniClass<JNIChordRecord>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/steelsidekick/sguitar/ChordRecord") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(Ljava/lang/Integer;Ljava/lang/String;[I)V") };
    const jfieldID field_mId { ::djinni::jniGetFieldID(clazz.get(), "mId", "Ljava/lang/Integer;") };
    const jfieldID field_mName { ::djinni::jniGetFieldID(clazz.get(), "mName", "Ljava/lang/String;") };
    const jfieldID field_mIntervals { ::djinni::jniGetFieldID(clazz.get(), "mIntervals", "[I") };
};

} // namespace djinni_generated
