// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_dao.djinni

#include "jni_chord_DAO.hpp"  // my header
#include "Marshal.hpp"
#include "jni_chord_record.hpp"
#include "jni_database_connection.hpp"

namespace djinni_generated {

JNIChordDAO::JNIChordDAO() : ::djinni::JniInterface<::ChordDAO, JNIChordDAO>("com/steelsidekick/sguitar/ChordDAO$CppProxy") {}

JNIChordDAO::~JNIChordDAO() = default;


CJNIEXPORT void JNICALL Java_com_steelsidekick_sguitar_ChordDAO_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        delete reinterpret_cast<::djinni::CppProxyHandle<::ChordDAO>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jobject JNICALL Java_com_steelsidekick_sguitar_ChordDAO_createChordDao(JNIEnv* jniEnv, jobject /*this*/, jobject j_databaseConnection)
{
    try {
        auto r = ::ChordDAO::create_chord_dao(::djinni_generated::JNIDatabaseConnection::toCpp(jniEnv, j_databaseConnection));
        return ::djinni::release(::djinni_generated::JNIChordDAO::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT jobject JNICALL Java_com_steelsidekick_sguitar_ChordDAO_00024CppProxy_native_1getChords(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        const auto& ref = ::djinni::objectFromHandleAddress<::ChordDAO>(nativeRef);
        auto r = ref->get_chords();
        return ::djinni::release(::djinni::Array<::djinni_generated::JNIChordRecord, ::djinni::JavaClassName<'c','o','m','/','s','t','e','e','l','s','i','d','e','k','i','c','k','/','s','g','u','i','t','a','r','/','C','h','o','r','d','R','e','c','o','r','d'>>::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT jobject JNICALL Java_com_steelsidekick_sguitar_ChordDAO_00024CppProxy_native_1addChord(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jobject j_chord)
{
    try {
        const auto& ref = ::djinni::objectFromHandleAddress<::ChordDAO>(nativeRef);
        auto r = ref->add_chord(::djinni_generated::JNIChordRecord::toCpp(jniEnv, j_chord));
        return ::djinni::release(::djinni::Optional<std::optional, ::djinni::I32>::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT jboolean JNICALL Java_com_steelsidekick_sguitar_ChordDAO_00024CppProxy_native_1updateChord(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jobject j_chord)
{
    try {
        const auto& ref = ::djinni::objectFromHandleAddress<::ChordDAO>(nativeRef);
        auto r = ref->update_chord(::djinni_generated::JNIChordRecord::toCpp(jniEnv, j_chord));
        return ::djinni::release(::djinni::Bool::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT jboolean JNICALL Java_com_steelsidekick_sguitar_ChordDAO_00024CppProxy_native_1deleteChord(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jint j_id)
{
    try {
        const auto& ref = ::djinni::objectFromHandleAddress<::ChordDAO>(nativeRef);
        auto r = ref->delete_chord(::djinni::I32::toCpp(jniEnv, j_id));
        return ::djinni::release(::djinni::Bool::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

} // namespace djinni_generated
