// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_dao.djinni

#include "jni_guitar_string_record.hpp"  // my header
#include "Marshal.hpp"

namespace djinni_generated {

JNIGuitarStringRecord::JNIGuitarStringRecord() = default;

JNIGuitarStringRecord::~JNIGuitarStringRecord() = default;

auto JNIGuitarStringRecord::fromCpp(JNIEnv* jniEnv, const CppType& c) -> ::djinni::LocalRef<JniType> {
    const auto& data = ::djinni::JniClass<JNIGuitarStringRecord>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::get(::djinni::Optional<std::optional, ::djinni::I32>::fromCpp(jniEnv, c.id)),
                                                           ::djinni::get(::djinni::I32::fromCpp(jniEnv, c.guitar_id)),
                                                           ::djinni::get(::djinni::I32::fromCpp(jniEnv, c.string_number)),
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.start_note)),
                                                           ::djinni::get(::djinni::I32::fromCpp(jniEnv, c.octave)))};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto JNIGuitarStringRecord::toCpp(JNIEnv* jniEnv, JniType j) -> CppType {
    ::djinni::JniLocalScope jscope(jniEnv, 6);
    assert(j != nullptr);
    const auto& data = ::djinni::JniClass<JNIGuitarStringRecord>::get();
    return {::djinni::Optional<std::optional, ::djinni::I32>::toCpp(jniEnv, jniEnv->GetObjectField(j, data.field_mId)),
            ::djinni::I32::toCpp(jniEnv, jniEnv->GetIntField(j, data.field_mGuitarId)),
            ::djinni::I32::toCpp(jniEnv, jniEnv->GetIntField(j, data.field_mStringNumber)),
            ::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_mStartNote)),
            ::djinni::I32::toCpp(jniEnv, jniEnv->GetIntField(j, data.field_mOctave))};
}

} // namespace djinni_generated
