// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_objects.djinni

#pragma once

#include "djinni_support.hpp"
#include "guitar.hpp"

namespace djinni_generated {

class JNIGuitar final : ::djinni::JniInterface<::Guitar, JNIGuitar> {
public:
    using CppType = std::shared_ptr<::Guitar>;
    using CppOptType = std::shared_ptr<::Guitar>;
    using JniType = jobject;

    using Boxed = JNIGuitar;

    ~JNIGuitar();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<JNIGuitar>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<JNIGuitar>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    JNIGuitar();
    friend ::djinni::JniClass<JNIGuitar>;
    friend ::djinni::JniInterface<::Guitar, JNIGuitar>;

};

} // namespace djinni_generated
