// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_objects.djinni

#pragma once

#include "djinni_support.hpp"
#include "guitar_string.hpp"

namespace djinni_generated {

class JNIGuitarString final : ::djinni::JniInterface<::GuitarString, JNIGuitarString> {
public:
    using CppType = std::shared_ptr<::GuitarString>;
    using CppOptType = std::shared_ptr<::GuitarString>;
    using JniType = jobject;

    using Boxed = JNIGuitarString;

    ~JNIGuitarString();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<JNIGuitarString>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<JNIGuitarString>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    JNIGuitarString();
    friend ::djinni::JniClass<JNIGuitarString>;
    friend ::djinni::JniInterface<::GuitarString, JNIGuitarString>;

};

} // namespace djinni_generated
