// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_dao.djinni

#pragma once

#include "djinni_support.hpp"
#include "scale_DAO.hpp"

namespace djinni_generated {

class JNIScaleDAO final : ::djinni::JniInterface<::ScaleDAO, JNIScaleDAO> {
public:
    using CppType = std::shared_ptr<::ScaleDAO>;
    using CppOptType = std::shared_ptr<::ScaleDAO>;
    using JniType = jobject;

    using Boxed = JNIScaleDAO;

    ~JNIScaleDAO();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<JNIScaleDAO>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<JNIScaleDAO>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    JNIScaleDAO();
    friend ::djinni::JniClass<JNIScaleDAO>;
    friend ::djinni::JniInterface<::ScaleDAO, JNIScaleDAO>;

};

} // namespace djinni_generated
