// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_dao.djinni

#pragma once

#include "djinni_support.hpp"
#include "guitar_adjustment_position.hpp"

namespace djinni_generated {

class JNIGuitarAdjustmentPosition final : ::djinni::JniEnum {
public:
    using CppType = ::GuitarAdjustmentPosition;
    using JniType = jobject;

    using Boxed = JNIGuitarAdjustmentPosition;

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return static_cast<CppType>(::djinni::JniClass<JNIGuitarAdjustmentPosition>::get().ordinal(jniEnv, j)); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, CppType c) { return ::djinni::JniClass<JNIGuitarAdjustmentPosition>::get().create(jniEnv, static_cast<jint>(c)); }

private:
    JNIGuitarAdjustmentPosition() : JniEnum("com/steelsidekick/sguitar/GuitarAdjustmentPosition") {}
    friend ::djinni::JniClass<JNIGuitarAdjustmentPosition>;
};

} // namespace djinni_generated
