// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_dao.djinni

#pragma once

#include "djinni_support.hpp"
#include "guitar_DAO.hpp"

namespace djinni_generated {

class JNIGuitarDAO final : ::djinni::JniInterface<::GuitarDAO, JNIGuitarDAO> {
public:
    using CppType = std::shared_ptr<::GuitarDAO>;
    using CppOptType = std::shared_ptr<::GuitarDAO>;
    using JniType = jobject;

    using Boxed = JNIGuitarDAO;

    ~JNIGuitarDAO();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<JNIGuitarDAO>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<JNIGuitarDAO>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    JNIGuitarDAO();
    friend ::djinni::JniClass<JNIGuitarDAO>;
    friend ::djinni::JniInterface<::GuitarDAO, JNIGuitarDAO>;

};

} // namespace djinni_generated
