// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_dao.djinni

#include "jni_guitar_adjustment_record.hpp"  // my header
#include "Marshal.hpp"
#include "jni_guitar_string_adjustment_record.hpp"

namespace djinni_generated {

JNIGuitarAdjustmentRecord::JNIGuitarAdjustmentRecord() = default;

JNIGuitarAdjustmentRecord::~JNIGuitarAdjustmentRecord() = default;

auto JNIGuitarAdjustmentRecord::fromCpp(JNIEnv* jniEnv, const CppType& c) -> ::djinni::LocalRef<JniType> {
    const auto& data = ::djinni::JniClass<JNIGuitarAdjustmentRecord>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::get(::djinni::Optional<std::optional, ::djinni::I32>::fromCpp(jniEnv, c.id)),
                                                           ::djinni::get(::djinni::I32::fromCpp(jniEnv, c.guitar_id)),
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.name)),
                                                           ::djinni::get(::djinni::I32::fromCpp(jniEnv, c.position)),
                                                           ::djinni::get(::djinni::I32::fromCpp(jniEnv, c.order)),
                                                           ::djinni::get(::djinni::Array<::djinni_generated::JNIGuitarStringAdjustmentRecord, ::djinni::JavaClassName<'c','o','m','/','s','t','e','e','l','s','i','d','e','k','i','c','k','/','s','g','u','i','t','a','r','/','G','u','i','t','a','r','S','t','r','i','n','g','A','d','j','u','s','t','m','e','n','t','R','e','c','o','r','d'>>::fromCpp(jniEnv, c.guitar_string_adjustments)))};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto JNIGuitarAdjustmentRecord::toCpp(JNIEnv* jniEnv, JniType j) -> CppType {
    ::djinni::JniLocalScope jscope(jniEnv, 7);
    assert(j != nullptr);
    const auto& data = ::djinni::JniClass<JNIGuitarAdjustmentRecord>::get();
    return {::djinni::Optional<std::optional, ::djinni::I32>::toCpp(jniEnv, jniEnv->GetObjectField(j, data.field_mId)),
            ::djinni::I32::toCpp(jniEnv, jniEnv->GetIntField(j, data.field_mGuitarId)),
            ::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_mName)),
            ::djinni::I32::toCpp(jniEnv, jniEnv->GetIntField(j, data.field_mPosition)),
            ::djinni::I32::toCpp(jniEnv, jniEnv->GetIntField(j, data.field_mOrder)),
            ::djinni::Array<::djinni_generated::JNIGuitarStringAdjustmentRecord, ::djinni::JavaClassName<'c','o','m','/','s','t','e','e','l','s','i','d','e','k','i','c','k','/','s','g','u','i','t','a','r','/','G','u','i','t','a','r','S','t','r','i','n','g','A','d','j','u','s','t','m','e','n','t','R','e','c','o','r','d'>>::toCpp(jniEnv, jniEnv->GetObjectField(j, data.field_mGuitarStringAdjustments))};
}

} // namespace djinni_generated
