// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_objects.djinni

#include "jni_scale.hpp"  // my header
#include "Marshal.hpp"
#include "jni_note_value.hpp"

namespace djinni_generated {

JNIScale::JNIScale() : ::djinni::JniInterface<::Scale, JNIScale>("com/steelsidekick/sguitar/Scale$CppProxy") {}

JNIScale::~JNIScale() = default;


CJNIEXPORT void JNICALL Java_com_steelsidekick_sguitar_Scale_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        delete reinterpret_cast<::djinni::CppProxyHandle<::Scale>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jobject JNICALL Java_com_steelsidekick_sguitar_Scale_createWithRootNote(JNIEnv* jniEnv, jobject /*this*/, jobject j_rootNote, jobject j_semitones)
{
    try {
        auto r = ::Scale::create_with_root_note(::djinni_generated::JNINoteValue::toCpp(jniEnv, j_rootNote),
                                                ::djinni::Array<::djinni::I32, ::djinni::JavaClassName<'I'>>::toCpp(jniEnv, j_semitones));
        return ::djinni::release(::djinni_generated::JNIScale::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT jobject JNICALL Java_com_steelsidekick_sguitar_Scale_00024CppProxy_native_1getNotes(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        const auto& ref = ::djinni::objectFromHandleAddress<::Scale>(nativeRef);
        auto r = ref->get_notes();
        return ::djinni::release(::djinni::Array<::djinni_generated::JNINoteValue, ::djinni::JavaClassName<'c','o','m','/','s','t','e','e','l','s','i','d','e','k','i','c','k','/','s','g','u','i','t','a','r','/','N','o','t','e','V','a','l','u','e'>>::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT jstring JNICALL Java_com_steelsidekick_sguitar_Scale_00024CppProxy_native_1testDescription(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        const auto& ref = ::djinni::objectFromHandleAddress<::Scale>(nativeRef);
        auto r = ref->test_description();
        return ::djinni::release(::djinni::String::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

} // namespace djinni_generated
