// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_dao.djinni

#pragma once

#include "djinni_support.hpp"
#include "guitar_string_adjustment_record.hpp"

namespace djinni_generated {

class JNIGuitarStringAdjustmentRecord final {
public:
    using CppType = ::GuitarStringAdjustmentRecord;
    using JniType = jobject;

    using Boxed = JNIGuitarStringAdjustmentRecord;

    ~JNIGuitarStringAdjustmentRecord();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    JNIGuitarStringAdjustmentRecord();
    friend ::djinni::JniClass<JNIGuitarStringAdjustmentRecord>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/steelsidekick/sguitar/GuitarStringAdjustmentRecord") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(Ljava/lang/Integer;III)V") };
    const jfieldID field_mId { ::djinni::jniGetFieldID(clazz.get(), "mId", "Ljava/lang/Integer;") };
    const jfieldID field_mGuitarAdjustmentId { ::djinni::jniGetFieldID(clazz.get(), "mGuitarAdjustmentId", "I") };
    const jfieldID field_mStringNumber { ::djinni::jniGetFieldID(clazz.get(), "mStringNumber", "I") };
    const jfieldID field_mStep { ::djinni::jniGetFieldID(clazz.get(), "mStep", "I") };
};

} // namespace djinni_generated
