// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_objects.djinni

#pragma once

#include "djinni_support.hpp"
#include "note.hpp"

namespace djinni_generated {

class JNINote final : ::djinni::JniInterface<::Note, JNINote> {
public:
    using CppType = std::shared_ptr<::Note>;
    using CppOptType = std::shared_ptr<::Note>;
    using JniType = jobject;

    using Boxed = JNINote;

    ~JNINote();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<JNINote>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<JNINote>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    JNINote();
    friend ::djinni::JniClass<JNINote>;
    friend ::djinni::JniInterface<::Note, JNINote>;

};

} // namespace djinni_generated
