// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_dao.djinni

#pragma once

#include "djinni_support.hpp"
#include "guitar_record.hpp"

namespace djinni_generated {

class JNIGuitarRecord final {
public:
    using CppType = ::GuitarRecord;
    using JniType = jobject;

    using Boxed = JNIGuitarRecord;

    ~JNIGuitarRecord();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    JNIGuitarRecord();
    friend ::djinni::JniClass<JNIGuitarRecord>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/steelsidekick/sguitar/GuitarRecord") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(Ljava/lang/Integer;Ljava/lang/String;I[II[Lcom/steelsidekick/sguitar/GuitarStringRecord;[Lcom/steelsidekick/sguitar/GuitarAdjustmentRecord;)V") };
    const jfieldID field_id { ::djinni::jniGetFieldID(clazz.get(), "id", "Ljava/lang/Integer;") };
    const jfieldID field_name { ::djinni::jniGetFieldID(clazz.get(), "name", "Ljava/lang/String;") };
    const jfieldID field_numberOfFrets { ::djinni::jniGetFieldID(clazz.get(), "numberOfFrets", "I") };
    const jfieldID field_fretMarkers { ::djinni::jniGetFieldID(clazz.get(), "fretMarkers", "[I") };
    const jfieldID field_type { ::djinni::jniGetFieldID(clazz.get(), "type", "I") };
    const jfieldID field_guitarStrings { ::djinni::jniGetFieldID(clazz.get(), "guitarStrings", "[Lcom/steelsidekick/sguitar/GuitarStringRecord;") };
    const jfieldID field_guitarAdjustments { ::djinni::jniGetFieldID(clazz.get(), "guitarAdjustments", "[Lcom/steelsidekick/sguitar/GuitarAdjustmentRecord;") };
};

} // namespace djinni_generated
