// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_objects.djinni

#pragma once

#include "djinni_support.hpp"
#include "harmonized_scale.hpp"

namespace djinni_generated {

class JNIHarmonizedScale final : ::djinni::JniInterface<::HarmonizedScale, JNIHarmonizedScale> {
public:
    using CppType = std::shared_ptr<::HarmonizedScale>;
    using CppOptType = std::shared_ptr<::HarmonizedScale>;
    using JniType = jobject;

    using Boxed = JNIHarmonizedScale;

    ~JNIHarmonizedScale();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<JNIHarmonizedScale>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<JNIHarmonizedScale>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    JNIHarmonizedScale();
    friend ::djinni::JniClass<JNIHarmonizedScale>;
    friend ::djinni::JniInterface<::HarmonizedScale, JNIHarmonizedScale>;

};

} // namespace djinni_generated
