// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_dao.djinni

#include "jni_scale_DAO.hpp"  // my header
#include "Marshal.hpp"
#include "jni_database_connection.hpp"
#include "jni_scale_record.hpp"

namespace djinni_generated {

JNIScaleDAO::JNIScaleDAO() : ::djinni::JniInterface<::ScaleDAO, JNIScaleDAO>("com/steelsidekick/sguitar/ScaleDAO$CppProxy") {}

JNIScaleDAO::~JNIScaleDAO() = default;


CJNIEXPORT void JNICALL Java_com_steelsidekick_sguitar_ScaleDAO_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        delete reinterpret_cast<::djinni::CppProxyHandle<::ScaleDAO>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jobject JNICALL Java_com_steelsidekick_sguitar_ScaleDAO_createScaleDao(JNIEnv* jniEnv, jobject /*this*/, jobject j_databaseConnection)
{
    try {
        auto r = ::ScaleDAO::create_scale_dao(::djinni_generated::JNIDatabaseConnection::toCpp(jniEnv, j_databaseConnection));
        return ::djinni::release(::djinni_generated::JNIScaleDAO::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT jobject JNICALL Java_com_steelsidekick_sguitar_ScaleDAO_00024CppProxy_native_1getScales(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        const auto& ref = ::djinni::objectFromHandleAddress<::ScaleDAO>(nativeRef);
        auto r = ref->get_scales();
        return ::djinni::release(::djinni::Array<::djinni_generated::JNIScaleRecord, ::djinni::JavaClassName<'c','o','m','/','s','t','e','e','l','s','i','d','e','k','i','c','k','/','s','g','u','i','t','a','r','/','S','c','a','l','e','R','e','c','o','r','d'>>::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT jobject JNICALL Java_com_steelsidekick_sguitar_ScaleDAO_00024CppProxy_native_1addScale(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jobject j_scale)
{
    try {
        const auto& ref = ::djinni::objectFromHandleAddress<::ScaleDAO>(nativeRef);
        auto r = ref->add_scale(::djinni_generated::JNIScaleRecord::toCpp(jniEnv, j_scale));
        return ::djinni::release(::djinni::Optional<std::optional, ::djinni::I32>::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT jboolean JNICALL Java_com_steelsidekick_sguitar_ScaleDAO_00024CppProxy_native_1updateScale(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jobject j_scale)
{
    try {
        const auto& ref = ::djinni::objectFromHandleAddress<::ScaleDAO>(nativeRef);
        auto r = ref->update_scale(::djinni_generated::JNIScaleRecord::toCpp(jniEnv, j_scale));
        return ::djinni::release(::djinni::Bool::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT jboolean JNICALL Java_com_steelsidekick_sguitar_ScaleDAO_00024CppProxy_native_1deleteScale(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jint j_id)
{
    try {
        const auto& ref = ::djinni::objectFromHandleAddress<::ScaleDAO>(nativeRef);
        auto r = ref->delete_scale(::djinni::I32::toCpp(jniEnv, j_id));
        return ::djinni::release(::djinni::Bool::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

} // namespace djinni_generated
