// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_dao.djinni

#include "jni_database_connection.hpp"  // my header
#include "Marshal.hpp"

namespace djinni_generated {

JNIDatabaseConnection::JNIDatabaseConnection() : ::djinni::JniInterface<::DatabaseConnection, JNIDatabaseConnection>("com/steelsidekick/sguitar/DatabaseConnection$CppProxy") {}

JNIDatabaseConnection::~JNIDatabaseConnection() = default;


CJNIEXPORT void JNICALL Java_com_steelsidekick_sguitar_DatabaseConnection_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        delete reinterpret_cast<::djinni::CppProxyHandle<::DatabaseConnection>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jobject JNICALL Java_com_steelsidekick_sguitar_DatabaseConnection_createDatabaseConnection(JNIEnv* jniEnv, jobject /*this*/, jstring j_path)
{
    try {
        auto r = ::DatabaseConnection::create_database_connection(::djinni::String::toCpp(jniEnv, j_path));
        return ::djinni::release(::djinni_generated::JNIDatabaseConnection::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

} // namespace djinni_generated
