// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_dao.djinni

#pragma once

#include "djinni_support.hpp"
#include "guitar_record.hpp"

namespace djinni_generated {

class JNIGuitarRecord final {
public:
    using CppType = ::GuitarRecord;
    using JniType = jobject;

    using Boxed = JNIGuitarRecord;

    ~JNIGuitarRecord();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    JNIGuitarRecord();
    friend ::djinni::JniClass<JNIGuitarRecord>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/steelsidekick/sguitar/GuitarRecord") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(Ljava/lang/Integer;Ljava/lang/String;I[II[Lcom/steelsidekick/sguitar/GuitarStringRecord;[Lcom/steelsidekick/sguitar/GuitarAdjustmentRecord;)V") };
    const jfieldID field_mId { ::djinni::jniGetFieldID(clazz.get(), "mId", "Ljava/lang/Integer;") };
    const jfieldID field_mName { ::djinni::jniGetFieldID(clazz.get(), "mName", "Ljava/lang/String;") };
    const jfieldID field_mNumberOfFrets { ::djinni::jniGetFieldID(clazz.get(), "mNumberOfFrets", "I") };
    const jfieldID field_mFretMarkers { ::djinni::jniGetFieldID(clazz.get(), "mFretMarkers", "[I") };
    const jfieldID field_mType { ::djinni::jniGetFieldID(clazz.get(), "mType", "I") };
    const jfieldID field_mGuitarStrings { ::djinni::jniGetFieldID(clazz.get(), "mGuitarStrings", "[Lcom/steelsidekick/sguitar/GuitarStringRecord;") };
    const jfieldID field_mGuitarAdjustments { ::djinni::jniGetFieldID(clazz.get(), "mGuitarAdjustments", "[Lcom/steelsidekick/sguitar/GuitarAdjustmentRecord;") };
};

} // namespace djinni_generated
