// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_dao.djinni

#pragma once

#include "djinni_support.hpp"
#include "guitar_string_adjustment_record.hpp"

namespace djinni_generated {

class JNIGuitarStringAdjustmentRecord final {
public:
    using CppType = ::GuitarStringAdjustmentRecord;
    using JniType = jobject;

    using Boxed = JNIGuitarStringAdjustmentRecord;

    ~JNIGuitarStringAdjustmentRecord();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    JNIGuitarStringAdjustmentRecord();
    friend ::djinni::JniClass<JNIGuitarStringAdjustmentRecord>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/steelsidekick/sguitar/GuitarStringAdjustmentRecord") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(Ljava/lang/Integer;III)V") };
    const jfieldID field_id { ::djinni::jniGetFieldID(clazz.get(), "id", "Ljava/lang/Integer;") };
    const jfieldID field_guitarAdjustmentId { ::djinni::jniGetFieldID(clazz.get(), "guitarAdjustmentId", "I") };
    const jfieldID field_stringNumber { ::djinni::jniGetFieldID(clazz.get(), "stringNumber", "I") };
    const jfieldID field_step { ::djinni::jniGetFieldID(clazz.get(), "step", "I") };
};

} // namespace djinni_generated
