// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_objects.djinni

#pragma once

#include "djinni_support.hpp"
#include "note.hpp"

namespace djinni_generated {

class Note final : ::djinni::JniInterface<::Note, Note> {
public:
    using CppType = std::shared_ptr<::Note>;
    using CppOptType = std::shared_ptr<::Note>;
    using JniType = jobject;

    using Boxed = Note;

    ~Note();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<Note>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<Note>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    Note();
    friend ::djinni::JniClass<Note>;
    friend ::djinni::JniInterface<::Note, Note>;

};

} // namespace djinni_generated
