// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_objects.djinni

#pragma once

#include "djinni_support.hpp"
#include "note_value.hpp"

namespace djinni_generated {

class NoteValue final : ::djinni::JniEnum {
public:
    using CppType = ::NoteValue;
    using JniType = jobject;

    using Boxed = NoteValue;

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return static_cast<CppType>(::djinni::JniClass<NoteValue>::get().ordinal(jniEnv, j)); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, CppType c) { return ::djinni::JniClass<NoteValue>::get().create(jniEnv, static_cast<jint>(c)); }

private:
    NoteValue() : JniEnum("com/steelsidekick/sguitar/NoteValue") {}
    friend ::djinni::JniClass<NoteValue>;
};

} // namespace djinni_generated
