// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_dao.djinni

#pragma once

#include "djinni_support.hpp"
#include "scale_record.hpp"

namespace djinni_generated {

class ScaleRecord final {
public:
    using CppType = ::ScaleRecord;
    using JniType = jobject;

    using Boxed = ScaleRecord;

    ~ScaleRecord();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    ScaleRecord();
    friend ::djinni::JniClass<ScaleRecord>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/steelsidekick/sguitar/ScaleRecord") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(ILjava/lang/String;[I)V") };
    const jfieldID field_id { ::djinni::jniGetFieldID(clazz.get(), "id", "I") };
    const jfieldID field_name { ::djinni::jniGetFieldID(clazz.get(), "name", "Ljava/lang/String;") };
    const jfieldID field_semitones { ::djinni::jniGetFieldID(clazz.get(), "semitones", "[I") };
};

} // namespace djinni_generated
