// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_dao.djinni

#pragma once

#include "SGDatabase_connection.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class SGDatabaseConnection final : ::djinni::JniInterface<::SGDatabaseConnection, SGDatabaseConnection> {
public:
    using CppType = std::shared_ptr<::SGDatabaseConnection>;
    using CppOptType = std::shared_ptr<::SGDatabaseConnection>;
    using JniType = jobject;

    using Boxed = SGDatabaseConnection;

    ~SGDatabaseConnection();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<SGDatabaseConnection>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<SGDatabaseConnection>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    SGDatabaseConnection();
    friend ::djinni::JniClass<SGDatabaseConnection>;
    friend ::djinni::JniInterface<::SGDatabaseConnection, SGDatabaseConnection>;

};

} // namespace djinni_generated
