// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_dao.djinni

#include "SGDatabase_connection.hpp"  // my header
#include "Marshal.hpp"

namespace djinni_generated {

SGDatabaseConnection::SGDatabaseConnection() : ::djinni::JniInterface<::SGDatabaseConnection, SGDatabaseConnection>("com/steelsidekick/sguitar/SGDatabaseConnection$CppProxy") {}

SGDatabaseConnection::~SGDatabaseConnection() = default;


CJNIEXPORT void JNICALL Java_com_steelsidekick_sguitar_SGDatabaseConnection_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        delete reinterpret_cast<::djinni::CppProxyHandle<::SGDatabaseConnection>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jobject JNICALL Java_com_steelsidekick_sguitar_SGDatabaseConnection_createSGDatabaseConnection(JNIEnv* jniEnv, jobject /*this*/, jstring j_path)
{
    try {
        auto r = ::SGDatabaseConnection::create_SGDatabase_connection(::djinni::String::toCpp(jniEnv, j_path));
        return ::djinni::release(::djinni_generated::SGDatabaseConnection::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

} // namespace djinni_generated
