// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_import.djinni

#pragma once

#include "SGuitar_import.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class SGuitarImport final : ::djinni::JniInterface<::SGuitarImport, SGuitarImport> {
public:
    using CppType = std::shared_ptr<::SGuitarImport>;
    using CppOptType = std::shared_ptr<::SGuitarImport>;
    using JniType = jobject;

    using Boxed = SGuitarImport;

    ~SGuitarImport();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<SGuitarImport>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<SGuitarImport>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    SGuitarImport();
    friend ::djinni::JniClass<SGuitarImport>;
    friend ::djinni::JniInterface<::SGuitarImport, SGuitarImport>;

};

} // namespace djinni_generated
