// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_factory.djinni

#include "SGuitar_factory.hpp"  // my header
#include "chord.hpp"
#include "chord_record.hpp"
#include "guitar.hpp"
#include "guitar_record.hpp"
#include "note_value.hpp"
#include "scale.hpp"
#include "scale_record.hpp"

namespace djinni_generated {

SGuitarFactory::SGuitarFactory() : ::djinni::JniInterface<::SGuitarFactory, SGuitarFactory>("com/steelsidekick/sguitar/SGuitarFactory$CppProxy") {}

SGuitarFactory::~SGuitarFactory() = default;


CJNIEXPORT void JNICALL Java_com_steelsidekick_sguitar_SGuitarFactory_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        delete reinterpret_cast<::djinni::CppProxyHandle<::SGuitarFactory>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jobject JNICALL Java_com_steelsidekick_sguitar_SGuitarFactory_createGuitar(JNIEnv* jniEnv, jobject /*this*/, jobject j_guitarRecord)
{
    try {
        auto r = ::SGuitarFactory::create_guitar(::djinni_generated::GuitarRecord::toCpp(jniEnv, j_guitarRecord));
        return ::djinni::release(::djinni_generated::Guitar::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT jobject JNICALL Java_com_steelsidekick_sguitar_SGuitarFactory_createScale(JNIEnv* jniEnv, jobject /*this*/, jobject j_rootNote, jobject j_scaleRecord)
{
    try {
        auto r = ::SGuitarFactory::create_scale(::djinni_generated::NoteValue::toCpp(jniEnv, j_rootNote),
                                                ::djinni_generated::ScaleRecord::toCpp(jniEnv, j_scaleRecord));
        return ::djinni::release(::djinni_generated::Scale::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT jobject JNICALL Java_com_steelsidekick_sguitar_SGuitarFactory_createChord(JNIEnv* jniEnv, jobject /*this*/, jobject j_rootNote, jobject j_chordRecord)
{
    try {
        auto r = ::SGuitarFactory::create_chord(::djinni_generated::NoteValue::toCpp(jniEnv, j_rootNote),
                                                ::djinni_generated::ChordRecord::toCpp(jniEnv, j_chordRecord));
        return ::djinni::release(::djinni_generated::Chord::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

} // namespace djinni_generated
