// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_dao.djinni

#pragma once

#include "SGuitar_database.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class SGuitarDatabase final : ::djinni::JniInterface<::SGuitarDatabase, SGuitarDatabase> {
public:
    using CppType = std::shared_ptr<::SGuitarDatabase>;
    using CppOptType = std::shared_ptr<::SGuitarDatabase>;
    using JniType = jobject;

    using Boxed = SGuitarDatabase;

    ~SGuitarDatabase();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<SGuitarDatabase>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<SGuitarDatabase>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    SGuitarDatabase();
    friend ::djinni::JniClass<SGuitarDatabase>;
    friend ::djinni::JniInterface<::SGuitarDatabase, SGuitarDatabase>;

};

} // namespace djinni_generated
