// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_import.djinni

#include "SGuitar_import.hpp"  // my header
#include "Marshal.hpp"
#include "guitar_DAO.hpp"
#include "guitar_record.hpp"

namespace djinni_generated {

SGuitarImport::SGuitarImport() : ::djinni::JniInterface<::SGuitarImport, SGuitarImport>("com/steelsidekick/sguitar/SGuitarImport$CppProxy") {}

SGuitarImport::~SGuitarImport() = default;


CJNIEXPORT void JNICALL Java_com_steelsidekick_sguitar_SGuitarImport_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        delete reinterpret_cast<::djinni::CppProxyHandle<::SGuitarImport>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jboolean JNICALL Java_com_steelsidekick_sguitar_SGuitarImport_importJsonGuitarFromPath(JNIEnv* jniEnv, jobject /*this*/, jstring j_fromPath, jobject j_toGuitarDAO)
{
    try {
        auto r = ::SGuitarImport::importJsonGuitarFromPath(::djinni::String::toCpp(jniEnv, j_fromPath),
                                                           ::djinni_generated::GuitarDAO::toCpp(jniEnv, j_toGuitarDAO));
        return ::djinni::release(::djinni::Bool::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT jobject JNICALL Java_com_steelsidekick_sguitar_SGuitarImport_convertJsonToGuitarRecord(JNIEnv* jniEnv, jobject /*this*/, jstring j_filename, jstring j_json)
{
    try {
        auto r = ::SGuitarImport::convertJsonToGuitarRecord(::djinni::String::toCpp(jniEnv, j_filename),
                                                            ::djinni::String::toCpp(jniEnv, j_json));
        return ::djinni::release(::djinni_generated::GuitarRecord::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

} // namespace djinni_generated
