// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar.djinni


export interface GuitarImport {
}
export interface GuitarImport_statics {
    importJsonGuitarFromPath(fromPath: string, toGuitarDAO: GuitarDAO): boolean;
    convertJsonToGuitarRecord(filename: string, json: string): GuitarRecord;
}

export interface GuitarFactory {
}
export interface GuitarFactory_statics {
    createGuitar(guitarRecord: GuitarRecord): Guitar;
    createScale(rootNote: NoteValue, scaleRecord: ScaleRecord): Scale;
    createChord(rootNote: NoteValue, chordRecord: ChordRecord): Chord;
}

export enum NoteValue {
    C = 0,
    C_SHARP = 1,
    D = 2,
    D_SHARP = 3,
    E = 4,
    F = 5,
    F_SHARP = 6,
    G = 7,
    G_SHARP = 8,
    A = 9,
    A_SHARP = 10,
    B = 11,
}

export enum AccidentalType {
    NATURAL = 0,
    SHARP = 1,
    FLAT = 2,
}

export interface Note {
    getMidiNote(): number;
    getNote(): NoteValue;
    getOctave(): number;
    testDescription(): string;
    noteNameSharp(): string;
    noteNameFlat(): string;
}
export interface Note_statics {
    createWithNote(note: NoteValue, octave: number): Note;
    createWithMidiNote(midiNote: number): Note;
    noteNameSharpForNote(note: NoteValue): string;
    noteNameFlatForNote(note: NoteValue): string;
    noteValueForNoteString(noteString: string): NoteValue;
}

export interface Scale {
    getNotes(): Array<NoteValue>;
    testDescription(): string;
}
export interface Scale_statics {
    createWithRootNote(rootNote: NoteValue, semitones: Int32Array): Scale;
}

export interface Chord {
    getNotes(): Array<NoteValue>;
    testDescription(): string;
}
export interface Chord_statics {
    createWithRootNote(rootNote: NoteValue, intervals: Int32Array): Chord;
    createWithNotes(notes: Array<NoteValue>): Chord;
}

export interface HarmonizedScale {
    getChords(): Array<Chord>;
    testDescription(): string;
}
export interface HarmonizedScale_statics {
    createHarmonizedScaleWithRootNote(rootNote: NoteValue, semitones: Int32Array): HarmonizedScale;
}

export interface GuitarString {
    getStartNote(): Note;
    getNotes(): Array<Note>;
    reset(): void;
    adjustStringBySteps(steps: number): void;
    testDescription(): string;
}
export interface GuitarString_statics {
    create(): GuitarString;
    createWithStartNote(startNote: Note, numberOfFrets: number): GuitarString;
}

export interface StringAdjustment {
    getStringNumber(): number;
    getStep(): number;
    testDescription(): string;
}
export interface StringAdjustment_statics {
    createWithStringNumber(stringNumber: number, step: number): StringAdjustment;
}

export interface GuitarAdjustment {
    getStringAdjustments(): Array<StringAdjustment>;
    getPosition(): number;
    getOrder(): number;
    setActivated(activated: boolean): void;
    isActivated(): boolean;
    testDescription(): string;
}
export interface GuitarAdjustment_statics {
    createWithStringAdjustments(stringAdjustments: Array<StringAdjustment>, position: number, order: number): GuitarAdjustment;
}

export interface Guitar {
    getNumberOfFrets(): number;
    getFretMarkers(): Int32Array;
    getStrings(): Array<GuitarString>;
    resetStrings(): void;
    getGuitarAdjustments(): Map<string, GuitarAdjustment>;
    setAdjustmentActivated(adjustmentId: string, activated: boolean): void;
    isAdjustmentActivated(adjustmentId: string): boolean;
    testDescription(): string;
}
export interface Guitar_statics {
    create(numberOfFrets: number, fretMarkers: Int32Array, guitarStrings: Array<GuitarString>, guitarAdjustments: Map<string, GuitarAdjustment>): Guitar;
}

export interface /*record*/ ScaleRecord {
    id?: number;
    name: string;
    semitones: Int32Array;
}

export interface /*record*/ ChordRecord {
    id?: number;
    name: string;
    intervals: Int32Array;
}

export interface /*record*/ GuitarStringRecord {
    id?: number;
    guitarId: number;
    stringNumber: number;
    startNote: string;
    octave: number;
}

export interface /*record*/ GuitarStringAdjustmentRecord {
    id?: number;
    guitarAdjustmentId: number;
    stringNumber: number;
    step: number;
}

export interface /*record*/ GuitarAdjustmentRecord {
    id?: number;
    guitarId: number;
    name: string;
    position: number;
    order: number;
    guitarStringAdjustments: Array<GuitarStringAdjustmentRecord>;
}

export enum GuitarAdjustmentPosition {
    TOP = 0,
    BOTTOM = 1,
}

export interface /*record*/ GuitarRecord {
    id?: number;
    name: string;
    numberOfFrets: number;
    fretMarkers: Int32Array;
    type: number;
    guitarStrings: Array<GuitarStringRecord>;
    guitarAdjustments: Array<GuitarAdjustmentRecord>;
}

export interface DatabaseConnection {
}
export interface DatabaseConnection_statics {
    createDatabaseConnection(path: string): DatabaseConnection;
}

export interface ScaleDAO {
    getScales(): Array<ScaleRecord>;
    addScale(scale: ScaleRecord): number | undefined;
    updateScale(scale: ScaleRecord): boolean;
    deleteScale(id: number): boolean;
}
export interface ScaleDAO_statics {
    createScaleDao(databaseConnection: DatabaseConnection): ScaleDAO;
}

export interface ChordDAO {
    getChords(): Array<ChordRecord>;
    addChord(chord: ChordRecord): number | undefined;
    updateChord(chord: ChordRecord): boolean;
    deleteChord(id: number): boolean;
}
export interface ChordDAO_statics {
    createChordDao(databaseConnection: DatabaseConnection): ChordDAO;
}

export interface GuitarDAO {
    getGuitars(): Array<GuitarRecord>;
    addGuitar(guitar: GuitarRecord): number | undefined;
    updateGuitar(guitar: GuitarRecord): boolean;
    deleteGuitar(id: number): boolean;
}
export interface GuitarDAO_statics {
    createGuitarDao(databaseConnection: DatabaseConnection): GuitarDAO;
}

export interface SGuitar_statics {
    GuitarImport: GuitarImport_statics;
    GuitarFactory: GuitarFactory_statics;
    Note: Note_statics;
    Scale: Scale_statics;
    Chord: Chord_statics;
    HarmonizedScale: HarmonizedScale_statics;
    GuitarString: GuitarString_statics;
    StringAdjustment: StringAdjustment_statics;
    GuitarAdjustment: GuitarAdjustment_statics;
    Guitar: Guitar_statics;
    DatabaseConnection: DatabaseConnection_statics;
    ScaleDAO: ScaleDAO_statics;
    ChordDAO: ChordDAO_statics;
    GuitarDAO: GuitarDAO_statics;
}
