// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_objects.djinni

#include "jni_harmonized_scale.hpp"  // my header
#include "jni_chord.hpp"
#include "jni_note_value.hpp"

namespace djinni_generated {

em::val JNIHarmonizedScale::cppProxyMethods() {
    static const em::val methods = em::val::array(std::vector<std::string> {
        "getChords",
        "testDescription",
    });
    return methods;
}

em::val JNIHarmonizedScale::create_harmonized_scale_with_root_note(int32_t w_root_note,const em::val& w_semitones) {
    try {
        auto r = ::HarmonizedScale::create_harmonized_scale_with_root_note(::djinni_generated::JNINoteValue::toCpp(w_root_note),
                                               ::djinni::Array<::djinni::I32>::toCpp(w_semitones));
        return ::djinni_generated::JNIHarmonizedScale::fromCpp(r);
    }
    catch(const std::exception& e) {
        return ::djinni::ExceptionHandlingTraits<::djinni_generated::JNIHarmonizedScale>::handleNativeException(e);
    }
}
em::val JNIHarmonizedScale::get_chords(const CppType& self) {
    try {
        auto r = self->get_chords();
        return ::djinni::Array<::djinni_generated::JNIChord>::fromCpp(r);
    }
    catch(const std::exception& e) {
        return ::djinni::ExceptionHandlingTraits<::djinni::Array<::djinni_generated::JNIChord>>::handleNativeException(e);
    }
}
std::string JNIHarmonizedScale::test_description(const CppType& self) {
    try {
        auto r = self->test_description();
        return ::djinni::String::fromCpp(r);
    }
    catch(const std::exception& e) {
        return ::djinni::ExceptionHandlingTraits<::djinni::String>::handleNativeException(e);
    }
}

EMSCRIPTEN_BINDINGS(_harmonized_scale) {
    em::class_<::HarmonizedScale>("HarmonizedScale")
        .smart_ptr<std::shared_ptr<::HarmonizedScale>>("HarmonizedScale")
        .function("nativeDestroy", &JNIHarmonizedScale::nativeDestroy)
        .class_function("createHarmonizedScaleWithRootNote", JNIHarmonizedScale::create_harmonized_scale_with_root_note)
        .function("getChords", JNIHarmonizedScale::get_chords)
        .function("testDescription", JNIHarmonizedScale::test_description)
        ;
}

} // namespace djinni_generated
