// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_objects.djinni

#pragma once

#include "djinni_wasm.hpp"
#include "string_adjustment.hpp"

namespace djinni_generated {

struct JNIStringAdjustment : ::djinni::JsInterface<::StringAdjustment, JNIStringAdjustment> {
    using CppType = std::shared_ptr<::StringAdjustment>;
    using CppOptType = std::shared_ptr<::StringAdjustment>;
    using JsType = em::val;
    using Boxed = JNIStringAdjustment;

    static CppType toCpp(JsType j) { return _fromJs(j); }
    static JsType fromCppOpt(const CppOptType& c) { return {_toJs(c)}; }
    static JsType fromCpp(const CppType& c) {
        ::djinni::checkForNull(c.get(), "JNIStringAdjustment::fromCpp");
        return fromCppOpt(c);
    }

    static em::val cppProxyMethods();

    static em::val create_with_string_number(int32_t w_string_number,int32_t w_step);
    static int32_t get_string_number(const CppType& self);
    static int32_t get_step(const CppType& self);
    static std::string test_description(const CppType& self);

};

} // namespace djinni_generated
