// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_dao.djinni

#pragma once

#include "djinni_wasm.hpp"
#include "guitar_DAO.hpp"

namespace djinni_generated {

struct JNIGuitarDAO : ::djinni::JsInterface<::GuitarDAO, JNIGuitarDAO> {
    using CppType = std::shared_ptr<::GuitarDAO>;
    using CppOptType = std::shared_ptr<::GuitarDAO>;
    using JsType = em::val;
    using Boxed = JNIGuitarDAO;

    static CppType toCpp(JsType j) { return _fromJs(j); }
    static JsType fromCppOpt(const CppOptType& c) { return {_toJs(c)}; }
    static JsType fromCpp(const CppType& c) {
        ::djinni::checkForNull(c.get(), "JNIGuitarDAO::fromCpp");
        return fromCppOpt(c);
    }

    static em::val cppProxyMethods();

    static em::val create_guitar_dao(const em::val& w_database_connection);
    static em::val get_guitars(const CppType& self);
    static em::val add_guitar(const CppType& self, const em::val& w_guitar);
    static bool update_guitar(const CppType& self, const em::val& w_guitar);
    static bool delete_guitar(const CppType& self, int32_t w_id);

};

} // namespace djinni_generated
