// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_dao.djinni

#include "jni_guitar_adjustment_record.hpp"  // my header
#include "jni_guitar_string_adjustment_record.hpp"

namespace djinni_generated {

auto JNIGuitarAdjustmentRecord::toCpp(const JsType& j) -> CppType {
    return {::djinni::Optional<std::optional, ::djinni::I32>::Boxed::toCpp(j["id"]),
            ::djinni::I32::Boxed::toCpp(j["guitarId"]),
            ::djinni::String::Boxed::toCpp(j["name"]),
            ::djinni::I32::Boxed::toCpp(j["position"]),
            ::djinni::I32::Boxed::toCpp(j["order"]),
            ::djinni::Array<::djinni_generated::JNIGuitarStringAdjustmentRecord>::Boxed::toCpp(j["guitarStringAdjustments"])};
}
auto JNIGuitarAdjustmentRecord::fromCpp(const CppType& c) -> JsType {
    em::val js = em::val::object();
    js.set("id", ::djinni::Optional<std::optional, ::djinni::I32>::Boxed::fromCpp(c.id));
    js.set("guitarId", ::djinni::I32::Boxed::fromCpp(c.guitar_id));
    js.set("name", ::djinni::String::Boxed::fromCpp(c.name));
    js.set("position", ::djinni::I32::Boxed::fromCpp(c.position));
    js.set("order", ::djinni::I32::Boxed::fromCpp(c.order));
    js.set("guitarStringAdjustments", ::djinni::Array<::djinni_generated::JNIGuitarStringAdjustmentRecord>::Boxed::fromCpp(c.guitar_string_adjustments));
    return js;
}

} // namespace djinni_generated
