// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_objects.djinni

#include "jni_scale.hpp"  // my header
#include "jni_note_value.hpp"

namespace djinni_generated {

em::val JNIScale::cppProxyMethods() {
    static const em::val methods = em::val::array(std::vector<std::string> {
        "getNotes",
        "testDescription",
    });
    return methods;
}

em::val JNIScale::create_with_root_note(int32_t w_root_note,const em::val& w_semitones) {
    try {
        auto r = ::Scale::create_with_root_note(::djinni_generated::JNINoteValue::toCpp(w_root_note),
                              ::djinni::Array<::djinni::I32>::toCpp(w_semitones));
        return ::djinni_generated::JNIScale::fromCpp(r);
    }
    catch(const std::exception& e) {
        return ::djinni::ExceptionHandlingTraits<::djinni_generated::JNIScale>::handleNativeException(e);
    }
}
em::val JNIScale::get_notes(const CppType& self) {
    try {
        auto r = self->get_notes();
        return ::djinni::Array<::djinni_generated::JNINoteValue>::fromCpp(r);
    }
    catch(const std::exception& e) {
        return ::djinni::ExceptionHandlingTraits<::djinni::Array<::djinni_generated::JNINoteValue>>::handleNativeException(e);
    }
}
std::string JNIScale::test_description(const CppType& self) {
    try {
        auto r = self->test_description();
        return ::djinni::String::fromCpp(r);
    }
    catch(const std::exception& e) {
        return ::djinni::ExceptionHandlingTraits<::djinni::String>::handleNativeException(e);
    }
}

EMSCRIPTEN_BINDINGS(_scale) {
    em::class_<::Scale>("Scale")
        .smart_ptr<std::shared_ptr<::Scale>>("Scale")
        .function("nativeDestroy", &JNIScale::nativeDestroy)
        .class_function("createWithRootNote", JNIScale::create_with_root_note)
        .function("getNotes", JNIScale::get_notes)
        .function("testDescription", JNIScale::test_description)
        ;
}

} // namespace djinni_generated
