// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_objects.djinni

#pragma once

#include "chord.hpp"
#include "djinni_wasm.hpp"

namespace djinni_generated {

struct JNIChord : ::djinni::JsInterface<::Chord, JNIChord> {
    using CppType = std::shared_ptr<::Chord>;
    using CppOptType = std::shared_ptr<::Chord>;
    using JsType = em::val;
    using Boxed = JNIChord;

    static CppType toCpp(JsType j) { return _fromJs(j); }
    static JsType fromCppOpt(const CppOptType& c) { return {_toJs(c)}; }
    static JsType fromCpp(const CppType& c) {
        ::djinni::checkForNull(c.get(), "JNIChord::fromCpp");
        return fromCppOpt(c);
    }

    static em::val cppProxyMethods();

    static em::val create_with_root_note(int32_t w_root_note,const em::val& w_intervals);
    static em::val create_with_notes(const em::val& w_notes);
    static em::val get_notes(const CppType& self);
    static std::string test_description(const CppType& self);

};

} // namespace djinni_generated
