// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_dao.djinni

#include "jni_chord_DAO.hpp"  // my header
#include "jni_chord_record.hpp"
#include "jni_database_connection.hpp"

namespace djinni_generated {

em::val JNIChordDAO::cppProxyMethods() {
    static const em::val methods = em::val::array(std::vector<std::string> {
        "getChords",
        "addChord",
        "updateChord",
        "deleteChord",
    });
    return methods;
}

em::val JNIChordDAO::create_chord_dao(const em::val& w_database_connection) {
    try {
        auto r = ::ChordDAO::create_chord_dao(::djinni_generated::JNIDatabaseConnection::toCpp(w_database_connection));
        return ::djinni_generated::JNIChordDAO::fromCpp(r);
    }
    catch(const std::exception& e) {
        return ::djinni::ExceptionHandlingTraits<::djinni_generated::JNIChordDAO>::handleNativeException(e);
    }
}
em::val JNIChordDAO::get_chords(const CppType& self) {
    try {
        auto r = self->get_chords();
        return ::djinni::Array<::djinni_generated::JNIChordRecord>::fromCpp(r);
    }
    catch(const std::exception& e) {
        return ::djinni::ExceptionHandlingTraits<::djinni::Array<::djinni_generated::JNIChordRecord>>::handleNativeException(e);
    }
}
em::val JNIChordDAO::add_chord(const CppType& self, const em::val& w_chord) {
    try {
        auto r = self->add_chord(::djinni_generated::JNIChordRecord::toCpp(w_chord));
        return ::djinni::Optional<std::optional, ::djinni::I32>::fromCpp(r);
    }
    catch(const std::exception& e) {
        return ::djinni::ExceptionHandlingTraits<::djinni::Optional<std::optional, ::djinni::I32>>::handleNativeException(e);
    }
}
bool JNIChordDAO::update_chord(const CppType& self, const em::val& w_chord) {
    try {
        auto r = self->update_chord(::djinni_generated::JNIChordRecord::toCpp(w_chord));
        return ::djinni::Bool::fromCpp(r);
    }
    catch(const std::exception& e) {
        return ::djinni::ExceptionHandlingTraits<::djinni::Bool>::handleNativeException(e);
    }
}
bool JNIChordDAO::delete_chord(const CppType& self, int32_t w_id) {
    try {
        auto r = self->delete_chord(::djinni::I32::toCpp(w_id));
        return ::djinni::Bool::fromCpp(r);
    }
    catch(const std::exception& e) {
        return ::djinni::ExceptionHandlingTraits<::djinni::Bool>::handleNativeException(e);
    }
}

EMSCRIPTEN_BINDINGS(_chord_DAO) {
    em::class_<::ChordDAO>("ChordDAO")
        .smart_ptr<std::shared_ptr<::ChordDAO>>("ChordDAO")
        .function("nativeDestroy", &JNIChordDAO::nativeDestroy)
        .class_function("createChordDao", JNIChordDAO::create_chord_dao)
        .function("getChords", JNIChordDAO::get_chords)
        .function("addChord", JNIChordDAO::add_chord)
        .function("updateChord", JNIChordDAO::update_chord)
        .function("deleteChord", JNIChordDAO::delete_chord)
        ;
}

} // namespace djinni_generated
