// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_objects.djinni

#include "jni_guitar_string.hpp"  // my header
#include "jni_note.hpp"

namespace djinni_generated {

em::val JNIGuitarString::cppProxyMethods() {
    static const em::val methods = em::val::array(std::vector<std::string> {
        "getStartNote",
        "getNotes",
        "reset",
        "adjustStringBySteps",
        "testDescription",
    });
    return methods;
}

em::val JNIGuitarString::create() {
    try {
        auto r = ::GuitarString::create();
        return ::djinni_generated::JNIGuitarString::fromCpp(r);
    }
    catch(const std::exception& e) {
        return ::djinni::ExceptionHandlingTraits<::djinni_generated::JNIGuitarString>::handleNativeException(e);
    }
}
em::val JNIGuitarString::create_with_start_note(const em::val& w_start_note,int32_t w_number_of_frets) {
    try {
        auto r = ::GuitarString::create_with_start_note(::djinni_generated::JNINote::toCpp(w_start_note),
                               ::djinni::I32::toCpp(w_number_of_frets));
        return ::djinni_generated::JNIGuitarString::fromCpp(r);
    }
    catch(const std::exception& e) {
        return ::djinni::ExceptionHandlingTraits<::djinni_generated::JNIGuitarString>::handleNativeException(e);
    }
}
em::val JNIGuitarString::get_start_note(const CppType& self) {
    try {
        auto r = self->get_start_note();
        return ::djinni_generated::JNINote::fromCpp(r);
    }
    catch(const std::exception& e) {
        return ::djinni::ExceptionHandlingTraits<::djinni_generated::JNINote>::handleNativeException(e);
    }
}
em::val JNIGuitarString::get_notes(const CppType& self) {
    try {
        auto r = self->get_notes();
        return ::djinni::Array<::djinni_generated::JNINote>::fromCpp(r);
    }
    catch(const std::exception& e) {
        return ::djinni::ExceptionHandlingTraits<::djinni::Array<::djinni_generated::JNINote>>::handleNativeException(e);
    }
}
void JNIGuitarString::reset(const CppType& self) {
    try {
        self->reset();
    }
    catch(const std::exception& e) {
        return ::djinni::ExceptionHandlingTraits<void>::handleNativeException(e);
    }
}
void JNIGuitarString::adjust_string_by_steps(const CppType& self, int32_t w_steps) {
    try {
        self->adjust_string_by_steps(::djinni::I32::toCpp(w_steps));
    }
    catch(const std::exception& e) {
        return ::djinni::ExceptionHandlingTraits<void>::handleNativeException(e);
    }
}
std::string JNIGuitarString::test_description(const CppType& self) {
    try {
        auto r = self->test_description();
        return ::djinni::String::fromCpp(r);
    }
    catch(const std::exception& e) {
        return ::djinni::ExceptionHandlingTraits<::djinni::String>::handleNativeException(e);
    }
}

EMSCRIPTEN_BINDINGS(_guitar_string) {
    em::class_<::GuitarString>("GuitarString")
        .smart_ptr<std::shared_ptr<::GuitarString>>("GuitarString")
        .function("nativeDestroy", &JNIGuitarString::nativeDestroy)
        .class_function("create", JNIGuitarString::create)
        .class_function("createWithStartNote", JNIGuitarString::create_with_start_note)
        .function("getStartNote", JNIGuitarString::get_start_note)
        .function("getNotes", JNIGuitarString::get_notes)
        .function("reset", JNIGuitarString::reset)
        .function("adjustStringBySteps", JNIGuitarString::adjust_string_by_steps)
        .function("testDescription", JNIGuitarString::test_description)
        ;
}

} // namespace djinni_generated
