// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_dao.djinni

#pragma once

#include "chord_DAO.hpp"
#include "djinni_wasm.hpp"

namespace djinni_generated {

struct JNIChordDAO : ::djinni::JsInterface<::ChordDAO, JNIChordDAO> {
    using CppType = std::shared_ptr<::ChordDAO>;
    using CppOptType = std::shared_ptr<::ChordDAO>;
    using JsType = em::val;
    using Boxed = JNIChordDAO;

    static CppType toCpp(JsType j) { return _fromJs(j); }
    static JsType fromCppOpt(const CppOptType& c) { return {_toJs(c)}; }
    static JsType fromCpp(const CppType& c) {
        ::djinni::checkForNull(c.get(), "JNIChordDAO::fromCpp");
        return fromCppOpt(c);
    }

    static em::val cppProxyMethods();

    static em::val create_chord_dao(const em::val& w_database_connection);
    static em::val get_chords(const CppType& self);
    static em::val add_chord(const CppType& self, const em::val& w_chord);
    static bool update_chord(const CppType& self, const em::val& w_chord);
    static bool delete_chord(const CppType& self, int32_t w_id);

};

} // namespace djinni_generated
