// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_dao.djinni

#pragma once

#include "djinni_wasm.hpp"
#include "guitar_adjustment_position.hpp"

namespace djinni_generated {

struct JNIGuitarAdjustmentPosition: ::djinni::WasmEnum<::GuitarAdjustmentPosition> {
    static void staticInitializeConstants();
};

} // namespace djinni_generated
