// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_factory.djinni

#include "jni_guitar_factory.hpp"  // my header
#include "jni_chord.hpp"
#include "jni_chord_record.hpp"
#include "jni_guitar.hpp"
#include "jni_guitar_record.hpp"
#include "jni_note_value.hpp"
#include "jni_scale.hpp"
#include "jni_scale_record.hpp"

namespace djinni_generated {

em::val JNIGuitarFactory::cppProxyMethods() {
    static const em::val methods = em::val::array(std::vector<std::string> {
    });
    return methods;
}

em::val JNIGuitarFactory::create_guitar(const em::val& w_guitar_record) {
    try {
        auto r = ::GuitarFactory::create_guitar(::djinni_generated::JNIGuitarRecord::toCpp(w_guitar_record));
        return ::djinni_generated::JNIGuitar::fromCpp(r);
    }
    catch(const std::exception& e) {
        return ::djinni::ExceptionHandlingTraits<::djinni_generated::JNIGuitar>::handleNativeException(e);
    }
}
em::val JNIGuitarFactory::create_scale(int32_t w_root_note,const em::val& w_scale_record) {
    try {
        auto r = ::GuitarFactory::create_scale(::djinni_generated::JNINoteValue::toCpp(w_root_note),
                     ::djinni_generated::JNIScaleRecord::toCpp(w_scale_record));
        return ::djinni_generated::JNIScale::fromCpp(r);
    }
    catch(const std::exception& e) {
        return ::djinni::ExceptionHandlingTraits<::djinni_generated::JNIScale>::handleNativeException(e);
    }
}
em::val JNIGuitarFactory::create_chord(int32_t w_root_note,const em::val& w_chord_record) {
    try {
        auto r = ::GuitarFactory::create_chord(::djinni_generated::JNINoteValue::toCpp(w_root_note),
                     ::djinni_generated::JNIChordRecord::toCpp(w_chord_record));
        return ::djinni_generated::JNIChord::fromCpp(r);
    }
    catch(const std::exception& e) {
        return ::djinni::ExceptionHandlingTraits<::djinni_generated::JNIChord>::handleNativeException(e);
    }
}

EMSCRIPTEN_BINDINGS(_guitar_factory) {
    em::class_<::GuitarFactory>("GuitarFactory")
        .smart_ptr<std::shared_ptr<::GuitarFactory>>("GuitarFactory")
        .function("nativeDestroy", &JNIGuitarFactory::nativeDestroy)
        .class_function("createGuitar", JNIGuitarFactory::create_guitar)
        .class_function("createScale", JNIGuitarFactory::create_scale)
        .class_function("createChord", JNIGuitarFactory::create_chord)
        ;
}

} // namespace djinni_generated
