// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_dao.djinni

#include "jni_guitar_string_adjustment_record.hpp"  // my header

namespace djinni_generated {

auto JNIGuitarStringAdjustmentRecord::toCpp(const JsType& j) -> CppType {
    return {::djinni::Optional<std::optional, ::djinni::I32>::Boxed::toCpp(j["id"]),
            ::djinni::I32::Boxed::toCpp(j["guitarAdjustmentId"]),
            ::djinni::I32::Boxed::toCpp(j["stringNumber"]),
            ::djinni::I32::Boxed::toCpp(j["step"])};
}
auto JNIGuitarStringAdjustmentRecord::fromCpp(const CppType& c) -> JsType {
    em::val js = em::val::object();
    js.set("id", ::djinni::Optional<std::optional, ::djinni::I32>::Boxed::fromCpp(c.id));
    js.set("guitarAdjustmentId", ::djinni::I32::Boxed::fromCpp(c.guitar_adjustment_id));
    js.set("stringNumber", ::djinni::I32::Boxed::fromCpp(c.string_number));
    js.set("step", ::djinni::I32::Boxed::fromCpp(c.step));
    return js;
}

} // namespace djinni_generated
