// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_objects.djinni

#include "jni_note_value.hpp"  // my header
#include <mutex>

namespace djinni_generated {

namespace {
    EM_JS(void, djinni_init__note_value_consts, (), {
        Module.NoteValue =  {
            C : 0,
            C_SHARP : 1,
            D : 2,
            D_SHARP : 3,
            E : 4,
            F : 5,
            F_SHARP : 6,
            G : 7,
            G_SHARP : 8,
            A : 9,
            A_SHARP : 10,
            B : 11,
        }
    })
}

void JNINoteValue::staticInitializeConstants() {
    static std::once_flag initOnce;
    std::call_once(initOnce, [] {
        djinni_init__note_value_consts();
    });
}

EMSCRIPTEN_BINDINGS(_note_value) {
    JNINoteValue::staticInitializeConstants();
}

} // namespace djinni_generated
