// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_objects.djinni

#pragma once

#include "accidental_type.hpp"
#include "djinni_wasm.hpp"

namespace djinni_generated {

struct JNIAccidentalType: ::djinni::WasmEnum<::AccidentalType> {
    static void staticInitializeConstants();
};

} // namespace djinni_generated
