// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_objects.djinni

#pragma once

#include "djinni_wasm.hpp"
#include "note_value.hpp"

namespace djinni_generated {

struct JNINoteValue: ::djinni::WasmEnum<::NoteValue> {
    static void staticInitializeConstants();
};

} // namespace djinni_generated
