// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_objects.djinni

#include "jni_guitar_adjustment.hpp"  // my header
#include "jni_string_adjustment.hpp"

namespace djinni_generated {

em::val JNIGuitarAdjustment::cppProxyMethods() {
    static const em::val methods = em::val::array(std::vector<std::string> {
        "getStringAdjustments",
        "getPosition",
        "getOrder",
        "setActivated",
        "isActivated",
        "testDescription",
    });
    return methods;
}

em::val JNIGuitarAdjustment::create_with_string_adjustments(const em::val& w_string_adjustments,int32_t w_position,int32_t w_order) {
    try {
        auto r = ::GuitarAdjustment::create_with_string_adjustments(::djinni::Array<::djinni_generated::JNIStringAdjustment>::toCpp(w_string_adjustments),
                                       ::djinni::I32::toCpp(w_position),
                                       ::djinni::I32::toCpp(w_order));
        return ::djinni_generated::JNIGuitarAdjustment::fromCpp(r);
    }
    catch(const std::exception& e) {
        return ::djinni::ExceptionHandlingTraits<::djinni_generated::JNIGuitarAdjustment>::handleNativeException(e);
    }
}
em::val JNIGuitarAdjustment::get_string_adjustments(const CppType& self) {
    try {
        auto r = self->get_string_adjustments();
        return ::djinni::Array<::djinni_generated::JNIStringAdjustment>::fromCpp(r);
    }
    catch(const std::exception& e) {
        return ::djinni::ExceptionHandlingTraits<::djinni::Array<::djinni_generated::JNIStringAdjustment>>::handleNativeException(e);
    }
}
int32_t JNIGuitarAdjustment::get_position(const CppType& self) {
    try {
        auto r = self->get_position();
        return ::djinni::I32::fromCpp(r);
    }
    catch(const std::exception& e) {
        return ::djinni::ExceptionHandlingTraits<::djinni::I32>::handleNativeException(e);
    }
}
int32_t JNIGuitarAdjustment::get_order(const CppType& self) {
    try {
        auto r = self->get_order();
        return ::djinni::I32::fromCpp(r);
    }
    catch(const std::exception& e) {
        return ::djinni::ExceptionHandlingTraits<::djinni::I32>::handleNativeException(e);
    }
}
void JNIGuitarAdjustment::set_activated(const CppType& self, bool w_activated) {
    try {
        self->set_activated(::djinni::Bool::toCpp(w_activated));
    }
    catch(const std::exception& e) {
        return ::djinni::ExceptionHandlingTraits<void>::handleNativeException(e);
    }
}
bool JNIGuitarAdjustment::is_activated(const CppType& self) {
    try {
        auto r = self->is_activated();
        return ::djinni::Bool::fromCpp(r);
    }
    catch(const std::exception& e) {
        return ::djinni::ExceptionHandlingTraits<::djinni::Bool>::handleNativeException(e);
    }
}
std::string JNIGuitarAdjustment::test_description(const CppType& self) {
    try {
        auto r = self->test_description();
        return ::djinni::String::fromCpp(r);
    }
    catch(const std::exception& e) {
        return ::djinni::ExceptionHandlingTraits<::djinni::String>::handleNativeException(e);
    }
}

EMSCRIPTEN_BINDINGS(_guitar_adjustment) {
    em::class_<::GuitarAdjustment>("GuitarAdjustment")
        .smart_ptr<std::shared_ptr<::GuitarAdjustment>>("GuitarAdjustment")
        .function("nativeDestroy", &JNIGuitarAdjustment::nativeDestroy)
        .class_function("createWithStringAdjustments", JNIGuitarAdjustment::create_with_string_adjustments)
        .function("getStringAdjustments", JNIGuitarAdjustment::get_string_adjustments)
        .function("getPosition", JNIGuitarAdjustment::get_position)
        .function("getOrder", JNIGuitarAdjustment::get_order)
        .function("setActivated", JNIGuitarAdjustment::set_activated)
        .function("isActivated", JNIGuitarAdjustment::is_activated)
        .function("testDescription", JNIGuitarAdjustment::test_description)
        ;
}

} // namespace djinni_generated
