// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_dao.djinni

#pragma once

#include "chord_record.hpp"
#include "djinni_wasm.hpp"

namespace djinni_generated {

struct JNIChordRecord
{
    using CppType = ::ChordRecord;
    using JsType = em::val;
    using Boxed = JNIChordRecord;

    static CppType toCpp(const JsType& j);
    static JsType fromCpp(const CppType& c);
};

} // namespace djinni_generated
