// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_objects.djinni

#include "jni_note.hpp"  // my header
#include "jni_note_value.hpp"

namespace djinni_generated {

em::val JNINote::cppProxyMethods() {
    static const em::val methods = em::val::array(std::vector<std::string> {
        "getMidiNote",
        "getNote",
        "getOctave",
        "testDescription",
        "noteNameSharp",
        "noteNameFlat",
    });
    return methods;
}

em::val JNINote::create_with_note(int32_t w_note,int32_t w_octave) {
    try {
        auto r = ::Note::create_with_note(::djinni_generated::JNINoteValue::toCpp(w_note),
                         ::djinni::I32::toCpp(w_octave));
        return ::djinni_generated::JNINote::fromCpp(r);
    }
    catch(const std::exception& e) {
        return ::djinni::ExceptionHandlingTraits<::djinni_generated::JNINote>::handleNativeException(e);
    }
}
em::val JNINote::create_with_midi_note(int32_t w_midi_note) {
    try {
        auto r = ::Note::create_with_midi_note(::djinni::I32::toCpp(w_midi_note));
        return ::djinni_generated::JNINote::fromCpp(r);
    }
    catch(const std::exception& e) {
        return ::djinni::ExceptionHandlingTraits<::djinni_generated::JNINote>::handleNativeException(e);
    }
}
int32_t JNINote::get_midi_note(const CppType& self) {
    try {
        auto r = self->get_midi_note();
        return ::djinni::I32::fromCpp(r);
    }
    catch(const std::exception& e) {
        return ::djinni::ExceptionHandlingTraits<::djinni::I32>::handleNativeException(e);
    }
}
int32_t JNINote::get_note(const CppType& self) {
    try {
        auto r = self->get_note();
        return ::djinni_generated::JNINoteValue::fromCpp(r);
    }
    catch(const std::exception& e) {
        return ::djinni::ExceptionHandlingTraits<::djinni_generated::JNINoteValue>::handleNativeException(e);
    }
}
int32_t JNINote::get_octave(const CppType& self) {
    try {
        auto r = self->get_octave();
        return ::djinni::I32::fromCpp(r);
    }
    catch(const std::exception& e) {
        return ::djinni::ExceptionHandlingTraits<::djinni::I32>::handleNativeException(e);
    }
}
std::string JNINote::test_description(const CppType& self) {
    try {
        auto r = self->test_description();
        return ::djinni::String::fromCpp(r);
    }
    catch(const std::exception& e) {
        return ::djinni::ExceptionHandlingTraits<::djinni::String>::handleNativeException(e);
    }
}
std::string JNINote::note_name_sharp(const CppType& self) {
    try {
        auto r = self->note_name_sharp();
        return ::djinni::String::fromCpp(r);
    }
    catch(const std::exception& e) {
        return ::djinni::ExceptionHandlingTraits<::djinni::String>::handleNativeException(e);
    }
}
std::string JNINote::note_name_flat(const CppType& self) {
    try {
        auto r = self->note_name_flat();
        return ::djinni::String::fromCpp(r);
    }
    catch(const std::exception& e) {
        return ::djinni::ExceptionHandlingTraits<::djinni::String>::handleNativeException(e);
    }
}
std::string JNINote::note_name_sharp_for_note(int32_t w_note) {
    try {
        auto r = ::Note::note_name_sharp_for_note(::djinni_generated::JNINoteValue::toCpp(w_note));
        return ::djinni::String::fromCpp(r);
    }
    catch(const std::exception& e) {
        return ::djinni::ExceptionHandlingTraits<::djinni::String>::handleNativeException(e);
    }
}
std::string JNINote::note_name_flat_for_note(int32_t w_note) {
    try {
        auto r = ::Note::note_name_flat_for_note(::djinni_generated::JNINoteValue::toCpp(w_note));
        return ::djinni::String::fromCpp(r);
    }
    catch(const std::exception& e) {
        return ::djinni::ExceptionHandlingTraits<::djinni::String>::handleNativeException(e);
    }
}
int32_t JNINote::note_value_for_note_string(const std::string& w_note_string) {
    try {
        auto r = ::Note::note_value_for_note_string(::djinni::String::toCpp(w_note_string));
        return ::djinni_generated::JNINoteValue::fromCpp(r);
    }
    catch(const std::exception& e) {
        return ::djinni::ExceptionHandlingTraits<::djinni_generated::JNINoteValue>::handleNativeException(e);
    }
}

EMSCRIPTEN_BINDINGS(_note) {
    em::class_<::Note>("Note")
        .smart_ptr<std::shared_ptr<::Note>>("Note")
        .function("nativeDestroy", &JNINote::nativeDestroy)
        .class_function("createWithNote", JNINote::create_with_note)
        .class_function("createWithMidiNote", JNINote::create_with_midi_note)
        .function("getMidiNote", JNINote::get_midi_note)
        .function("getNote", JNINote::get_note)
        .function("getOctave", JNINote::get_octave)
        .function("testDescription", JNINote::test_description)
        .function("noteNameSharp", JNINote::note_name_sharp)
        .function("noteNameFlat", JNINote::note_name_flat)
        .class_function("noteNameSharpForNote", JNINote::note_name_sharp_for_note)
        .class_function("noteNameFlatForNote", JNINote::note_name_flat_for_note)
        .class_function("noteValueForNoteString", JNINote::note_value_for_note_string)
        ;
}

} // namespace djinni_generated
