// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_objects.djinni

#pragma once

#include "djinni_wasm.hpp"
#include "note.hpp"

namespace djinni_generated {

struct JNINote : ::djinni::JsInterface<::Note, JNINote> {
    using CppType = std::shared_ptr<::Note>;
    using CppOptType = std::shared_ptr<::Note>;
    using JsType = em::val;
    using Boxed = JNINote;

    static CppType toCpp(JsType j) { return _fromJs(j); }
    static JsType fromCppOpt(const CppOptType& c) { return {_toJs(c)}; }
    static JsType fromCpp(const CppType& c) {
        ::djinni::checkForNull(c.get(), "JNINote::fromCpp");
        return fromCppOpt(c);
    }

    static em::val cppProxyMethods();

    static em::val create_with_note(int32_t w_note,int32_t w_octave);
    static em::val create_with_midi_note(int32_t w_midi_note);
    static int32_t get_midi_note(const CppType& self);
    static int32_t get_note(const CppType& self);
    static int32_t get_octave(const CppType& self);
    static std::string test_description(const CppType& self);
    static std::string note_name_sharp(const CppType& self);
    static std::string note_name_flat(const CppType& self);
    static std::string note_name_sharp_for_note(int32_t w_note);
    static std::string note_name_flat_for_note(int32_t w_note);
    static int32_t note_value_for_note_string(const std::string& w_note_string);

};

} // namespace djinni_generated
