// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_dao.djinni

#include "jni_scale_DAO.hpp"  // my header
#include "jni_database_connection.hpp"
#include "jni_scale_record.hpp"

namespace djinni_generated {

em::val JNIScaleDAO::cppProxyMethods() {
    static const em::val methods = em::val::array(std::vector<std::string> {
        "getScales",
        "addScale",
        "updateScale",
        "deleteScale",
    });
    return methods;
}

em::val JNIScaleDAO::create_scale_dao(const em::val& w_database_connection) {
    try {
        auto r = ::ScaleDAO::create_scale_dao(::djinni_generated::JNIDatabaseConnection::toCpp(w_database_connection));
        return ::djinni_generated::JNIScaleDAO::fromCpp(r);
    }
    catch(const std::exception& e) {
        return ::djinni::ExceptionHandlingTraits<::djinni_generated::JNIScaleDAO>::handleNativeException(e);
    }
}
em::val JNIScaleDAO::get_scales(const CppType& self) {
    try {
        auto r = self->get_scales();
        return ::djinni::Array<::djinni_generated::JNIScaleRecord>::fromCpp(r);
    }
    catch(const std::exception& e) {
        return ::djinni::ExceptionHandlingTraits<::djinni::Array<::djinni_generated::JNIScaleRecord>>::handleNativeException(e);
    }
}
em::val JNIScaleDAO::add_scale(const CppType& self, const em::val& w_scale) {
    try {
        auto r = self->add_scale(::djinni_generated::JNIScaleRecord::toCpp(w_scale));
        return ::djinni::Optional<std::optional, ::djinni::I32>::fromCpp(r);
    }
    catch(const std::exception& e) {
        return ::djinni::ExceptionHandlingTraits<::djinni::Optional<std::optional, ::djinni::I32>>::handleNativeException(e);
    }
}
bool JNIScaleDAO::update_scale(const CppType& self, const em::val& w_scale) {
    try {
        auto r = self->update_scale(::djinni_generated::JNIScaleRecord::toCpp(w_scale));
        return ::djinni::Bool::fromCpp(r);
    }
    catch(const std::exception& e) {
        return ::djinni::ExceptionHandlingTraits<::djinni::Bool>::handleNativeException(e);
    }
}
bool JNIScaleDAO::delete_scale(const CppType& self, int32_t w_id) {
    try {
        auto r = self->delete_scale(::djinni::I32::toCpp(w_id));
        return ::djinni::Bool::fromCpp(r);
    }
    catch(const std::exception& e) {
        return ::djinni::ExceptionHandlingTraits<::djinni::Bool>::handleNativeException(e);
    }
}

EMSCRIPTEN_BINDINGS(_scale_DAO) {
    em::class_<::ScaleDAO>("ScaleDAO")
        .smart_ptr<std::shared_ptr<::ScaleDAO>>("ScaleDAO")
        .function("nativeDestroy", &JNIScaleDAO::nativeDestroy)
        .class_function("createScaleDao", JNIScaleDAO::create_scale_dao)
        .function("getScales", JNIScaleDAO::get_scales)
        .function("addScale", JNIScaleDAO::add_scale)
        .function("updateScale", JNIScaleDAO::update_scale)
        .function("deleteScale", JNIScaleDAO::delete_scale)
        ;
}

} // namespace djinni_generated
