// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_objects.djinni

#pragma once

#include "djinni_wasm.hpp"
#include "guitar_adjustment.hpp"

namespace djinni_generated {

struct JNIGuitarAdjustment : ::djinni::JsInterface<::GuitarAdjustment, JNIGuitarAdjustment> {
    using CppType = std::shared_ptr<::GuitarAdjustment>;
    using CppOptType = std::shared_ptr<::GuitarAdjustment>;
    using JsType = em::val;
    using Boxed = JNIGuitarAdjustment;

    static CppType toCpp(JsType j) { return _fromJs(j); }
    static JsType fromCppOpt(const CppOptType& c) { return {_toJs(c)}; }
    static JsType fromCpp(const CppType& c) {
        ::djinni::checkForNull(c.get(), "JNIGuitarAdjustment::fromCpp");
        return fromCppOpt(c);
    }

    static em::val cppProxyMethods();

    static em::val create_with_string_adjustments(const em::val& w_string_adjustments,int32_t w_position,int32_t w_order);
    static em::val get_string_adjustments(const CppType& self);
    static int32_t get_position(const CppType& self);
    static int32_t get_order(const CppType& self);
    static void set_activated(const CppType& self, bool w_activated);
    static bool is_activated(const CppType& self);
    static std::string test_description(const CppType& self);

};

} // namespace djinni_generated
