// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_import.djinni

#include "jni_guitar_import.hpp"  // my header
#include "jni_guitar_DAO.hpp"
#include "jni_guitar_record.hpp"

namespace djinni_generated {

em::val JNIGuitarImport::cppProxyMethods() {
    static const em::val methods = em::val::array(std::vector<std::string> {
    });
    return methods;
}

bool JNIGuitarImport::importJsonGuitarFromPath(const std::string& w_fromPath,const em::val& w_toGuitarDAO) {
    try {
        auto r = ::GuitarImport::importJsonGuitarFromPath(::djinni::String::toCpp(w_fromPath),
                                 ::djinni_generated::JNIGuitarDAO::toCpp(w_toGuitarDAO));
        return ::djinni::Bool::fromCpp(r);
    }
    catch(const std::exception& e) {
        return ::djinni::ExceptionHandlingTraits<::djinni::Bool>::handleNativeException(e);
    }
}
em::val JNIGuitarImport::convertJsonToGuitarRecord(const std::string& w_filename,const std::string& w_json) {
    try {
        auto r = ::GuitarImport::convertJsonToGuitarRecord(::djinni::String::toCpp(w_filename),
                                  ::djinni::String::toCpp(w_json));
        return ::djinni_generated::JNIGuitarRecord::fromCpp(r);
    }
    catch(const std::exception& e) {
        return ::djinni::ExceptionHandlingTraits<::djinni_generated::JNIGuitarRecord>::handleNativeException(e);
    }
}

EMSCRIPTEN_BINDINGS(_guitar_import) {
    em::class_<::GuitarImport>("GuitarImport")
        .smart_ptr<std::shared_ptr<::GuitarImport>>("GuitarImport")
        .function("nativeDestroy", &JNIGuitarImport::nativeDestroy)
        .class_function("importJsonGuitarFromPath", JNIGuitarImport::importJsonGuitarFromPath)
        .class_function("convertJsonToGuitarRecord", JNIGuitarImport::convertJsonToGuitarRecord)
        ;
}

} // namespace djinni_generated
