// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_objects.djinni

#pragma once

#include "djinni_wasm.hpp"
#include "harmonized_scale.hpp"

namespace djinni_generated {

struct JNIHarmonizedScale : ::djinni::JsInterface<::HarmonizedScale, JNIHarmonizedScale> {
    using CppType = std::shared_ptr<::HarmonizedScale>;
    using CppOptType = std::shared_ptr<::HarmonizedScale>;
    using JsType = em::val;
    using Boxed = JNIHarmonizedScale;

    static CppType toCpp(JsType j) { return _fromJs(j); }
    static JsType fromCppOpt(const CppOptType& c) { return {_toJs(c)}; }
    static JsType fromCpp(const CppType& c) {
        ::djinni::checkForNull(c.get(), "JNIHarmonizedScale::fromCpp");
        return fromCppOpt(c);
    }

    static em::val cppProxyMethods();

    static em::val create_harmonized_scale_with_root_note(int32_t w_root_note,const em::val& w_semitones);
    static em::val get_chords(const CppType& self);
    static std::string test_description(const CppType& self);

};

} // namespace djinni_generated
