// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_import.djinni

#pragma once

#include "djinni_wasm.hpp"
#include "guitar_import.hpp"

namespace djinni_generated {

struct JNIGuitarImport : ::djinni::JsInterface<::GuitarImport, JNIGuitarImport> {
    using CppType = std::shared_ptr<::GuitarImport>;
    using CppOptType = std::shared_ptr<::GuitarImport>;
    using JsType = em::val;
    using Boxed = JNIGuitarImport;

    static CppType toCpp(JsType j) { return _fromJs(j); }
    static JsType fromCppOpt(const CppOptType& c) { return {_toJs(c)}; }
    static JsType fromCpp(const CppType& c) {
        ::djinni::checkForNull(c.get(), "JNIGuitarImport::fromCpp");
        return fromCppOpt(c);
    }

    static em::val cppProxyMethods();

    static bool importJsonGuitarFromPath(const std::string& w_fromPath,const em::val& w_toGuitarDAO);
    static em::val convertJsonToGuitarRecord(const std::string& w_filename,const std::string& w_json);

};

} // namespace djinni_generated
