// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_dao.djinni

#include "jni_scale_record.hpp"  // my header

namespace djinni_generated {

auto JNIScaleRecord::toCpp(const JsType& j) -> CppType {
    return {::djinni::Optional<std::optional, ::djinni::I32>::Boxed::toCpp(j["id"]),
            ::djinni::String::Boxed::toCpp(j["name"]),
            ::djinni::Array<::djinni::I32>::Boxed::toCpp(j["semitones"])};
}
auto JNIScaleRecord::fromCpp(const CppType& c) -> JsType {
    em::val js = em::val::object();
    js.set("id", ::djinni::Optional<std::optional, ::djinni::I32>::Boxed::fromCpp(c.id));
    js.set("name", ::djinni::String::Boxed::fromCpp(c.name));
    js.set("semitones", ::djinni::Array<::djinni::I32>::Boxed::fromCpp(c.semitones));
    return js;
}

} // namespace djinni_generated
