// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_objects.djinni

#include "jni_accidental_type.hpp"  // my header
#include <mutex>

namespace djinni_generated {

namespace {
    EM_JS(void, djinni_init__accidental_type_consts, (), {
        Module.AccidentalType =  {
            NATURAL : 0,
            SHARP : 1,
            FLAT : 2,
        }
    })
}

void JNIAccidentalType::staticInitializeConstants() {
    static std::once_flag initOnce;
    std::call_once(initOnce, [] {
        djinni_init__accidental_type_consts();
    });
}

EMSCRIPTEN_BINDINGS(_accidental_type) {
    JNIAccidentalType::staticInitializeConstants();
}

} // namespace djinni_generated
