// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_dao.djinni

#include "jni_guitar_record.hpp"  // my header
#include "jni_guitar_adjustment_record.hpp"
#include "jni_guitar_string_record.hpp"

namespace djinni_generated {

auto JNIGuitarRecord::toCpp(const JsType& j) -> CppType {
    return {::djinni::Optional<std::optional, ::djinni::I32>::Boxed::toCpp(j["id"]),
            ::djinni::String::Boxed::toCpp(j["name"]),
            ::djinni::I32::Boxed::toCpp(j["numberOfFrets"]),
            ::djinni::Array<::djinni::I32>::Boxed::toCpp(j["fretMarkers"]),
            ::djinni::I32::Boxed::toCpp(j["type"]),
            ::djinni::Array<::djinni_generated::JNIGuitarStringRecord>::Boxed::toCpp(j["guitarStrings"]),
            ::djinni::Array<::djinni_generated::JNIGuitarAdjustmentRecord>::Boxed::toCpp(j["guitarAdjustments"])};
}
auto JNIGuitarRecord::fromCpp(const CppType& c) -> JsType {
    em::val js = em::val::object();
    js.set("id", ::djinni::Optional<std::optional, ::djinni::I32>::Boxed::fromCpp(c.id));
    js.set("name", ::djinni::String::Boxed::fromCpp(c.name));
    js.set("numberOfFrets", ::djinni::I32::Boxed::fromCpp(c.number_of_frets));
    js.set("fretMarkers", ::djinni::Array<::djinni::I32>::Boxed::fromCpp(c.fret_markers));
    js.set("type", ::djinni::I32::Boxed::fromCpp(c.type));
    js.set("guitarStrings", ::djinni::Array<::djinni_generated::JNIGuitarStringRecord>::Boxed::fromCpp(c.guitar_strings));
    js.set("guitarAdjustments", ::djinni::Array<::djinni_generated::JNIGuitarAdjustmentRecord>::Boxed::fromCpp(c.guitar_adjustments));
    return js;
}

} // namespace djinni_generated
