// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_objects.djinni

#include "jni_chord.hpp"  // my header
#include "jni_note_value.hpp"

namespace djinni_generated {

em::val JNIChord::cppProxyMethods() {
    static const em::val methods = em::val::array(std::vector<std::string> {
        "getNotes",
        "testDescription",
    });
    return methods;
}

em::val JNIChord::create_with_root_note(int32_t w_root_note,const em::val& w_intervals) {
    try {
        auto r = ::Chord::create_with_root_note(::djinni_generated::JNINoteValue::toCpp(w_root_note),
                              ::djinni::Array<::djinni::I32>::toCpp(w_intervals));
        return ::djinni_generated::JNIChord::fromCpp(r);
    }
    catch(const std::exception& e) {
        return ::djinni::ExceptionHandlingTraits<::djinni_generated::JNIChord>::handleNativeException(e);
    }
}
em::val JNIChord::create_with_notes(const em::val& w_notes) {
    try {
        auto r = ::Chord::create_with_notes(::djinni::Array<::djinni_generated::JNINoteValue>::toCpp(w_notes));
        return ::djinni_generated::JNIChord::fromCpp(r);
    }
    catch(const std::exception& e) {
        return ::djinni::ExceptionHandlingTraits<::djinni_generated::JNIChord>::handleNativeException(e);
    }
}
em::val JNIChord::get_notes(const CppType& self) {
    try {
        auto r = self->get_notes();
        return ::djinni::Array<::djinni_generated::JNINoteValue>::fromCpp(r);
    }
    catch(const std::exception& e) {
        return ::djinni::ExceptionHandlingTraits<::djinni::Array<::djinni_generated::JNINoteValue>>::handleNativeException(e);
    }
}
std::string JNIChord::test_description(const CppType& self) {
    try {
        auto r = self->test_description();
        return ::djinni::String::fromCpp(r);
    }
    catch(const std::exception& e) {
        return ::djinni::ExceptionHandlingTraits<::djinni::String>::handleNativeException(e);
    }
}

EMSCRIPTEN_BINDINGS(_chord) {
    em::class_<::Chord>("Chord")
        .smart_ptr<std::shared_ptr<::Chord>>("Chord")
        .function("nativeDestroy", &JNIChord::nativeDestroy)
        .class_function("createWithRootNote", JNIChord::create_with_root_note)
        .class_function("createWithNotes", JNIChord::create_with_notes)
        .function("getNotes", JNIChord::get_notes)
        .function("testDescription", JNIChord::test_description)
        ;
}

} // namespace djinni_generated
