// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_objects.djinni

#include "jni_string_adjustment.hpp"  // my header

namespace djinni_generated {

em::val JNIStringAdjustment::cppProxyMethods() {
    static const em::val methods = em::val::array(std::vector<std::string> {
        "getStringNumber",
        "getStep",
        "testDescription",
    });
    return methods;
}

em::val JNIStringAdjustment::create_with_string_number(int32_t w_string_number,int32_t w_step) {
    try {
        auto r = ::StringAdjustment::create_with_string_number(::djinni::I32::toCpp(w_string_number),
                                  ::djinni::I32::toCpp(w_step));
        return ::djinni_generated::JNIStringAdjustment::fromCpp(r);
    }
    catch(const std::exception& e) {
        return ::djinni::ExceptionHandlingTraits<::djinni_generated::JNIStringAdjustment>::handleNativeException(e);
    }
}
int32_t JNIStringAdjustment::get_string_number(const CppType& self) {
    try {
        auto r = self->get_string_number();
        return ::djinni::I32::fromCpp(r);
    }
    catch(const std::exception& e) {
        return ::djinni::ExceptionHandlingTraits<::djinni::I32>::handleNativeException(e);
    }
}
int32_t JNIStringAdjustment::get_step(const CppType& self) {
    try {
        auto r = self->get_step();
        return ::djinni::I32::fromCpp(r);
    }
    catch(const std::exception& e) {
        return ::djinni::ExceptionHandlingTraits<::djinni::I32>::handleNativeException(e);
    }
}
std::string JNIStringAdjustment::test_description(const CppType& self) {
    try {
        auto r = self->test_description();
        return ::djinni::String::fromCpp(r);
    }
    catch(const std::exception& e) {
        return ::djinni::ExceptionHandlingTraits<::djinni::String>::handleNativeException(e);
    }
}

EMSCRIPTEN_BINDINGS(_string_adjustment) {
    em::class_<::StringAdjustment>("StringAdjustment")
        .smart_ptr<std::shared_ptr<::StringAdjustment>>("StringAdjustment")
        .function("nativeDestroy", &JNIStringAdjustment::nativeDestroy)
        .class_function("createWithStringNumber", JNIStringAdjustment::create_with_string_number)
        .function("getStringNumber", JNIStringAdjustment::get_string_number)
        .function("getStep", JNIStringAdjustment::get_step)
        .function("testDescription", JNIStringAdjustment::test_description)
        ;
}

} // namespace djinni_generated
