// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_dao.djinni

#pragma once

#include "djinni_wasm.hpp"
#include "scale_DAO.hpp"

namespace djinni_generated {

struct JNIScaleDAO : ::djinni::JsInterface<::ScaleDAO, JNIScaleDAO> {
    using CppType = std::shared_ptr<::ScaleDAO>;
    using CppOptType = std::shared_ptr<::ScaleDAO>;
    using JsType = em::val;
    using Boxed = JNIScaleDAO;

    static CppType toCpp(JsType j) { return _fromJs(j); }
    static JsType fromCppOpt(const CppOptType& c) { return {_toJs(c)}; }
    static JsType fromCpp(const CppType& c) {
        ::djinni::checkForNull(c.get(), "JNIScaleDAO::fromCpp");
        return fromCppOpt(c);
    }

    static em::val cppProxyMethods();

    static em::val create_scale_dao(const em::val& w_database_connection);
    static em::val get_scales(const CppType& self);
    static em::val add_scale(const CppType& self, const em::val& w_scale);
    static bool update_scale(const CppType& self, const em::val& w_scale);
    static bool delete_scale(const CppType& self, int32_t w_id);

};

} // namespace djinni_generated
