// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_dao.djinni

#include "jni_guitar_DAO.hpp"  // my header
#include "jni_database_connection.hpp"
#include "jni_guitar_record.hpp"

namespace djinni_generated {

em::val JNIGuitarDAO::cppProxyMethods() {
    static const em::val methods = em::val::array(std::vector<std::string> {
        "getGuitars",
        "addGuitar",
        "updateGuitar",
        "deleteGuitar",
    });
    return methods;
}

em::val JNIGuitarDAO::create_guitar_dao(const em::val& w_database_connection) {
    try {
        auto r = ::GuitarDAO::create_guitar_dao(::djinni_generated::JNIDatabaseConnection::toCpp(w_database_connection));
        return ::djinni_generated::JNIGuitarDAO::fromCpp(r);
    }
    catch(const std::exception& e) {
        return ::djinni::ExceptionHandlingTraits<::djinni_generated::JNIGuitarDAO>::handleNativeException(e);
    }
}
em::val JNIGuitarDAO::get_guitars(const CppType& self) {
    try {
        auto r = self->get_guitars();
        return ::djinni::Array<::djinni_generated::JNIGuitarRecord>::fromCpp(r);
    }
    catch(const std::exception& e) {
        return ::djinni::ExceptionHandlingTraits<::djinni::Array<::djinni_generated::JNIGuitarRecord>>::handleNativeException(e);
    }
}
em::val JNIGuitarDAO::add_guitar(const CppType& self, const em::val& w_guitar) {
    try {
        auto r = self->add_guitar(::djinni_generated::JNIGuitarRecord::toCpp(w_guitar));
        return ::djinni::Optional<std::optional, ::djinni::I32>::fromCpp(r);
    }
    catch(const std::exception& e) {
        return ::djinni::ExceptionHandlingTraits<::djinni::Optional<std::optional, ::djinni::I32>>::handleNativeException(e);
    }
}
bool JNIGuitarDAO::update_guitar(const CppType& self, const em::val& w_guitar) {
    try {
        auto r = self->update_guitar(::djinni_generated::JNIGuitarRecord::toCpp(w_guitar));
        return ::djinni::Bool::fromCpp(r);
    }
    catch(const std::exception& e) {
        return ::djinni::ExceptionHandlingTraits<::djinni::Bool>::handleNativeException(e);
    }
}
bool JNIGuitarDAO::delete_guitar(const CppType& self, int32_t w_id) {
    try {
        auto r = self->delete_guitar(::djinni::I32::toCpp(w_id));
        return ::djinni::Bool::fromCpp(r);
    }
    catch(const std::exception& e) {
        return ::djinni::ExceptionHandlingTraits<::djinni::Bool>::handleNativeException(e);
    }
}

EMSCRIPTEN_BINDINGS(_guitar_DAO) {
    em::class_<::GuitarDAO>("GuitarDAO")
        .smart_ptr<std::shared_ptr<::GuitarDAO>>("GuitarDAO")
        .function("nativeDestroy", &JNIGuitarDAO::nativeDestroy)
        .class_function("createGuitarDao", JNIGuitarDAO::create_guitar_dao)
        .function("getGuitars", JNIGuitarDAO::get_guitars)
        .function("addGuitar", JNIGuitarDAO::add_guitar)
        .function("updateGuitar", JNIGuitarDAO::update_guitar)
        .function("deleteGuitar", JNIGuitarDAO::delete_guitar)
        ;
}

} // namespace djinni_generated
