// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_dao.djinni

#pragma once

#include "djinni_wasm.hpp"
#include "scale_record.hpp"

namespace djinni_generated {

struct JNIScaleRecord
{
    using CppType = ::ScaleRecord;
    using JsType = em::val;
    using Boxed = JNIScaleRecord;

    static CppType toCpp(const JsType& j);
    static JsType fromCpp(const CppType& c);
};

} // namespace djinni_generated
