// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_dao.djinni

#pragma once

#include "djinni_wasm.hpp"
#include "guitar_adjustment_record.hpp"

namespace djinni_generated {

struct JNIGuitarAdjustmentRecord
{
    using CppType = ::GuitarAdjustmentRecord;
    using JsType = em::val;
    using Boxed = JNIGuitarAdjustmentRecord;

    static CppType toCpp(const JsType& j);
    static JsType fromCpp(const CppType& c);
};

} // namespace djinni_generated
