// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_dao.djinni

#pragma once

#include "database_connection.hpp"
#include "djinni_wasm.hpp"

namespace djinni_generated {

struct JNIDatabaseConnection : ::djinni::JsInterface<::DatabaseConnection, JNIDatabaseConnection> {
    using CppType = std::shared_ptr<::DatabaseConnection>;
    using CppOptType = std::shared_ptr<::DatabaseConnection>;
    using JsType = em::val;
    using Boxed = JNIDatabaseConnection;

    static CppType toCpp(JsType j) { return _fromJs(j); }
    static JsType fromCppOpt(const CppOptType& c) { return {_toJs(c)}; }
    static JsType fromCpp(const CppType& c) {
        ::djinni::checkForNull(c.get(), "JNIDatabaseConnection::fromCpp");
        return fromCppOpt(c);
    }

    static em::val cppProxyMethods();

    static em::val create_database_connection(const std::string& w_path);

};

} // namespace djinni_generated
