// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_objects.djinni

#include "jni_guitar.hpp"  // my header
#include "jni_guitar_adjustment.hpp"
#include "jni_guitar_string.hpp"

namespace djinni_generated {

em::val JNIGuitar::cppProxyMethods() {
    static const em::val methods = em::val::array(std::vector<std::string> {
        "getNumberOfFrets",
        "getFretMarkers",
        "getStrings",
        "resetStrings",
        "getGuitarAdjustments",
        "setAdjustmentActivated",
        "isAdjustmentActivated",
        "testDescription",
    });
    return methods;
}

em::val JNIGuitar::create(int32_t w_number_of_frets,const em::val& w_fret_markers,const em::val& w_guitar_strings,const em::val& w_guitar_adjustments) {
    try {
        auto r = ::Guitar::create(::djinni::I32::toCpp(w_number_of_frets),
               ::djinni::Array<::djinni::I32>::toCpp(w_fret_markers),
               ::djinni::Array<::djinni_generated::JNIGuitarString>::toCpp(w_guitar_strings),
               ::djinni::Map<::djinni::String, ::djinni_generated::JNIGuitarAdjustment>::toCpp(w_guitar_adjustments));
        return ::djinni_generated::JNIGuitar::fromCpp(r);
    }
    catch(const std::exception& e) {
        return ::djinni::ExceptionHandlingTraits<::djinni_generated::JNIGuitar>::handleNativeException(e);
    }
}
int32_t JNIGuitar::get_number_of_frets(const CppType& self) {
    try {
        auto r = self->get_number_of_frets();
        return ::djinni::I32::fromCpp(r);
    }
    catch(const std::exception& e) {
        return ::djinni::ExceptionHandlingTraits<::djinni::I32>::handleNativeException(e);
    }
}
em::val JNIGuitar::get_fret_markers(const CppType& self) {
    try {
        auto r = self->get_fret_markers();
        return ::djinni::Array<::djinni::I32>::fromCpp(r);
    }
    catch(const std::exception& e) {
        return ::djinni::ExceptionHandlingTraits<::djinni::Array<::djinni::I32>>::handleNativeException(e);
    }
}
em::val JNIGuitar::get_strings(const CppType& self) {
    try {
        auto r = self->get_strings();
        return ::djinni::Array<::djinni_generated::JNIGuitarString>::fromCpp(r);
    }
    catch(const std::exception& e) {
        return ::djinni::ExceptionHandlingTraits<::djinni::Array<::djinni_generated::JNIGuitarString>>::handleNativeException(e);
    }
}
void JNIGuitar::reset_strings(const CppType& self) {
    try {
        self->reset_strings();
    }
    catch(const std::exception& e) {
        return ::djinni::ExceptionHandlingTraits<void>::handleNativeException(e);
    }
}
em::val JNIGuitar::get_guitar_adjustments(const CppType& self) {
    try {
        auto r = self->get_guitar_adjustments();
        return ::djinni::Map<::djinni::String, ::djinni_generated::JNIGuitarAdjustment>::fromCpp(r);
    }
    catch(const std::exception& e) {
        return ::djinni::ExceptionHandlingTraits<::djinni::Map<::djinni::String, ::djinni_generated::JNIGuitarAdjustment>>::handleNativeException(e);
    }
}
void JNIGuitar::set_adjustment_activated(const CppType& self, const std::string& w_adjustment_id,bool w_activated) {
    try {
        self->set_adjustment_activated(::djinni::String::toCpp(w_adjustment_id),
                                 ::djinni::Bool::toCpp(w_activated));
    }
    catch(const std::exception& e) {
        return ::djinni::ExceptionHandlingTraits<void>::handleNativeException(e);
    }
}
bool JNIGuitar::is_adjustment_activated(const CppType& self, const std::string& w_adjustment_id) {
    try {
        auto r = self->is_adjustment_activated(::djinni::String::toCpp(w_adjustment_id));
        return ::djinni::Bool::fromCpp(r);
    }
    catch(const std::exception& e) {
        return ::djinni::ExceptionHandlingTraits<::djinni::Bool>::handleNativeException(e);
    }
}
std::string JNIGuitar::test_description(const CppType& self) {
    try {
        auto r = self->test_description();
        return ::djinni::String::fromCpp(r);
    }
    catch(const std::exception& e) {
        return ::djinni::ExceptionHandlingTraits<::djinni::String>::handleNativeException(e);
    }
}

EMSCRIPTEN_BINDINGS(_guitar) {
    em::class_<::Guitar>("Guitar")
        .smart_ptr<std::shared_ptr<::Guitar>>("Guitar")
        .function("nativeDestroy", &JNIGuitar::nativeDestroy)
        .class_function("create", JNIGuitar::create)
        .function("getNumberOfFrets", JNIGuitar::get_number_of_frets)
        .function("getFretMarkers", JNIGuitar::get_fret_markers)
        .function("getStrings", JNIGuitar::get_strings)
        .function("resetStrings", JNIGuitar::reset_strings)
        .function("getGuitarAdjustments", JNIGuitar::get_guitar_adjustments)
        .function("setAdjustmentActivated", JNIGuitar::set_adjustment_activated)
        .function("isAdjustmentActivated", JNIGuitar::is_adjustment_activated)
        .function("testDescription", JNIGuitar::test_description)
        ;
}

} // namespace djinni_generated
