// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_dao.djinni

#include "jni_guitar_adjustment_position.hpp"  // my header
#include <mutex>

namespace djinni_generated {

namespace {
    EM_JS(void, djinni_init__guitar_adjustment_position_consts, (), {
        Module.GuitarAdjustmentPosition =  {
            TOP : 0,
            BOTTOM : 1,
        }
    })
}

void JNIGuitarAdjustmentPosition::staticInitializeConstants() {
    static std::once_flag initOnce;
    std::call_once(initOnce, [] {
        djinni_init__guitar_adjustment_position_consts();
    });
}

EMSCRIPTEN_BINDINGS(_guitar_adjustment_position) {
    JNIGuitarAdjustmentPosition::staticInitializeConstants();
}

} // namespace djinni_generated
