// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_objects.djinni

#pragma once

#include "djinni_wasm.hpp"
#include "guitar_string.hpp"

namespace djinni_generated {

struct JNIGuitarString : ::djinni::JsInterface<::GuitarString, JNIGuitarString> {
    using CppType = std::shared_ptr<::GuitarString>;
    using CppOptType = std::shared_ptr<::GuitarString>;
    using JsType = em::val;
    using Boxed = JNIGuitarString;

    static CppType toCpp(JsType j) { return _fromJs(j); }
    static JsType fromCppOpt(const CppOptType& c) { return {_toJs(c)}; }
    static JsType fromCpp(const CppType& c) {
        ::djinni::checkForNull(c.get(), "JNIGuitarString::fromCpp");
        return fromCppOpt(c);
    }

    static em::val cppProxyMethods();

    static em::val create();
    static em::val create_with_start_note(const em::val& w_start_note,int32_t w_number_of_frets);
    static em::val get_start_note(const CppType& self);
    static em::val get_notes(const CppType& self);
    static void reset(const CppType& self);
    static void adjust_string_by_steps(const CppType& self, int32_t w_steps);
    static std::string test_description(const CppType& self);

};

} // namespace djinni_generated
