// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_dao.djinni

#include "jni_database_connection.hpp"  // my header

namespace djinni_generated {

em::val JNIDatabaseConnection::cppProxyMethods() {
    static const em::val methods = em::val::array(std::vector<std::string> {
    });
    return methods;
}

em::val JNIDatabaseConnection::create_database_connection(const std::string& w_path) {
    try {
        auto r = ::DatabaseConnection::create_database_connection(::djinni::String::toCpp(w_path));
        return ::djinni_generated::JNIDatabaseConnection::fromCpp(r);
    }
    catch(const std::exception& e) {
        return ::djinni::ExceptionHandlingTraits<::djinni_generated::JNIDatabaseConnection>::handleNativeException(e);
    }
}

EMSCRIPTEN_BINDINGS(_database_connection) {
    em::class_<::DatabaseConnection>("DatabaseConnection")
        .smart_ptr<std::shared_ptr<::DatabaseConnection>>("DatabaseConnection")
        .function("nativeDestroy", &JNIDatabaseConnection::nativeDestroy)
        .class_function("createDatabaseConnection", JNIDatabaseConnection::create_database_connection)
        ;
}

} // namespace djinni_generated
