// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_objects.djinni

#pragma once

#include "djinni_wasm.hpp"
#include "guitar.hpp"

namespace djinni_generated {

struct JNIGuitar : ::djinni::JsInterface<::Guitar, JNIGuitar> {
    using CppType = std::shared_ptr<::Guitar>;
    using CppOptType = std::shared_ptr<::Guitar>;
    using JsType = em::val;
    using Boxed = JNIGuitar;

    static CppType toCpp(JsType j) { return _fromJs(j); }
    static JsType fromCppOpt(const CppOptType& c) { return {_toJs(c)}; }
    static JsType fromCpp(const CppType& c) {
        ::djinni::checkForNull(c.get(), "JNIGuitar::fromCpp");
        return fromCppOpt(c);
    }

    static em::val cppProxyMethods();

    static em::val create(int32_t w_number_of_frets,const em::val& w_fret_markers,const em::val& w_guitar_strings,const em::val& w_guitar_adjustments);
    static int32_t get_number_of_frets(const CppType& self);
    static em::val get_fret_markers(const CppType& self);
    static em::val get_strings(const CppType& self);
    static void reset_strings(const CppType& self);
    static em::val get_guitar_adjustments(const CppType& self);
    static void set_adjustment_activated(const CppType& self, const std::string& w_adjustment_id,bool w_activated);
    static bool is_adjustment_activated(const CppType& self, const std::string& w_adjustment_id);
    static std::string test_description(const CppType& self);

};

} // namespace djinni_generated
