// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_factory.djinni

#pragma once

#include "djinni_wasm.hpp"
#include "guitar_factory.hpp"

namespace djinni_generated {

struct JNIGuitarFactory : ::djinni::JsInterface<::GuitarFactory, JNIGuitarFactory> {
    using CppType = std::shared_ptr<::GuitarFactory>;
    using CppOptType = std::shared_ptr<::GuitarFactory>;
    using JsType = em::val;
    using Boxed = JNIGuitarFactory;

    static CppType toCpp(JsType j) { return _fromJs(j); }
    static JsType fromCppOpt(const CppOptType& c) { return {_toJs(c)}; }
    static JsType fromCpp(const CppType& c) {
        ::djinni::checkForNull(c.get(), "JNIGuitarFactory::fromCpp");
        return fromCppOpt(c);
    }

    static em::val cppProxyMethods();

    static em::val create_guitar(const em::val& w_guitar_record);
    static em::val create_scale(int32_t w_root_note,const em::val& w_scale_record);
    static em::val create_chord(int32_t w_root_note,const em::val& w_chord_record);

};

} // namespace djinni_generated
