// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_dao.djinni

#pragma once

#include "djinni_wasm.hpp"
#include "guitar_string_record.hpp"

namespace djinni_generated {

struct JNIGuitarStringRecord
{
    using CppType = ::GuitarStringRecord;
    using JsType = em::val;
    using Boxed = JNIGuitarStringRecord;

    static CppType toCpp(const JsType& j);
    static JsType fromCpp(const CppType& c);
};

} // namespace djinni_generated
