// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_dao.djinni

#include "jni_guitar_string_record.hpp"  // my header

namespace djinni_generated {

auto JNIGuitarStringRecord::toCpp(const JsType& j) -> CppType {
    return {::djinni::Optional<std::optional, ::djinni::I32>::Boxed::toCpp(j["id"]),
            ::djinni::I32::Boxed::toCpp(j["guitarId"]),
            ::djinni::I32::Boxed::toCpp(j["stringNumber"]),
            ::djinni::String::Boxed::toCpp(j["startNote"]),
            ::djinni::I32::Boxed::toCpp(j["octave"])};
}
auto JNIGuitarStringRecord::fromCpp(const CppType& c) -> JsType {
    em::val js = em::val::object();
    js.set("id", ::djinni::Optional<std::optional, ::djinni::I32>::Boxed::fromCpp(c.id));
    js.set("guitarId", ::djinni::I32::Boxed::fromCpp(c.guitar_id));
    js.set("stringNumber", ::djinni::I32::Boxed::fromCpp(c.string_number));
    js.set("startNote", ::djinni::String::Boxed::fromCpp(c.start_note));
    js.set("octave", ::djinni::I32::Boxed::fromCpp(c.octave));
    return js;
}

} // namespace djinni_generated
