// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_objects.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, SGAccidentalType)
{
    SGAccidentalTypeNatural = 0,
    SGAccidentalTypeSharp = 1,
    SGAccidentalTypeFlat = 2,
};
