// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_dao.djinni

#import "SGChordRecord.h"
#import <Foundation/Foundation.h>
@class SGChordDAO;
@class SGSGDatabaseConnection;


@interface SGChordDAO : NSObject

+ (nullable SGChordDAO *)createChordDao:(nullable SGSGDatabaseConnection *)database;

- (nonnull NSArray<SGChordRecord *> *)getChords;

- (nullable NSNumber *)addChord:(nonnull SGChordRecord *)chord;

- (BOOL)updateChord:(nonnull SGChordRecord *)chord;

- (BOOL)deleteChord:(int32_t)id;

@end
