// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_dao.djinni

#import <Foundation/Foundation.h>

@interface SGChordRecord : NSObject
- (nonnull instancetype)init NS_UNAVAILABLE;
+ (nonnull instancetype)new NS_UNAVAILABLE;
- (nonnull instancetype)initWithId:(int32_t)id
                              name:(nonnull NSString *)name
                         intervals:(nonnull NSArray<NSNumber *> *)intervals NS_DESIGNATED_INITIALIZER;
+ (nonnull instancetype)chordRecordWithId:(int32_t)id
                                     name:(nonnull NSString *)name
                                intervals:(nonnull NSArray<NSNumber *> *)intervals;

@property (nonatomic, readonly) int32_t id;

@property (nonatomic, readonly, nonnull) NSString * name;

@property (nonatomic, readonly, nonnull) NSArray<NSNumber *> * intervals;

@end
