// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_dao.djinni

#import "SGChordRecord.h"


@implementation SGChordRecord

- (nonnull instancetype)initWithId:(nullable NSNumber *)id
                              name:(nonnull NSString *)name
                         intervals:(nonnull NSArray<NSNumber *> *)intervals
{
    if (self = [super init]) {
        _id = id;
        _name = [name copy];
        _intervals = [intervals copy];
    }
    return self;
}

+ (nonnull instancetype)chordRecordWithId:(nullable NSNumber *)id
                                     name:(nonnull NSString *)name
                                intervals:(nonnull NSArray<NSNumber *> *)intervals
{
    return [[self alloc] initWithId:id
                               name:name
                          intervals:intervals];
}

#ifndef DJINNI_DISABLE_DESCRIPTION_METHODS
- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p id:%@ name:%@ intervals:%@>", self.class, (void *)self, self.id, self.name, self.intervals];
}

#endif
@end
