// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_dao.djinni

#import "SGChordRecord.h"
#import <Foundation/Foundation.h>
@class SGChordDAO;
@class SGSGuitarDatabase;


@interface SGChordDAO : NSObject

+ (nullable SGChordDAO *)createChordDao:(nullable SGSGuitarDatabase *)database;

- (nonnull NSArray<SGChordRecord *> *)getChords;

- (int32_t)addChord:(nonnull SGChordRecord *)chord;

- (void)updateChord:(nonnull SGChordRecord *)chord;

- (void)deleteChord:(int32_t)id;

@end
