// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_dao.djinni

#import <Foundation/Foundation.h>
@class SGDatabaseConnection;


@interface SGDatabaseConnection : NSObject

+ (nullable SGDatabaseConnection *)createDatabaseConnection:(nonnull NSString *)path;

@end
