// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_objects.djinni

#import <Foundation/Foundation.h>
@class SGGuitar;
@class SGGuitarAdjustment;
@class SGGuitarString;


@interface SGGuitar : NSObject

+ (nullable SGGuitar *)create:(int32_t)numberOfFrets
                  fretMarkers:(nonnull NSArray<NSNumber *> *)fretMarkers
                guitarStrings:(nonnull NSArray<SGGuitarString *> *)guitarStrings
            guitarAdjustments:(nonnull NSDictionary<NSString *, SGGuitarAdjustment *> *)guitarAdjustments;

- (int32_t)getNumberOfFrets;

- (nonnull NSArray<NSNumber *> *)getFretMarkers;

- (nonnull NSArray<SGGuitarString *> *)getStrings;

- (void)resetStrings;

- (void)setAdjustmentActivated:(nonnull NSString *)adjustmentId
                     activated:(BOOL)activated;

- (BOOL)isAdjustmentActivated:(nonnull NSString *)adjustmentId;

- (nonnull NSString *)testDescription;

@end
