// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_dao.djinni

#import "SGGuitarAdjustmentRecord.h"
#import "SGGuitarStringRecord.h"
#import <Foundation/Foundation.h>

@interface SGGuitarRecord : NSObject
- (nonnull instancetype)init NS_UNAVAILABLE;
+ (nonnull instancetype)new NS_UNAVAILABLE;
- (nonnull instancetype)initWithId:(int32_t)id
                              name:(nonnull NSString *)name
                     numberOfFrets:(int32_t)numberOfFrets
                       fretMarkers:(nonnull NSArray<NSNumber *> *)fretMarkers
                              type:(int32_t)type
                     guitarStrings:(nonnull NSArray<SGGuitarStringRecord *> *)guitarStrings
                 guitarAdjustments:(nonnull NSArray<SGGuitarAdjustmentRecord *> *)guitarAdjustments NS_DESIGNATED_INITIALIZER;
+ (nonnull instancetype)guitarRecordWithId:(int32_t)id
                                      name:(nonnull NSString *)name
                             numberOfFrets:(int32_t)numberOfFrets
                               fretMarkers:(nonnull NSArray<NSNumber *> *)fretMarkers
                                      type:(int32_t)type
                             guitarStrings:(nonnull NSArray<SGGuitarStringRecord *> *)guitarStrings
                         guitarAdjustments:(nonnull NSArray<SGGuitarAdjustmentRecord *> *)guitarAdjustments;

@property (nonatomic, readonly) int32_t id;

@property (nonatomic, readonly, nonnull) NSString * name;

@property (nonatomic, readonly) int32_t numberOfFrets;

@property (nonatomic, readonly, nonnull) NSArray<NSNumber *> * fretMarkers;

@property (nonatomic, readonly) int32_t type;

@property (nonatomic, readonly, nonnull) NSArray<SGGuitarStringRecord *> * guitarStrings;

@property (nonatomic, readonly, nonnull) NSArray<SGGuitarAdjustmentRecord *> * guitarAdjustments;

@end
