// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_dao.djinni

#import "SGGuitarStringRecord.h"


@implementation SGGuitarStringRecord

- (nonnull instancetype)initWithId:(nullable NSNumber *)id
                          guitarId:(int32_t)guitarId
                      stringNumber:(int32_t)stringNumber
                         startNote:(nonnull NSString *)startNote
                            octave:(int32_t)octave
{
    if (self = [super init]) {
        _id = id;
        _guitarId = guitarId;
        _stringNumber = stringNumber;
        _startNote = [startNote copy];
        _octave = octave;
    }
    return self;
}

+ (nonnull instancetype)guitarStringRecordWithId:(nullable NSNumber *)id
                                        guitarId:(int32_t)guitarId
                                    stringNumber:(int32_t)stringNumber
                                       startNote:(nonnull NSString *)startNote
                                          octave:(int32_t)octave
{
    return [[self alloc] initWithId:id
                           guitarId:guitarId
                       stringNumber:stringNumber
                          startNote:startNote
                             octave:octave];
}

#ifndef DJINNI_DISABLE_DESCRIPTION_METHODS
- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p id:%@ guitarId:%@ stringNumber:%@ startNote:%@ octave:%@>", self.class, (void *)self, self.id, @(self.guitarId), @(self.stringNumber), self.startNote, @(self.octave)];
}

#endif
@end
