// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_dao.djinni

#import "SGGuitarRecord.h"


@implementation SGGuitarRecord

- (nonnull instancetype)initWithId:(int32_t)id
                              name:(nonnull NSString *)name
                     numberOfFrets:(int32_t)numberOfFrets
                       fretMarkers:(nonnull NSArray<NSNumber *> *)fretMarkers
                     guitarStrings:(nonnull NSArray<SGGuitarStringRecord *> *)guitarStrings
                 guitarAdjustments:(nonnull NSArray<SGGuitarAdjustmentRecord *> *)guitarAdjustments
{
    if (self = [super init]) {
        _id = id;
        _name = [name copy];
        _numberOfFrets = numberOfFrets;
        _fretMarkers = [fretMarkers copy];
        _guitarStrings = [guitarStrings copy];
        _guitarAdjustments = [guitarAdjustments copy];
    }
    return self;
}

+ (nonnull instancetype)guitarRecordWithId:(int32_t)id
                                      name:(nonnull NSString *)name
                             numberOfFrets:(int32_t)numberOfFrets
                               fretMarkers:(nonnull NSArray<NSNumber *> *)fretMarkers
                             guitarStrings:(nonnull NSArray<SGGuitarStringRecord *> *)guitarStrings
                         guitarAdjustments:(nonnull NSArray<SGGuitarAdjustmentRecord *> *)guitarAdjustments
{
    return [[self alloc] initWithId:id
                               name:name
                      numberOfFrets:numberOfFrets
                        fretMarkers:fretMarkers
                      guitarStrings:guitarStrings
                  guitarAdjustments:guitarAdjustments];
}

#ifndef DJINNI_DISABLE_DESCRIPTION_METHODS
- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p id:%@ name:%@ numberOfFrets:%@ fretMarkers:%@ guitarStrings:%@ guitarAdjustments:%@>", self.class, (void *)self, @(self.id), self.name, @(self.numberOfFrets), self.fretMarkers, self.guitarStrings, self.guitarAdjustments];
}

#endif
@end
