// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_factory.djinni

#import "SGChordRecord.h"
#import "SGGuitarRecord.h"
#import "SGNoteValue.h"
#import "SGScaleRecord.h"
#import <Foundation/Foundation.h>
@class SGChord;
@class SGGuitar;
@class SGScale;


@interface SGGuitarFactory : NSObject

+ (nullable SGGuitar *)createGuitar:(nonnull SGGuitarRecord *)guitarRecord;

+ (nullable SGScale *)createScale:(SGNoteValue)rootNote
                      scaleRecord:(nonnull SGScaleRecord *)scaleRecord;

+ (nullable SGChord *)createChord:(SGNoteValue)rootNote
                      chordRecord:(nonnull SGChordRecord *)chordRecord;

@end
