// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_dao.djinni

#import <Foundation/Foundation.h>

@interface SGGuitarStringAdjustmentRecord : NSObject
- (nonnull instancetype)init NS_UNAVAILABLE;
+ (nonnull instancetype)new NS_UNAVAILABLE;
- (nonnull instancetype)initWithId:(nullable NSNumber *)id
                guitarAdjustmentId:(int32_t)guitarAdjustmentId
                      stringNumber:(int32_t)stringNumber
                              step:(int32_t)step NS_DESIGNATED_INITIALIZER;
+ (nonnull instancetype)guitarStringAdjustmentRecordWithId:(nullable NSNumber *)id
                                        guitarAdjustmentId:(int32_t)guitarAdjustmentId
                                              stringNumber:(int32_t)stringNumber
                                                      step:(int32_t)step;

@property (nonatomic, readonly, nullable) NSNumber * id;

@property (nonatomic, readonly) int32_t guitarAdjustmentId;

@property (nonatomic, readonly) int32_t stringNumber;

@property (nonatomic, readonly) int32_t step;

@end
