// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_objects.djinni

#import <Foundation/Foundation.h>
@class SGGuitarAdjustment;
@class SGStringAdjustment;


@interface SGGuitarAdjustment : NSObject

+ (nullable SGGuitarAdjustment *)createWithStringAdjustments:(nonnull NSArray<SGStringAdjustment *> *)stringAdjustments
                                                    position:(int32_t)position
                                                       order:(int32_t)order;

- (nonnull NSArray<SGStringAdjustment *> *)getStringAdjustments;

- (int32_t)getPosition;

- (int32_t)getOrder;

- (void)setActivated:(BOOL)activated;

- (BOOL)isActivated;

- (nonnull NSString *)testDescription;

@end
