// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_dao.djinni

#import <Foundation/Foundation.h>

@interface SGGuitarStringRecord : NSObject
- (nonnull instancetype)init NS_UNAVAILABLE;
+ (nonnull instancetype)new NS_UNAVAILABLE;
- (nonnull instancetype)initWithId:(int32_t)id
                          guitarId:(int32_t)guitarId
                      stringNumber:(int32_t)stringNumber
                         startNote:(nonnull NSString *)startNote
                            octave:(int32_t)octave NS_DESIGNATED_INITIALIZER;
+ (nonnull instancetype)guitarStringRecordWithId:(int32_t)id
                                        guitarId:(int32_t)guitarId
                                    stringNumber:(int32_t)stringNumber
                                       startNote:(nonnull NSString *)startNote
                                          octave:(int32_t)octave;

@property (nonatomic, readonly) int32_t id;

@property (nonatomic, readonly) int32_t guitarId;

@property (nonatomic, readonly) int32_t stringNumber;

@property (nonatomic, readonly, nonnull) NSString * startNote;

@property (nonatomic, readonly) int32_t octave;

@end
