// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_dao.djinni

#import "SGGuitarRecord.h"
#import <Foundation/Foundation.h>
@class SGGuitarDAO;
@class SGSGuitarDatabase;


@interface SGGuitarDAO : NSObject

+ (nullable SGGuitarDAO *)createGuitarDao:(nullable SGSGuitarDatabase *)database;

- (nonnull NSArray<SGGuitarRecord *> *)getGuitars;

- (nullable NSNumber *)addGuitar:(nonnull SGGuitarRecord *)guitar;

- (BOOL)updateGuitar:(nonnull SGGuitarRecord *)guitar;

- (BOOL)deleteGuitar:(int32_t)id;

@end
