// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_dao.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, SGGuitarAdjustmentPosition)
{
    SGGuitarAdjustmentPositionTop = 0,
    SGGuitarAdjustmentPositionBottom = 1,
};
