// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_dao.djinni

#import "SGGuitarRecord.h"
#import <Foundation/Foundation.h>
@class SGDatabaseConnection;
@class SGGuitarDAO;


@interface SGGuitarDAO : NSObject

+ (nullable SGGuitarDAO *)createGuitarDao:(nullable SGDatabaseConnection *)databaseConnection;

- (nonnull NSArray<SGGuitarRecord *> *)getGuitars;

- (nullable NSNumber *)addGuitar:(nonnull SGGuitarRecord *)guitar;

- (BOOL)updateGuitar:(nonnull SGGuitarRecord *)guitar;

- (BOOL)deleteGuitar:(int32_t)id;

@end
