// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_import.djinni

#import "SGGuitarRecord.h"
#import <Foundation/Foundation.h>
@class SGGuitarDAO;


@interface SGGuitarImport : NSObject

+ (BOOL)importJsonGuitarFromPath:(nonnull NSString *)fromPath
                     toGuitarDAO:(nullable SGGuitarDAO *)toGuitarDAO;

+ (nonnull SGGuitarRecord *)convertJsonToGuitarRecord:(nonnull NSString *)filename
                                                 json:(nonnull NSString *)json;

@end
