// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_dao.djinni

#import "SGGuitarStringAdjustmentRecord.h"
#import <Foundation/Foundation.h>

@interface SGGuitarAdjustmentRecord : NSObject
- (nonnull instancetype)init NS_UNAVAILABLE;
+ (nonnull instancetype)new NS_UNAVAILABLE;
- (nonnull instancetype)initWithId:(int32_t)id
                          guitarId:(int32_t)guitarId
                              name:(nonnull NSString *)name
           guitarStringAdjustments:(nonnull NSArray<SGGuitarStringAdjustmentRecord *> *)guitarStringAdjustments NS_DESIGNATED_INITIALIZER;
+ (nonnull instancetype)guitarAdjustmentRecordWithId:(int32_t)id
                                            guitarId:(int32_t)guitarId
                                                name:(nonnull NSString *)name
                             guitarStringAdjustments:(nonnull NSArray<SGGuitarStringAdjustmentRecord *> *)guitarStringAdjustments;

@property (nonatomic) int32_t id;

@property (nonatomic) int32_t guitarId;

@property (nonatomic, copy, nonnull) NSString * name;

@property (nonatomic, copy, nonnull) NSArray<SGGuitarStringAdjustmentRecord *> * guitarStringAdjustments;

@end
