// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_dao.djinni

#import "SGScaleRecord.h"
#import <Foundation/Foundation.h>
@class SGSGDatabaseConnection;
@class SGScaleDAO;


@interface SGScaleDAO : NSObject

+ (nullable SGScaleDAO *)createScaleDao:(nullable SGSGDatabaseConnection *)database;

- (nonnull NSArray<SGScaleRecord *> *)getScales;

- (nullable NSNumber *)addScale:(nonnull SGScaleRecord *)scale;

- (BOOL)updateScale:(nonnull SGScaleRecord *)scale;

- (BOOL)deleteScale:(int32_t)id;

@end
