// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_dao.djinni

#import <Foundation/Foundation.h>

@interface SGScaleRecord : NSObject
- (nonnull instancetype)init NS_UNAVAILABLE;
+ (nonnull instancetype)new NS_UNAVAILABLE;
- (nonnull instancetype)initWithId:(nullable NSNumber *)id
                              name:(nonnull NSString *)name
                         semitones:(nonnull NSArray<NSNumber *> *)semitones NS_DESIGNATED_INITIALIZER;
+ (nonnull instancetype)scaleRecordWithId:(nullable NSNumber *)id
                                     name:(nonnull NSString *)name
                                semitones:(nonnull NSArray<NSNumber *> *)semitones;

@property (nonatomic, readonly, nullable) NSNumber * id;

@property (nonatomic, readonly, nonnull) NSString * name;

@property (nonatomic, readonly, nonnull) NSArray<NSNumber *> * semitones;

@end
