// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_dao.djinni

#import <Foundation/Foundation.h>
@class SGSGDatabaseConnection;


@interface SGSGDatabaseConnection : NSObject

+ (nullable SGSGDatabaseConnection *)createSgdatabaseConnection:(nonnull NSString *)path;

@end
