// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_dao.djinni

#import <Foundation/Foundation.h>
@class SGSGuitarDatabase;

extern int32_t const SGSGuitarDatabaseSGUITARDBUNSET;

@interface SGSGuitarDatabase : NSObject

+ (nullable SGSGuitarDatabase *)createSguitarDatabase:(nonnull NSString *)path;

@end
