[package]
name = "sguitar"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib", "staticlib"]
name = "sguitar"

[dependencies]
uniffi = { version = "0.28.1", features = ["cli"] }

[build-dependencies]
uniffi = { version = "0.28.1", features = [ "build" ] }

[[bin]]
name = "uniffi-bindgen"
path = "uniffi-bindgen.rs"
