INSERT INTO guitar_adjustment(guitar_id, name) VALUES (1, "P1");
INSERT INTO guitar_adjustment(guitar_id, name) VALUES (1, "P2");
INSERT INTO guitar_adjustment(guitar_id, name) VALUES (1, "P3");
INSERT INTO guitar_adjustment(guitar_id, name) VALUES (1, "LKL");
INSERT INTO guitar_adjustment(guitar_id, name) VALUES (1, "LKV");
INSERT INTO guitar_adjustment(guitar_id, name) VALUES (1, "LKR");
INSERT INTO guitar_adjustment(guitar_id, name) VALUES (1, "RKL");
INSERT INTO guitar_adjustment(guitar_id, name) VALUES (1, "RKR");


-- P1 - 1;
INSERT INTO string_adjustment (guitar_adjustment_id, string_number, step) VALUES (1, 5, 2);
INSERT INTO string_adjustment (guitar_adjustment_id, string_number, step) VALUES (1, 10, 2);
-- P2 - 2;
INSERT INTO string_adjustment (guitar_adjustment_id, string_number, step) VALUES (2, 3, 1);
INSERT INTO string_adjustment (guitar_adjustment_id, string_number, step) VALUES (2, 6, 1);
-- P3 - 3;
INSERT INTO string_adjustment (guitar_adjustment_id, string_number, step) VALUES (3, 4, 2);
INSERT INTO string_adjustment (guitar_adjustment_id, string_number, step) VALUES (3, 5, 2);
-- LKL - 4;
INSERT INTO string_adjustment (guitar_adjustment_id, string_number, step) VALUES (4, 4, 1);
INSERT INTO string_adjustment (guitar_adjustment_id, string_number, step) VALUES (4, 8, 1);
-- LKV - 5;
INSERT INTO string_adjustment (guitar_adjustment_id, string_number, step) VALUES (5, 5, -1);
INSERT INTO string_adjustment (guitar_adjustment_id, string_number, step) VALUES (5, 10, -1);
-- LKR - 6;
INSERT INTO string_adjustment (guitar_adjustment_id, string_number, step) VALUES (6, 4, 1);
INSERT INTO string_adjustment (guitar_adjustment_id, string_number, step) VALUES (6, 8, 1);
-- RKL - 7;
INSERT INTO string_adjustment (guitar_adjustment_id, string_number, step) VALUES (7, 1, 2);
INSERT INTO string_adjustment (guitar_adjustment_id, string_number, step) VALUES (7, 2, 2);
INSERT INTO string_adjustment (guitar_adjustment_id, string_number, step) VALUES (7, 6, -2);
-- RKR - 8;
INSERT INTO string_adjustment (guitar_adjustment_id, string_number, step) VALUES (8, 2, -1);
INSERT INTO string_adjustment (guitar_adjustment_id, string_number, step) VALUES (8, 9, -1);
