// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_dao.djinni

#pragma once

#include <functional>

enum class AdjustmentPosition : int {
    TOP = 0,
    BOTTOM = 1,
};

constexpr const char* to_string(AdjustmentPosition e) noexcept {
    constexpr const char* names[] = {
        "top",
        "bottom",
    };
    return names[static_cast<int>(e)];
}

namespace std {

template <>
struct hash<::AdjustmentPosition> {
    size_t operator()(::AdjustmentPosition type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

} // namespace std
