// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_dao.djinni

#pragma once

#include <cstdint>
#include <memory>
#include <optional>
#include <vector>

class SGDatabaseConnection;
struct ChordRecord;

class ChordDAO {
public:
    virtual ~ChordDAO() = default;

    static /*not-null*/ std::shared_ptr<ChordDAO> create_chord_dao(const /*not-null*/ std::shared_ptr<SGDatabaseConnection> & database);

    virtual std::vector<ChordRecord> get_chords() = 0;

    virtual std::optional<int32_t> add_chord(const ChordRecord & chord) = 0;

    virtual bool update_chord(const ChordRecord & chord) = 0;

    virtual bool delete_chord(int32_t id) = 0;
};
