// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_dao.djinni

#pragma once

#include <memory>
#include <string>

class DatabaseConnection {
public:
    virtual ~DatabaseConnection() = default;

    static /*not-null*/ std::shared_ptr<DatabaseConnection> create_database_connection(const std::string & path);
};
