// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_dao.djinni

#pragma once

#include <cstdint>
#include <optional>
#include <utility>

struct GuitarStringAdjustmentRecord final {
    std::optional<int32_t> id;
    int32_t guitar_adjustment_id;
    int32_t string_number;
    int32_t step;

    GuitarStringAdjustmentRecord(std::optional<int32_t> id_,
                                 int32_t guitar_adjustment_id_,
                                 int32_t string_number_,
                                 int32_t step_)
    : id(std::move(id_))
    , guitar_adjustment_id(std::move(guitar_adjustment_id_))
    , string_number(std::move(string_number_))
    , step(std::move(step_))
    {}
};
