// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_objects.djinni

#pragma once

#include <cstdint>
#include <memory>
#include <string>
#include <unordered_map>
#include <vector>

class GuitarAdjustment;
class GuitarString;

class Guitar {
public:
    virtual ~Guitar() = default;

    static /*not-null*/ std::shared_ptr<Guitar> create(int32_t number_of_frets, const std::vector<int32_t> & fret_markers, const std::vector</*not-null*/ std::shared_ptr<GuitarString>> & guitar_strings, const std::unordered_map<std::string, /*not-null*/ std::shared_ptr<GuitarAdjustment>> & guitar_adjustments);

    virtual int32_t get_number_of_frets() = 0;

    virtual std::vector<int32_t> get_fret_markers() = 0;

    virtual std::vector</*not-null*/ std::shared_ptr<GuitarString>> get_strings() = 0;

    virtual void reset_strings() = 0;

    virtual std::unordered_map<std::string, /*not-null*/ std::shared_ptr<GuitarAdjustment>> get_guitar_adjustments() = 0;

    virtual void set_adjustment_activated(const std::string & adjustment_id, bool activated) = 0;

    virtual bool is_adjustment_activated(const std::string & adjustment_id) = 0;

    virtual std::string test_description() = 0;
};
