// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_dao.djinni

#pragma once

#include <cstdint>
#include <memory>
#include <optional>
#include <vector>

class DatabaseConnection;
struct GuitarRecord;

class GuitarDAO {
public:
    virtual ~GuitarDAO() = default;

    static /*not-null*/ std::shared_ptr<GuitarDAO> create_guitar_dao(const /*not-null*/ std::shared_ptr<DatabaseConnection> & database_connection);

    virtual std::vector<GuitarRecord> get_guitars() = 0;

    virtual std::optional<int32_t> add_guitar(const GuitarRecord & guitar) = 0;

    virtual bool update_guitar(const GuitarRecord & guitar) = 0;

    virtual bool delete_guitar(int32_t id) = 0;
};
