// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_objects.djinni

#pragma once

#include <cstdint>
#include <memory>
#include <string>

enum class NoteValue;

class Note {
public:
    virtual ~Note() = default;

    static /*not-null*/ std::shared_ptr<Note> create_with_note(NoteValue note, int32_t octave);

    static /*not-null*/ std::shared_ptr<Note> create_with_midi_note(int32_t midi_note);

    virtual int32_t get_midi_note() = 0;

    virtual NoteValue get_note() = 0;

    virtual int32_t get_octave() = 0;

    virtual std::string test_description() = 0;

    virtual std::string note_name_sharp() = 0;

    virtual std::string note_name_flat() = 0;

    static std::string note_name_sharp_for_note(NoteValue note);

    static std::string note_name_flat_for_note(NoteValue note);

    static NoteValue note_value_for_note_string(const std::string & note_string);
};
