// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_dao.djinni

#pragma once

#include <cstdint>
#include <memory>
#include <optional>
#include <vector>

class SGDatabaseConnection;
struct ScaleRecord;

class ScaleDAO {
public:
    virtual ~ScaleDAO() = default;

    static /*not-null*/ std::shared_ptr<ScaleDAO> create_scale_dao(const /*not-null*/ std::shared_ptr<SGDatabaseConnection> & database);

    virtual std::vector<ScaleRecord> get_scales() = 0;

    virtual std::optional<int32_t> add_scale(const ScaleRecord & scale) = 0;

    virtual bool update_scale(const ScaleRecord & scale) = 0;

    virtual bool delete_scale(int32_t id) = 0;
};
