// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_dao.djinni

#pragma once

#include <cstdint>
#include <optional>
#include <string>
#include <utility>
#include <vector>

struct ScaleRecord final {
    std::optional<int32_t> id;
    std::string name;
    std::vector<int32_t> semitones;

    ScaleRecord(std::optional<int32_t> id_,
                std::string name_,
                std::vector<int32_t> semitones_)
    : id(std::move(id_))
    , name(std::move(name_))
    , semitones(std::move(semitones_))
    {}
};
