// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_dao.djinni

#pragma once

#include <memory>
#include <string>

class SGDatabaseConnection {
public:
    virtual ~SGDatabaseConnection() = default;

    static /*not-null*/ std::shared_ptr<SGDatabaseConnection> create_SGDatabase_connection(const std::string & path);
};
