// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_import.djinni

#pragma once

#include <memory>
#include <string>

class GuitarDAO;
struct GuitarRecord;

class SGuitarImport {
public:
    virtual ~SGuitarImport() = default;

    static bool importJsonGuitarFromPath(const std::string & fromPath, const /*not-null*/ std::shared_ptr<GuitarDAO> & toGuitarDAO);

    static GuitarRecord convertJsonToGuitarRecord(const std::string & json);
};
