// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_factory.djinni

#pragma once

#include <memory>

class Chord;
class Guitar;
class Scale;
enum class NoteValue;
struct ChordRecord;
struct GuitarRecord;
struct ScaleRecord;

class SGuitarFactory {
public:
    virtual ~SGuitarFactory() = default;

    static /*not-null*/ std::shared_ptr<Guitar> create_guitar(const GuitarRecord & guitar_record);

    static /*not-null*/ std::shared_ptr<Scale> create_scale(NoteValue root_note, const ScaleRecord & scale_record);

    static /*not-null*/ std::shared_ptr<Chord> create_chord(NoteValue root_note, const ChordRecord & chord_record);
};
