// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_dao.djinni

#import "SGChordDAO+Private.h"
#import "SGChordDAO.h"
#import "DJICppWrapperCache+Private.h"
#import "DJIError.h"
#import "DJIMarshal+Private.h"
#import "SGChordRecord+Private.h"
#import "SGSGuitarDatabase+Private.h"
#include <exception>
#include <stdexcept>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface SGChordDAO ()

- (id)initWithCpp:(const std::shared_ptr<::ChordDAO>&)cppRef;

@end

@implementation SGChordDAO {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::ChordDAO>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::ChordDAO>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

+ (nullable SGChordDAO *)createChordDao:(nullable SGSGuitarDatabase *)database {
    try {
        auto objcpp_result_ = ::ChordDAO::create_chord_dao(::djinni_generated::SGuitarDatabase::toCpp(database));
        return ::djinni_generated::ChordDAO::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (nonnull NSArray<SGChordRecord *> *)getChords {
    try {
        auto objcpp_result_ = _cppRefHandle.get()->get_chords();
        return ::djinni::Array<::djinni_generated::ChordRecord>::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (nullable NSNumber *)addChord:(nonnull SGChordRecord *)chord {
    try {
        auto objcpp_result_ = _cppRefHandle.get()->add_chord(::djinni_generated::ChordRecord::toCpp(chord));
        return ::djinni::Optional<std::optional, ::djinni::I32>::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (BOOL)updateChord:(nonnull SGChordRecord *)chord {
    try {
        auto objcpp_result_ = _cppRefHandle.get()->update_chord(::djinni_generated::ChordRecord::toCpp(chord));
        return ::djinni::Bool::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (BOOL)deleteChord:(int32_t)id {
    try {
        auto objcpp_result_ = _cppRefHandle.get()->delete_chord(::djinni::I32::toCpp(id));
        return ::djinni::Bool::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace djinni_generated {

auto ChordDAO::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return objc->_cppRefHandle.get();
}

auto ChordDAO::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return ::djinni::get_cpp_proxy<SGChordDAO>(cpp);
}

} // namespace djinni_generated

@end
