// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_dao.djinni

#import "SGChordRecord.h"
#include "chord_record.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class SGChordRecord;

namespace djinni_generated {

struct ChordRecord
{
    using CppType = ::ChordRecord;
    using ObjcType = SGChordRecord*;

    using Boxed = ChordRecord;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

} // namespace djinni_generated
