// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_dao.djinni

#include "chord_DAO.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class SGChordDAO;

namespace djinni_generated {

class ChordDAO
{
public:
    using CppType = std::shared_ptr<::ChordDAO>;
    using CppOptType = std::shared_ptr<::ChordDAO>;
    using ObjcType = SGChordDAO*;

    using Boxed = ChordDAO;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

} // namespace djinni_generated

