// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_dao.djinni

#include "database_connection.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class SGDatabaseConnection;

namespace djinni_generated {

class DatabaseConnection
{
public:
    using CppType = std::shared_ptr<::DatabaseConnection>;
    using CppOptType = std::shared_ptr<::DatabaseConnection>;
    using ObjcType = SGDatabaseConnection*;

    using Boxed = DatabaseConnection;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

} // namespace djinni_generated

