// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_dao.djinni

#import "SGDatabaseConnection+Private.h"
#import "SGDatabaseConnection.h"
#import "DJICppWrapperCache+Private.h"
#import "DJIError.h"
#import "DJIMarshal+Private.h"
#include <exception>
#include <stdexcept>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface SGDatabaseConnection ()

- (id)initWithCpp:(const std::shared_ptr<::DatabaseConnection>&)cppRef;

@end

@implementation SGDatabaseConnection {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::DatabaseConnection>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::DatabaseConnection>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

+ (nullable SGDatabaseConnection *)createDatabaseConnection:(nonnull NSString *)path {
    try {
        auto objcpp_result_ = ::DatabaseConnection::create_database_connection(::djinni::String::toCpp(path));
        return ::djinni_generated::DatabaseConnection::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace djinni_generated {

auto DatabaseConnection::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return objc->_cppRefHandle.get();
}

auto DatabaseConnection::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return ::djinni::get_cpp_proxy<SGDatabaseConnection>(cpp);
}

} // namespace djinni_generated

@end
