// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_objects.djinni

#ifdef __cplusplus
#include "guitar_adjustment.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class SGGuitarAdjustment;

namespace djinni_generated {

class GuitarAdjustment
{
public:
    using CppType = std::shared_ptr<::GuitarAdjustment>;
    using CppOptType = std::shared_ptr<::GuitarAdjustment>;
    using ObjcType = SGGuitarAdjustment*;

    using Boxed = GuitarAdjustment;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

} // namespace djinni_generated

#endif // __cplusplus
