// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_objects.djinni

#import "SGGuitarAdjustment+Private.h"
#import "SGGuitarAdjustment.h"
#import "DJICppWrapperCache+Private.h"
#import "DJIError.h"
#import "DJIMarshal+Private.h"
#import "SGStringAdjustment+Private.h"
#include <exception>
#include <stdexcept>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface SGGuitarAdjustment ()

- (id)initWithCpp:(const std::shared_ptr<::GuitarAdjustment>&)cppRef;

@end

@implementation SGGuitarAdjustment {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::GuitarAdjustment>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::GuitarAdjustment>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

+ (nullable SGGuitarAdjustment *)createWithStringAdjustments:(nonnull NSArray<SGStringAdjustment *> *)stringAdjustments
                                                    position:(int32_t)position
                                                       order:(int32_t)order {
    try {
        auto objcpp_result_ = ::GuitarAdjustment::create_with_string_adjustments(::djinni::Array<::djinni_generated::StringAdjustment>::toCpp(stringAdjustments),
                                                                                 ::djinni::I32::toCpp(position),
                                                                                 ::djinni::I32::toCpp(order));
        return ::djinni_generated::GuitarAdjustment::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (nonnull NSArray<SGStringAdjustment *> *)getStringAdjustments {
    try {
        auto objcpp_result_ = _cppRefHandle.get()->get_string_adjustments();
        return ::djinni::Array<::djinni_generated::StringAdjustment>::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (int32_t)getPosition {
    try {
        auto objcpp_result_ = _cppRefHandle.get()->get_position();
        return ::djinni::I32::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (int32_t)getOrder {
    try {
        auto objcpp_result_ = _cppRefHandle.get()->get_order();
        return ::djinni::I32::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (void)setActivated:(BOOL)activated {
    try {
        _cppRefHandle.get()->set_activated(::djinni::Bool::toCpp(activated));
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (BOOL)isActivated {
    try {
        auto objcpp_result_ = _cppRefHandle.get()->is_activated();
        return ::djinni::Bool::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (nonnull NSString *)testDescription {
    try {
        auto objcpp_result_ = _cppRefHandle.get()->test_description();
        return ::djinni::String::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace djinni_generated {

auto GuitarAdjustment::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return objc->_cppRefHandle.get();
}

auto GuitarAdjustment::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return ::djinni::get_cpp_proxy<SGGuitarAdjustment>(cpp);
}

} // namespace djinni_generated

@end
