// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_dao.djinni

#import "SGGuitarStringRecord+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto GuitarStringRecord::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::I32::toCpp(obj.id),
            ::djinni::I32::toCpp(obj.guitarId),
            ::djinni::I32::toCpp(obj.stringNumber),
            ::djinni::String::toCpp(obj.startNote),
            ::djinni::I32::toCpp(obj.octave)};
}

auto GuitarStringRecord::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[SGGuitarStringRecord alloc] initWithId:(::djinni::I32::fromCpp(cpp.id))
                                           guitarId:(::djinni::I32::fromCpp(cpp.guitar_id))
                                       stringNumber:(::djinni::I32::fromCpp(cpp.string_number))
                                          startNote:(::djinni::String::fromCpp(cpp.start_note))
                                             octave:(::djinni::I32::fromCpp(cpp.octave))];
}

} // namespace djinni_generated
