// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_import.djinni

#include "guitar_import.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class SGGuitarImport;

namespace djinni_generated {

class GuitarImport
{
public:
    using CppType = std::shared_ptr<::GuitarImport>;
    using CppOptType = std::shared_ptr<::GuitarImport>;
    using ObjcType = SGGuitarImport*;

    using Boxed = GuitarImport;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

} // namespace djinni_generated

