// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_factory.djinni

#include "guitar_factory.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class SGGuitarFactory;

namespace djinni_generated {

class GuitarFactory
{
public:
    using CppType = std::shared_ptr<::GuitarFactory>;
    using CppOptType = std::shared_ptr<::GuitarFactory>;
    using ObjcType = SGGuitarFactory*;

    using Boxed = GuitarFactory;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

} // namespace djinni_generated

