// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_objects.djinni

#include "guitar.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class SGGuitar;

namespace djinni_generated {

class Guitar
{
public:
    using CppType = std::shared_ptr<::Guitar>;
    using CppOptType = std::shared_ptr<::Guitar>;
    using ObjcType = SGGuitar*;

    using Boxed = Guitar;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

} // namespace djinni_generated

