// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_objects.djinni

#import "SGGuitar+Private.h"
#import "SGGuitar.h"
#import "DJICppWrapperCache+Private.h"
#import "DJIError.h"
#import "DJIMarshal+Private.h"
#import "SGGuitarAdjustment+Private.h"
#import "SGGuitarString+Private.h"
#include <exception>
#include <stdexcept>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface SGGuitar ()

- (id)initWithCpp:(const std::shared_ptr<::Guitar>&)cppRef;

@end

@implementation SGGuitar {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::Guitar>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::Guitar>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

+ (nullable SGGuitar *)create:(int32_t)numberOfFrets
                  fretMarkers:(nonnull NSArray<NSNumber *> *)fretMarkers
                guitarStrings:(nonnull NSArray<SGGuitarString *> *)guitarStrings
            guitarAdjustments:(nonnull NSDictionary<NSString *, SGGuitarAdjustment *> *)guitarAdjustments {
    try {
        auto objcpp_result_ = ::Guitar::create(::djinni::I32::toCpp(numberOfFrets),
                                               ::djinni::Array<::djinni::I32>::toCpp(fretMarkers),
                                               ::djinni::Array<::djinni_generated::GuitarString>::toCpp(guitarStrings),
                                               ::djinni::Map<::djinni::String, ::djinni_generated::GuitarAdjustment>::toCpp(guitarAdjustments));
        return ::djinni_generated::Guitar::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (nonnull NSArray<SGGuitarString *> *)getStrings {
    try {
        auto objcpp_result_ = _cppRefHandle.get()->get_strings();
        return ::djinni::Array<::djinni_generated::GuitarString>::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (void)resetStrings {
    try {
        _cppRefHandle.get()->reset_strings();
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (void)setAdjustmentActivated:(nonnull NSString *)adjustmentId
                     activated:(BOOL)activated {
    try {
        _cppRefHandle.get()->set_adjustment_activated(::djinni::String::toCpp(adjustmentId),
                                                      ::djinni::Bool::toCpp(activated));
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (BOOL)isAdjustmentActivated:(nonnull NSString *)adjustmentId {
    try {
        auto objcpp_result_ = _cppRefHandle.get()->is_adjustment_activated(::djinni::String::toCpp(adjustmentId));
        return ::djinni::Bool::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (nonnull NSString *)testDescription {
    try {
        auto objcpp_result_ = _cppRefHandle.get()->test_description();
        return ::djinni::String::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace djinni_generated {

auto Guitar::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return objc->_cppRefHandle.get();
}

auto Guitar::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return ::djinni::get_cpp_proxy<SGGuitar>(cpp);
}

} // namespace djinni_generated

@end
