// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_dao.djinni

#import "SGGuitarDAO+Private.h"
#import "SGGuitarDAO.h"
#import "DJICppWrapperCache+Private.h"
#import "DJIError.h"
#import "DJIMarshal+Private.h"
#import "SGGuitarRecord+Private.h"
#import "SGSGDatabaseConnection+Private.h"
#include <exception>
#include <stdexcept>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface SGGuitarDAO ()

- (id)initWithCpp:(const std::shared_ptr<::GuitarDAO>&)cppRef;

@end

@implementation SGGuitarDAO {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::GuitarDAO>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::GuitarDAO>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

+ (nullable SGGuitarDAO *)createGuitarDao:(nullable SGSGDatabaseConnection *)database {
    try {
        auto objcpp_result_ = ::GuitarDAO::create_guitar_dao(::djinni_generated::SGDatabaseConnection::toCpp(database));
        return ::djinni_generated::GuitarDAO::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (nonnull NSArray<SGGuitarRecord *> *)getGuitars {
    try {
        auto objcpp_result_ = _cppRefHandle.get()->get_guitars();
        return ::djinni::Array<::djinni_generated::GuitarRecord>::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (nullable NSNumber *)addGuitar:(nonnull SGGuitarRecord *)guitar {
    try {
        auto objcpp_result_ = _cppRefHandle.get()->add_guitar(::djinni_generated::GuitarRecord::toCpp(guitar));
        return ::djinni::Optional<std::optional, ::djinni::I32>::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (BOOL)updateGuitar:(nonnull SGGuitarRecord *)guitar {
    try {
        auto objcpp_result_ = _cppRefHandle.get()->update_guitar(::djinni_generated::GuitarRecord::toCpp(guitar));
        return ::djinni::Bool::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (BOOL)deleteGuitar:(int32_t)id {
    try {
        auto objcpp_result_ = _cppRefHandle.get()->delete_guitar(::djinni::I32::toCpp(id));
        return ::djinni::Bool::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace djinni_generated {

auto GuitarDAO::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return objc->_cppRefHandle.get();
}

auto GuitarDAO::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return ::djinni::get_cpp_proxy<SGGuitarDAO>(cpp);
}

} // namespace djinni_generated

@end
