// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_dao.djinni

#import "SGGuitarAdjustmentRecord+Private.h"
#import "DJIMarshal+Private.h"
#import "SGGuitarStringAdjustmentRecord+Private.h"
#include <cassert>

namespace djinni_generated {

auto GuitarAdjustmentRecord::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::I32::toCpp(obj.id),
            ::djinni::I32::toCpp(obj.guitarId),
            ::djinni::String::toCpp(obj.name),
            ::djinni::Array<::djinni_generated::GuitarStringAdjustmentRecord>::toCpp(obj.guitarStringAdjustments)};
}

auto GuitarAdjustmentRecord::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[SGGuitarAdjustmentRecord alloc] initWithId:(::djinni::I32::fromCpp(cpp.id))
                                               guitarId:(::djinni::I32::fromCpp(cpp.guitar_id))
                                                   name:(::djinni::String::fromCpp(cpp.name))
                                guitarStringAdjustments:(::djinni::Array<::djinni_generated::GuitarStringAdjustmentRecord>::fromCpp(cpp.guitar_string_adjustments))];
}

} // namespace djinni_generated
