// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_objects.djinni

#ifdef __cplusplus
#import "SGGuitarString+Private.h"
#import "SGGuitarString.h"
#import "DJICppWrapperCache+Private.h"
#import "DJIError.h"
#import "DJIMarshal+Private.h"
#import "SGNote+Private.h"
#include <exception>
#include <stdexcept>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface SGGuitarString ()

- (id)initWithCpp:(const std::shared_ptr<::GuitarString>&)cppRef;

@end

@implementation SGGuitarString {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::GuitarString>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::GuitarString>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

+ (nullable SGGuitarString *)create {
    try {
        auto objcpp_result_ = ::GuitarString::create();
        return ::djinni_generated::GuitarString::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

+ (nullable SGGuitarString *)createWithStartNote:(nullable SGNote *)startNote
                                   numberOfFrets:(int32_t)numberOfFrets {
    try {
        auto objcpp_result_ = ::GuitarString::create_with_start_note(::djinni_generated::Note::toCpp(startNote),
                                                                     ::djinni::I32::toCpp(numberOfFrets));
        return ::djinni_generated::GuitarString::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (nullable SGNote *)getStartNote {
    try {
        auto objcpp_result_ = _cppRefHandle.get()->get_start_note();
        return ::djinni_generated::Note::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (nonnull NSArray<SGNote *> *)getNotes {
    try {
        auto objcpp_result_ = _cppRefHandle.get()->get_notes();
        return ::djinni::Array<::djinni_generated::Note>::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (void)reset {
    try {
        _cppRefHandle.get()->reset();
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (void)adjustStringBySteps:(int32_t)steps {
    try {
        _cppRefHandle.get()->adjust_string_by_steps(::djinni::I32::toCpp(steps));
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (nonnull NSString *)testDescription {
    try {
        auto objcpp_result_ = _cppRefHandle.get()->test_description();
        return ::djinni::String::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace djinni_generated {

auto GuitarString::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return objc->_cppRefHandle.get();
}

auto GuitarString::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return ::djinni::get_cpp_proxy<SGGuitarString>(cpp);
}

} // namespace djinni_generated

@end
#endif // __cplusplus
