// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_dao.djinni

#import "SGGuitarRecord.h"
#include "guitar_record.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class SGGuitarRecord;

namespace djinni_generated {

struct GuitarRecord
{
    using CppType = ::GuitarRecord;
    using ObjcType = SGGuitarRecord*;

    using Boxed = GuitarRecord;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

} // namespace djinni_generated
