// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_dao.djinni

#import "SGGuitarStringAdjustmentRecord+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto GuitarStringAdjustmentRecord::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::Optional<std::optional, ::djinni::I32>::toCpp(obj.id),
            ::djinni::I32::toCpp(obj.guitarAdjustmentId),
            ::djinni::I32::toCpp(obj.stringNumber),
            ::djinni::I32::toCpp(obj.step)};
}

auto GuitarStringAdjustmentRecord::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[SGGuitarStringAdjustmentRecord alloc] initWithId:(::djinni::Optional<std::optional, ::djinni::I32>::fromCpp(cpp.id))
                                           guitarAdjustmentId:(::djinni::I32::fromCpp(cpp.guitar_adjustment_id))
                                                 stringNumber:(::djinni::I32::fromCpp(cpp.string_number))
                                                         step:(::djinni::I32::fromCpp(cpp.step))];
}

} // namespace djinni_generated
