// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_objects.djinni

#import "SGHarmonizedScale+Private.h"
#import "SGHarmonizedScale.h"
#import "DJICppWrapperCache+Private.h"
#import "DJIError.h"
#import "DJIMarshal+Private.h"
#import "SGChord+Private.h"
#import "SGNoteValue+Private.h"
#include <exception>
#include <stdexcept>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface SGHarmonizedScale ()

- (id)initWithCpp:(const std::shared_ptr<::HarmonizedScale>&)cppRef;

@end

@implementation SGHarmonizedScale {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::HarmonizedScale>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::HarmonizedScale>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

+ (nullable SGHarmonizedScale *)createHarmonizedScaleWithRootNote:(SGNoteValue)rootNote
                                                        semitones:(nonnull NSArray<NSNumber *> *)semitones {
    try {
        auto objcpp_result_ = ::HarmonizedScale::create_harmonized_scale_with_root_note(::djinni::Enum<::NoteValue, SGNoteValue>::toCpp(rootNote),
                                                                                        ::djinni::Array<::djinni::I32>::toCpp(semitones));
        return ::djinni_generated::HarmonizedScale::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (nonnull NSArray<SGChord *> *)getChords {
    try {
        auto objcpp_result_ = _cppRefHandle.get()->get_chords();
        return ::djinni::Array<::djinni_generated::Chord>::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (nonnull NSString *)testDescription {
    try {
        auto objcpp_result_ = _cppRefHandle.get()->test_description();
        return ::djinni::String::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace djinni_generated {

auto HarmonizedScale::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return objc->_cppRefHandle.get();
}

auto HarmonizedScale::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return ::djinni::get_cpp_proxy<SGHarmonizedScale>(cpp);
}

} // namespace djinni_generated

@end
