// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_objects.djinni

#ifdef __cplusplus
#include "note_value.hpp"
#import "DJIMarshal+Private.h"

#endif // __cplusplus
