// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_dao.djinni

#import "SGScaleRecord.h"
#include "scale_record.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class SGScaleRecord;

namespace djinni_generated {

struct ScaleRecord
{
    using CppType = ::ScaleRecord;
    using ObjcType = SGScaleRecord*;

    using Boxed = ScaleRecord;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

} // namespace djinni_generated
