// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_dao.djinni

#import "SGScaleDAO+Private.h"
#import "SGScaleDAO.h"
#import "DJICppWrapperCache+Private.h"
#import "DJIError.h"
#import "DJIMarshal+Private.h"
#import "SGSGuitarDatabase+Private.h"
#import "SGScaleRecord+Private.h"
#include <exception>
#include <stdexcept>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface SGScaleDAO ()

- (id)initWithCpp:(const std::shared_ptr<::ScaleDAO>&)cppRef;

@end

@implementation SGScaleDAO {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::ScaleDAO>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::ScaleDAO>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

+ (nullable SGScaleDAO *)createScaleDao:(nullable SGSGuitarDatabase *)database {
    try {
        auto objcpp_result_ = ::ScaleDAO::create_scale_dao(::djinni_generated::SGuitarDatabase::toCpp(database));
        return ::djinni_generated::ScaleDAO::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (nonnull NSArray<SGScaleRecord *> *)getScales {
    try {
        auto objcpp_result_ = _cppRefHandle.get()->get_scales();
        return ::djinni::Array<::djinni_generated::ScaleRecord>::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (int32_t)addScale:(nonnull SGScaleRecord *)scale {
    try {
        auto objcpp_result_ = _cppRefHandle.get()->add_scale(::djinni_generated::ScaleRecord::toCpp(scale));
        return ::djinni::I32::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (void)updateScale:(nonnull SGScaleRecord *)scale {
    try {
        _cppRefHandle.get()->update_scale(::djinni_generated::ScaleRecord::toCpp(scale));
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (void)deleteScale:(int32_t)id {
    try {
        _cppRefHandle.get()->delete_scale(::djinni::I32::toCpp(id));
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace djinni_generated {

auto ScaleDAO::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return objc->_cppRefHandle.get();
}

auto ScaleDAO::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return ::djinni::get_cpp_proxy<SGScaleDAO>(cpp);
}

} // namespace djinni_generated

@end
