// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_factory.djinni

#import "SGSGuitarFactory+Private.h"
#import "SGSGuitarFactory.h"
#import "DJICppWrapperCache+Private.h"
#import "DJIError.h"
#import "SGChord+Private.h"
#import "SGChordRecord+Private.h"
#import "SGGuitar+Private.h"
#import "SGGuitarRecord+Private.h"
#import "SGNoteValue+Private.h"
#import "SGScale+Private.h"
#import "SGScaleRecord+Private.h"
#include <exception>
#include <stdexcept>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface SGSGuitarFactory ()

- (id)initWithCpp:(const std::shared_ptr<::SGuitarFactory>&)cppRef;

@end

@implementation SGSGuitarFactory {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::SGuitarFactory>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::SGuitarFactory>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

+ (nullable SGGuitar *)createGuitar:(nonnull SGGuitarRecord *)guitarRecord {
    try {
        auto objcpp_result_ = ::SGuitarFactory::create_guitar(::djinni_generated::GuitarRecord::toCpp(guitarRecord));
        return ::djinni_generated::Guitar::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

+ (nullable SGScale *)createScale:(SGNoteValue)rootNote
                      scaleRecord:(nonnull SGScaleRecord *)scaleRecord {
    try {
        auto objcpp_result_ = ::SGuitarFactory::create_scale(::djinni::Enum<::NoteValue, SGNoteValue>::toCpp(rootNote),
                                                             ::djinni_generated::ScaleRecord::toCpp(scaleRecord));
        return ::djinni_generated::Scale::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

+ (nullable SGChord *)createChord:(SGNoteValue)rootNote
                      chordRecord:(nonnull SGChordRecord *)chordRecord {
    try {
        auto objcpp_result_ = ::SGuitarFactory::create_chord(::djinni::Enum<::NoteValue, SGNoteValue>::toCpp(rootNote),
                                                             ::djinni_generated::ChordRecord::toCpp(chordRecord));
        return ::djinni_generated::Chord::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace djinni_generated {

auto SGuitarFactory::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return objc->_cppRefHandle.get();
}

auto SGuitarFactory::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return ::djinni::get_cpp_proxy<SGSGuitarFactory>(cpp);
}

} // namespace djinni_generated

@end
