// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_dao.djinni

#import "SGSGuitarDatabase+Private.h"
#import "SGSGuitarDatabase.h"
#import "DJICppWrapperCache+Private.h"
#import "DJIError.h"
#import "DJIMarshal+Private.h"
#include <exception>
#include <stdexcept>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface SGSGuitarDatabase ()

- (id)initWithCpp:(const std::shared_ptr<::SGuitarDatabase>&)cppRef;

@end

@implementation SGSGuitarDatabase {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::SGuitarDatabase>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::SGuitarDatabase>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

+ (nullable SGSGuitarDatabase *)createSguitarDatabase:(nonnull NSString *)path {
    try {
        auto objcpp_result_ = ::SGuitarDatabase::create_sguitar_database(::djinni::String::toCpp(path));
        return ::djinni_generated::SGuitarDatabase::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace djinni_generated {

auto SGuitarDatabase::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return objc->_cppRefHandle.get();
}

auto SGuitarDatabase::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return ::djinni::get_cpp_proxy<SGSGuitarDatabase>(cpp);
}

} // namespace djinni_generated

@end
