// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_import.djinni

#import "SGSGuitarImport+Private.h"
#import "SGSGuitarImport.h"
#import "DJICppWrapperCache+Private.h"
#import "DJIError.h"
#import "DJIMarshal+Private.h"
#import "SGGuitarDAO+Private.h"
#import "SGGuitarRecord+Private.h"
#include <exception>
#include <stdexcept>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface SGSGuitarImport ()

- (id)initWithCpp:(const std::shared_ptr<::SGuitarImport>&)cppRef;

@end

@implementation SGSGuitarImport {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::SGuitarImport>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::SGuitarImport>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

+ (BOOL)importJsonGuitarFromPath:(nonnull NSString *)fromPath
                     toGuitarDAO:(nullable SGGuitarDAO *)toGuitarDAO {
    try {
        auto objcpp_result_ = ::SGuitarImport::importJsonGuitarFromPath(::djinni::String::toCpp(fromPath),
                                                                        ::djinni_generated::GuitarDAO::toCpp(toGuitarDAO));
        return ::djinni::Bool::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

+ (nonnull SGGuitarRecord *)convertJsonToGuitarRecord:(nonnull NSString *)json {
    try {
        auto objcpp_result_ = ::SGuitarImport::convertJsonToGuitarRecord(::djinni::String::toCpp(json));
        return ::djinni_generated::GuitarRecord::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace djinni_generated {

auto SGuitarImport::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return objc->_cppRefHandle.get();
}

auto SGuitarImport::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return ::djinni::get_cpp_proxy<SGSGuitarImport>(cpp);
}

} // namespace djinni_generated

@end
