// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sguitar_dao.djinni

#import "SGSGDatabaseConnection+Private.h"
#import "SGSGDatabaseConnection.h"
#import "DJICppWrapperCache+Private.h"
#import "DJIError.h"
#import "DJIMarshal+Private.h"
#include <exception>
#include <stdexcept>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface SGSGDatabaseConnection ()

- (id)initWithCpp:(const std::shared_ptr<::SGDatabaseConnection>&)cppRef;

@end

@implementation SGSGDatabaseConnection {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::SGDatabaseConnection>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::SGDatabaseConnection>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

+ (nullable SGSGDatabaseConnection *)createSgdatabaseConnection:(nonnull NSString *)path {
    try {
        auto objcpp_result_ = ::SGDatabaseConnection::create_sgdatabase_connection(::djinni::String::toCpp(path));
        return ::djinni_generated::SGDatabaseConnection::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace djinni_generated {

auto SGDatabaseConnection::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return objc->_cppRefHandle.get();
}

auto SGDatabaseConnection::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return ::djinni::get_cpp_proxy<SGSGDatabaseConnection>(cpp);
}

} // namespace djinni_generated

@end
